import test from "node:test";
import assert from "node:assert/strict";
import {generateKeyPairSync,createHash,createPublicKey} from "node:crypto";
import {spawn} from "node:child_process";
import {existsSync,mkdtempSync,writeFileSync,readFileSync,rmSync,utimesSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {appendApprovalEvent,approvalRequestSha,approvalSha,createApprovalRequest,inspectApproval,updateApproval} from "../dist/production_approval.js";
const H=(x:string|Buffer)=>createHash("sha256").update(x).digest("hex"), bindings=()=>({artifact_sha256:H("a"),archive_sha256:H("z"),manifest_sha256:H("m"),benchmark_sha256:H("b"),test_sha256:H("t"),review_sha256:H("r")});
function setup(status="pass"){const kp=generateKeyPairSync("ed25519"),pub=kp.publicKey.export({type:"spki",format:"pem"}).toString(),keyid=H(createPublicKey(pub).export({type:"spki",format:"der"})),request=createApprovalRequest({request_id:"req-1",requested_at:"2026-09-18T07:00:00Z",expires_at:"2027-09-18T07:00:00Z",requester:{id:"ci",role:"release-bot"},automated_evidence:{status,attestation_sha256:H("e")},bindings:bindings()}),policy={version:"hook-approval-trust-policy/v1",reviewers:[{id:"alice",role:"release-approver",keyid,public_key_pem:pub,actions:["review","approve","reject","expire","supersede"]}]};return{kp,request,policy}}
function decision(a:any,action:string,extra:any={}){return{action,reviewer:{id:"alice",role:"release-approver"},timestamp:"2026-09-18T07:10:00Z",rationale:"Reviewed production evidence and residual risk",accepted_risks:["documented residual"],waivers:["waiver-1"],expected_revision:a.events.length,expected_approval_sha256:approvalSha(a),...extra}}
test("automation pass remains pending, trusted human can review and approve",()=>{const x=setup();assert.equal(inspectApproval(x.request,{trustPolicy:x.policy,expectedBindings:bindings(),now:new Date("2026-09-18T09:00:00Z")}).state,"pending");let a=appendApprovalEvent(x.request,decision(x.request,"review"),x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString());a=appendApprovalEvent(a,decision(a,"approve"),x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString());assert.equal(inspectApproval(a,{trustPolicy:x.policy,expectedBindings:bindings(),now:new Date("2026-09-18T09:00:00Z")}).ok,true)});
test("anonymous, tampering, stale input and untrusted role fail",()=>{const x=setup(),pem=x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString();assert.throws(()=>appendApprovalEvent(x.request,{...decision(x.request,"approve"),reviewer:{id:"anonymous",role:"reviewer"}},pem),/anonymous/);const a=appendApprovalEvent(x.request,decision(x.request,"approve"),pem),tampered=structuredClone(a);tampered.events[0].rationale="changed";assert.equal(inspectApproval(tampered,{trustPolicy:x.policy}).ok,false);const b=bindings();b.test_sha256=H("changed");assert.equal(inspectApproval(a,{trustPolicy:x.policy,expectedBindings:b,now:new Date("2026-09-18T09:00:00Z")}).state,"stale");const wrong=structuredClone(x.policy);wrong.reviewers[0].role="other";assert.equal(inspectApproval(a,{trustPolicy:wrong}).ok,false)});
test("rejection is durable; expiry and supersession terminal",()=>{const x=setup(),pem=x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString(),r=appendApprovalEvent(x.request,decision(x.request,"reject"),pem);assert.equal(inspectApproval(r,{trustPolicy:x.policy}).state,"rejected");assert.throws(()=>appendApprovalEvent(r,decision(r,"approve"),pem),/terminal/);for(const action of ["expire","supersede"]){let a=appendApprovalEvent(x.request,decision(x.request,"approve"),pem);a=appendApprovalEvent(a,decision(a,action,action==="supersede"?{superseded_by:{request_id:"req-2",request_sha256:H("replacement")}}:{}),pem);assert.equal(inspectApproval(a,{trustPolicy:x.policy}).state,action==="expire"?"expired":"superseded")}});
test("identity normalization and chronology reject whitespace aliases, future, pre-request, and non-monotonic events",()=>{const x=setup(),pem=x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString();for(const value of [" anonymous "," AnOnYmOuS "])assert.throws(()=>appendApprovalEvent(x.request,{...decision(x.request,"approve"),reviewer:{id:value,role:"reviewer"}},pem),/anonymous/);assert.throws(()=>appendApprovalEvent(x.request,{...decision(x.request,"approve"),timestamp:"2026-09-18T06:59:59Z"},pem),/precedes/);assert.throws(()=>appendApprovalEvent(x.request,{...decision(x.request,"approve"),timestamp:"2027-09-18T07:00:00Z"},pem,new Date("2028-01-01T00:00:00Z")),/precede expires/);assert.throws(()=>appendApprovalEvent(x.request,{...decision(x.request,"approve"),timestamp:"2026-09-18T09:00:00Z"},pem,new Date("2026-09-18T08:00:00Z")),/future/);let a=appendApprovalEvent(x.request,decision(x.request,"review"),pem);assert.throws(()=>appendApprovalEvent(a,{...decision(a,"approve"),timestamp:"2026-09-18T07:09:59Z"},pem),/monotonic/)});
test("supersession requires exact replacement request hash and reciprocal lineage",()=>{const x=setup(),pem=x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString();let old=appendApprovalEvent(x.request,decision(x.request,"approve"),pem);const {version:_,events:__,...base}=x.request;const replacement=createApprovalRequest({...base,request_id:"req-2",supersedes:{request_id:old.request_id,request_sha256:approvalRequestSha(old)}});const linked=appendApprovalEvent(old,decision(old,"supersede",{superseded_by:{request_id:replacement.request_id,request_sha256:approvalRequestSha(replacement)}}),pem);const result=inspectApproval(linked,{trustPolicy:x.policy,replacementApproval:replacement,now:new Date("2026-09-18T09:00:00Z")});assert.ok(!result.errors.some((e:string)=>e.includes("lineage")||e.includes("bind replacement")));const forged=structuredClone(replacement);forged.request_id="other";assert.ok(inspectApproval(linked,{trustPolicy:x.policy,replacementApproval:forged,now:new Date("2026-09-18T09:00:00Z")}).errors.some((e:string)=>e.includes("bind replacement")))});
test("abandoned stale lock is recovered without overriding a live lock",()=>{const x=setup(),root=mkdtempSync(join(tmpdir(),"approval-lock-")),path=join(root,"approval.json"),spec=join(root,"decision.json"),key=join(root,"key.pem"),lock=path+".lock";try{writeFileSync(path,JSON.stringify(x.request));writeFileSync(spec,JSON.stringify(decision(x.request,"review")));writeFileSync(key,x.kp.privateKey.export({type:"pkcs8",format:"pem"}));writeFileSync(lock,JSON.stringify({pid:99999999}));const old=new Date(Date.now()-60_000);utimesSync(lock,old,old);assert.equal(updateApproval(path,spec,key).events.length,1);writeFileSync(spec,JSON.stringify(decision(JSON.parse(readFileSync(path,"utf8")),"approve")));writeFileSync(lock,JSON.stringify({pid:process.pid}));assert.throws(()=>updateApproval(path,spec,key),/locked by another writer/)}finally{rmSync(root,{recursive:true,force:true})}});
test("failed automation cannot be approved and optimistic concurrency rejects stale writer",()=>{const x=setup("fail"),pem=x.kp.privateKey.export({type:"pkcs8",format:"pem"}).toString();assert.throws(()=>appendApprovalEvent(x.request,decision(x.request,"approve"),pem),/must pass/);const y=setup(),root=mkdtempSync(join(tmpdir(),"approval-")),path=join(root,"approval.json"),spec=join(root,"decision.json"),key=join(root,"key.pem");try{writeFileSync(path,JSON.stringify(y.request));writeFileSync(spec,JSON.stringify(decision(y.request,"review")));writeFileSync(key,y.kp.privateKey.export({type:"pkcs8",format:"pem"}));updateApproval(path,spec,key);assert.throws(()=>updateApproval(path,spec,key),/revision conflict/);assert.equal(JSON.parse(readFileSync(path,"utf8")).events.length,1)}finally{rmSync(root,{recursive:true,force:true})}});

test("stale reclamation does not steal a concurrently replaced owner token",async()=>{const x=setup(),root=mkdtempSync(join(tmpdir(),"approval-lock-race-")),path=join(root,"approval.json"),spec=join(root,"decision.json"),key=join(root,"key.pem"),lock=path+".lock",marker=join(root,"observed");try{writeFileSync(path,JSON.stringify(x.request));writeFileSync(spec,JSON.stringify(decision(x.request,"review")));writeFileSync(key,x.kp.privateKey.export({type:"pkcs8",format:"pem"}));writeFileSync(lock,JSON.stringify({pid:99999999,token:"stale-owner"}));const old=new Date(Date.now()-60_000);utimesSync(lock,old,old);const modulePath=new URL("../dist/production_approval.js",import.meta.url).href,child=spawn(process.execPath,["--input-type=module","-e",'import {updateApproval} from '+JSON.stringify(modulePath)+';try{updateApproval(process.argv[1],process.argv[2],process.argv[3])}catch(e){console.error(e.message);process.exit(7)}',path,spec,key],{env:{...process.env,HOOK_CREATOR_TEST_STALE_LOCK_OBSERVED:marker,HOOK_CREATOR_TEST_PAUSE_AFTER_STALE_READ_MS:"250"},stdio:["ignore","pipe","pipe"]});for(let i=0;i<100&&!existsSync(marker);i++)await new Promise(r=>setTimeout(r,5));assert.ok(existsSync(marker),"reclaimer did not observe stale lock");rmSync(lock);writeFileSync(lock,JSON.stringify({pid:process.pid,token:"replacement-owner"}));const result=await new Promise<{code:number|null;stderr:string}>(resolve=>{let stderr="";child.stderr.on("data",x=>stderr+=x);child.on("close",code=>resolve({code,stderr}))});assert.equal(result.code,7);assert.match(result.stderr,/changed during stale reclamation/);assert.equal(JSON.parse(readFileSync(lock,"utf8")).token,"replacement-owner");assert.equal(JSON.parse(readFileSync(path,"utf8")).events.length,0)}finally{rmSync(root,{recursive:true,force:true})}});
