import { test } from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname,join } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import { hashEvidenceContent, hashEvidenceEdgeBinding, hashEvidenceNodeEnvelope, hashEvidenceSubject, verifyTransitiveEvidenceGraph } from "../dist/index.js";
const root=join(dirname(fileURLToPath(import.meta.url)),"..");
const load=(n:string)=>JSON.parse(readFileSync(join(root,"fixtures/evidence-graph",n),"utf8"));
const base=load("valid.json");
const anchors=base.nodes.map((n:any)=>n.envelopeHash);
const policy={now:"2026-09-18T08:00:00.000Z",trustedApprovalSubjectDigests:[hashEvidenceSubject("approval-subject")],issuers:[{id:"trusted-ci",schemaVersions:["1.0.0"],trustedFrom:"2026-01-01T00:00:00.000Z",trustedAnchorDigests:anchors},{id:"revoked-ci",schemaVersions:["1.0.0"],trustedFrom:"2026-01-01T00:00:00.000Z",revokedAt:"2026-08-01T00:00:00.000Z",trustedAnchorDigests:[]}]};

test("schema and fixture containing every node kind accept",()=>{const g=load("all-kinds.json");const schema=JSON.parse(readFileSync(join(root,"schema/evidence-graph/1.0.0/transitive-evidence-graph.schema.json"),"utf8"));assert.equal(new Ajv2020({strict:true,formats:{"date-time":true}}).compile(schema)(g),true);assert.deepEqual(verifyTransitiveEvidenceGraph(g,policy),{valid:true,diagnostics:[],nodeInvalid:[],affectedConclusions:[]});assert.deepEqual(new Set(g.nodes.map((n:any)=>n.kind)),new Set(["artifact","scenario","fixture","plan","output","grade","benchmark","test","archive","approval"]));});

test("canonical hashes are deterministic and envelope binds metadata plus content",()=>{assert.equal(hashEvidenceContent({b:[2,1],a:true}),hashEvidenceContent({a:true,b:[2,1]}));assert.throws(()=>hashEvidenceContent({n:NaN}));const n=structuredClone(base.nodes[0]);assert.equal(hashEvidenceNodeEnvelope(n),n.envelopeHash);for(const field of ["id","kind","schemaVersion","identity","issuedAt","content"]){const x=structuredClone(n);if(field==="identity")x.identity.subject+="-replacement";else if(field==="content")x.content={replacement:true};else x[field]+="x";assert.notEqual(hashEvidenceNodeEnvelope(x),n.envelopeHash,field);}});

test("all node-kind mutation scenario fixtures invalidate dependent conclusions",()=>{for(const kind of ["artifact","scenario","fixture","plan","output","grade","benchmark","test","archive","approval"]){const r=verifyTransitiveEvidenceGraph(load(`mutation-${kind}.json`),policy);assert.equal(r.valid,false,kind);assert.ok(r.nodeInvalid.some(x=>x.id===kind&&x.codes.includes("EVIDENCE_NODE_HASH_MISMATCH")),kind);assert.ok(r.affectedConclusions.length>0,kind);}});

test("recomputed hash and issuer substitutions fail authenticity",()=>{const g=structuredClone(base),n=g.nodes[0];n.identity.subject="substitute";n.envelopeHash=hashEvidenceNodeEnvelope(n);for(const e of g.edges){if(e.from===n.id)e.sourceEnvelopeHash=n.envelopeHash;if(e.to===n.id)e.targetEnvelopeHash=n.envelopeHash;e.dependencyHash=hashEvidenceEdgeBinding(e);}const r=verifyTransitiveEvidenceGraph(g,policy);assert.ok(r.nodeInvalid.find(x=>x.id===n.id)?.codes.includes("EVIDENCE_AUTHENTICITY_INVALID"));});

test("Ed25519 issuer authenticity verifies and signature substitution fails",()=>{const {privateKey,publicKey}=generateKeyPairSync("ed25519");const g=structuredClone(base);for(const n of g.nodes)n.authenticity={method:"ed25519",keyId:"release-key",signature:sign(null,Buffer.from(n.envelopeHash),privateKey).toString("base64url")};const p={...policy,issuers:[{id:"trusted-ci",schemaVersions:["1.0.0"],trustedFrom:"2026-01-01T00:00:00.000Z",keys:[{id:"release-key",algorithm:"ed25519" as const,publicKey:publicKey.export({type:"spki",format:"pem"}).toString()}]}]};assert.equal(verifyTransitiveEvidenceGraph(g,p).valid,true);g.nodes[0].authenticity.signature=g.nodes[1].authenticity.signature;assert.ok(verifyTransitiveEvidenceGraph(g,p).diagnostics.some(d=>d.code==="EVIDENCE_AUTHENTICITY_INVALID"));});

test("attack fixtures reject and edge binds full endpoints and relation",()=>{for(const [name,code] of [["replay.json","EVIDENCE_APPROVAL_STALE"],["substitution.json","EVIDENCE_DEPENDENCY_HASH_MISMATCH"],["downgrade.json","EVIDENCE_NODE_SCHEMA_UNSUPPORTED"],["stale-approval.json","EVIDENCE_NODE_EXPIRED"]] as const){const r=verifyTransitiveEvidenceGraph(load(name),policy);assert.equal(r.valid,false,name);assert.ok(r.diagnostics.some(d=>d.code===code),name);}});

test("future issuance and untrusted approval subject are invalid nodes",()=>{const g=structuredClone(base),n=g.nodes.find((x:any)=>x.kind==="approval");n.issuedAt="2027-01-01T00:00:00.000Z";const r=verifyTransitiveEvidenceGraph(g,policy);assert.ok(r.nodeInvalid.find(x=>x.id==="approval")?.codes.includes("EVIDENCE_NODE_FUTURE_ISSUED"));const p={...policy,trustedApprovalSubjectDigests:[]};assert.ok(verifyTransitiveEvidenceGraph(base,p).nodeInvalid.find(x=>x.id==="approval")?.codes.includes("EVIDENCE_APPROVAL_ANCHOR_INVALID"));});

test("first edge is deterministic and affected conclusions union all invalid roots",()=>{const g=structuredClone(base);g.nodes.find((n:any)=>n.kind==="scenario").content={bad:1};g.nodes.find((n:any)=>n.kind==="fixture").content={bad:2};const a=verifyTransitiveEvidenceGraph(g,policy);g.nodes.reverse();g.edges.reverse();const b=verifyTransitiveEvidenceGraph(g,policy);assert.deepEqual(a.firstInvalidEdge,b.firstInvalidEdge);assert.deepEqual(a.affectedConclusions,b.affectedConclusions);for(const id of ["output","grade","benchmark","test","approval"])assert.ok(a.affectedConclusions.includes(id),id);});

test("missing blocks cycles and duplicates reject",()=>{for(const name of ["missing.json","cycle.json","duplicate.json"])assert.equal(verifyTransitiveEvidenceGraph(load(name),policy).valid,false,name);});

test("issuer and subject form a graph-wide unique identity",()=>{const g=structuredClone(base),duplicate=structuredClone(g.nodes[0]);duplicate.id="artifact-copy";duplicate.envelopeHash=hashEvidenceNodeEnvelope(duplicate);duplicate.authenticity.anchorDigest=duplicate.envelopeHash;g.nodes.push(duplicate);const p={...policy,issuers:policy.issuers.map(i=>i.id==="trusted-ci"?{...i,trustedAnchorDigests:[...(i.trustedAnchorDigests??[]),duplicate.envelopeHash]}:i)};const r=verifyTransitiveEvidenceGraph(g,p);assert.equal(r.valid,false);assert.deepEqual(r.nodeInvalid.find(x=>x.id==="artifact-copy")?.codes,["EVIDENCE_GRAPH_MISSING_BLOCK","EVIDENCE_IDENTITY_MISMATCH"]);assert.equal(r.diagnostics.filter(d=>d.code==="EVIDENCE_IDENTITY_MISMATCH").length,1);});

test("a valid terminal approval is mandatory and every branch must reach one",()=>{const noApproval=structuredClone(base);noApproval.nodes=noApproval.nodes.filter((n:any)=>n.kind!=="approval");noApproval.edges=noApproval.edges.filter((e:any)=>e.to!=="approval");let r=verifyTransitiveEvidenceGraph(noApproval,policy);assert.equal(r.valid,false);assert.ok(r.diagnostics.some(d=>d.code==="EVIDENCE_GRAPH_MISSING_BLOCK"&&d.message==="Graph has no valid terminal approval conclusion."));const invalidApproval=structuredClone(base);invalidApproval.nodes.find((n:any)=>n.kind==="approval").content={tampered:true};r=verifyTransitiveEvidenceGraph(invalidApproval,policy);assert.ok(r.diagnostics.some(d=>d.message==="Graph has no valid terminal approval conclusion."));
  const orphan=structuredClone(base),node=structuredClone(orphan.nodes[0]);node.id="orphan-artifact";node.identity.subject="orphan-subject";node.envelopeHash=hashEvidenceNodeEnvelope(node);node.authenticity.anchorDigest=node.envelopeHash;orphan.nodes.push(node);const p={...policy,issuers:policy.issuers.map(i=>i.id==="trusted-ci"?{...i,trustedAnchorDigests:[...(i.trustedAnchorDigests??[]),node.envelopeHash]}:i)};r=verifyTransitiveEvidenceGraph(orphan,p);assert.equal(r.valid,false);assert.deepEqual(r.nodeInvalid.find(x=>x.id===node.id)?.codes,["EVIDENCE_GRAPH_MISSING_BLOCK"]);assert.ok(r.diagnostics.some(d=>d.path===`/nodes/${orphan.nodes.length-1}`&&d.message.includes("no directed path")));});

test("snapshot strict rejects every symbol own key, function and non-JSON descriptor",()=>{for(const enumerable of [true,false]){const value:any={ok:true};Object.defineProperty(value,Symbol("hidden"),{value:"x",enumerable});assert.throws(()=>hashEvidenceContent(value),/symbol key/);}for(const value of [{fn(){return 1;}},[()=>1]])assert.throws(()=>hashEvidenceContent(value),/non-JSON value/);for(const descriptor of [{value:1,enumerable:false,writable:true,configurable:true},{value:1,enumerable:true,writable:false,configurable:true},{value:1,enumerable:true,writable:true,configurable:false}]){const value:any={};Object.defineProperty(value,"x",descriptor);assert.throws(()=>hashEvidenceContent(value),/non-JSON object descriptor/);}const array:any=[1];Object.defineProperty(array,"0",{value:1,enumerable:true,writable:false,configurable:true});assert.throws(()=>hashEvidenceContent(array),/non-JSON array descriptor/);
  const graph=structuredClone(base);Object.defineProperty(graph.nodes[0],Symbol("non-enumerable"),{value:true,enumerable:false});assert.equal(verifyTransitiveEvidenceGraph(graph,policy).diagnostics[0].code,"EVIDENCE_GRAPH_INVALID");});

test("hostile proxy and getter fail closed without invoking getter",()=>{let invoked=false;const getter=structuredClone(base);Object.defineProperty(getter.nodes[0],"content",{enumerable:true,get(){invoked=true;throw new Error("owned");}});assert.equal(verifyTransitiveEvidenceGraph(getter,policy).valid,false);assert.equal(invoked,false);const proxy=new Proxy(base,{ownKeys(){throw new Error("owned");}});assert.equal(verifyTransitiveEvidenceGraph(proxy,policy).diagnostics[0].code,"EVIDENCE_GRAPH_INVALID");});
