import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname,join } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import { OUTCOME_METRIC_DICTIONARY, OUTCOME_METRIC_IDS, OUTCOME_METRICS_SCHEMA_ID, OUTCOME_METRICS_VERSION, OutcomeMetricsValidationError, computeOutcomeMetrics, createGoldenJourneyMetricContract, validateOutcomeMetricsInput } from "../dist/index.js";
const root=join(dirname(fileURLToPath(import.meta.url)),"..");
const load=(n:string)=>JSON.parse(readFileSync(join(root,"fixtures/outcome-metrics",n),"utf8"));
const valid=()=>structuredClone(load("valid.json"));

test("versioned schema, dictionary, golden contract, and package exports are complete",()=>{const schema=loadSchema();assert.equal(schema.$id,OUTCOME_METRICS_SCHEMA_ID);assert.equal(OUTCOME_METRICS_VERSION,"1.0.0");assert.deepEqual(Object.keys(OUTCOME_METRIC_DICTIONARY),OUTCOME_METRIC_IDS);for(const id of OUTCOME_METRIC_IDS){const d=OUTCOME_METRIC_DICTIONARY[id];assert.ok(d.formula&&d.population&&d.exclusions.length&&d.provenance&&d.target.unit);}assert.deepEqual(createGoldenJourneyMetricContract().requiredMetricIds,OUTCOME_METRIC_IDS);const pkg=JSON.parse(readFileSync(join(root,"package.json"),"utf8"));assert.ok(pkg.exports["./outcome-metrics"]&&pkg.exports["./outcome-metrics-types"]&&pkg.exports["./outcome-metrics-schema/1.0.0"]);});
function loadSchema(){return JSON.parse(readFileSync(join(root,"schema/outcome-metrics/1.0.0/outcome-productivity-metrics.schema.json"),"utf8"));}
test("schema and API accept conformance fixture and compute every requested metric",()=>{const x=valid(),check=new Ajv2020({strict:true,formats:{"date-time":true}}).compile(loadSchema());assert.equal(check(x),true,JSON.stringify(check.errors));assert.equal(validateOutcomeMetricsInput(x).valid,true);const r=computeOutcomeMetrics(x);assert.equal(r.metrics.length,10);const get=(id:string)=>r.metrics.find(m=>m.id===id)!;assert.equal(get("task-success-rate").value,1);assert.equal(get("time-savings-seconds").value,300);assert.equal(get("intervention-savings").value,1);assert.equal(get("creation-completion-rate").value,1);assert.equal(get("improvement-yield").value,1);assert.equal(get("regression-rate").value,0);assert.equal(get("recovery-rate").value,1);assert.equal(get("review-time-seconds").value,300);assert.equal(get("confidence-score").value,0.9);assert.equal(r.northStar.value,1);assert.equal(r.guardrails.releaseEligible,true);assert.match(r.computationHash,/^sha256:[a-f0-9]{64}$/);});
test("default processing is local, opt-out is distinct from included missing data",()=>{assert.equal(computeOutcomeMetrics(valid()).privacyStatus,"local-only");const o=computeOutcomeMetrics(load("opted-out.json"));assert.ok(o.metrics.every(x=>x.status==="opted-out"));const m=valid();m.events=[];m.evidence=[];m.evaluations=[];const missing=computeOutcomeMetrics(m);assert.ok(missing.metrics.every(x=>x.status==="missing"));const leaked=load("opted-out.json");leaked.events=[valid().events[0]];assert.ok(validateOutcomeMetricsInput(leaked).diagnostics.some(x=>x.code==="METRICS_PRIVACY_VIOLATION"));});
test("safety, evidence, human approval, and all budgets block north-star gaming",()=>{for(const mutate of [(x:any)=>x.evaluations.find((e:any)=>e.kind==="safety").passed=false,(x:any)=>x.evaluations.find((e:any)=>e.kind==="evidence-credibility").score=.7,(x:any)=>x.evaluations.find((e:any)=>e.kind==="human-approval").passed=false,(x:any)=>x.budget.maxCostUsd=3,(x:any)=>x.budget.maxDurationSeconds=100]){const x=valid();mutate(x);const r=computeOutcomeMetrics(x);assert.equal(r.northStar.value,0);assert.equal(r.northStar.status,"guardrail-blocked");assert.equal(r.guardrails.releaseEligible,false);assert.deepEqual(r.northStar.denominator,1);}});
test("automated approval and reward duplication reject",()=>{let x=valid();x.evaluations.find((e:any)=>e.kind==="human-approval").evaluator.type="automated";assert.ok(validateOutcomeMetricsInput(x).diagnostics.some(d=>d.code==="METRICS_GUARDRAIL_INVALID"));x=valid();x.events.push({...x.events.find((e:any)=>e.type==="release-candidate-created"),id:"extra-release"});assert.ok(validateOutcomeMetricsInput(x).diagnostics.some(d=>d.code==="METRICS_DUPLICATE"));x=valid();x.evaluations.push({...x.evaluations[0],id:"extra-grade"});assert.ok(validateOutcomeMetricsInput(x).diagnostics.some(d=>d.code==="METRICS_DUPLICATE"));});
test("golden metric list, unknown fields, unsupported version, and provenance fail closed",()=>{for(const mutate of [(x:any)=>x.metricContract.requiredMetricIds.pop(),(x:any)=>x.extra=true,(x:any)=>x.schemaVersion="2.0.0",(x:any)=>x.events[0].provenance.digest="sha256:no"]){const x=valid();mutate(x);const r=validateOutcomeMetricsInput(x);assert.equal(r.valid,false);assert.throws(()=>computeOutcomeMetrics(x),OutcomeMetricsValidationError);}});
test("computation is byte deterministic under input order and dictionary is immutable",()=>{const a=computeOutcomeMetrics(valid()),x=valid();x.events.reverse();x.evaluations.reverse();assert.deepEqual(computeOutcomeMetrics(x),a);assert.throws(()=>{(OUTCOME_METRIC_DICTIONARY["task-success-rate"] as any).formula="gaming";});});
test("hostile getters, proxies, cycles, symbols, sparse arrays, and non-finite values reject without execution",()=>{let invoked=false;const getter=valid();Object.defineProperty(getter,"events",{enumerable:true,get(){invoked=true;throw new Error("owned");}});assert.equal(validateOutcomeMetricsInput(getter).valid,false);assert.equal(invoked,false);assert.equal(validateOutcomeMetricsInput(new Proxy(valid(),{ownKeys(){throw new Error("owned");}})).valid,false);const cycle=valid();cycle.self=cycle;assert.equal(validateOutcomeMetricsInput(cycle).valid,false);const symbol=valid();symbol[Symbol("x")]=1;assert.equal(validateOutcomeMetricsInput(symbol).valid,false);const sparse=valid();sparse.events.length++;assert.equal(validateOutcomeMetricsInput(sparse).valid,false);const nan=valid();nan.budget.maxCostUsd=NaN;assert.equal(validateOutcomeMetricsInput(nan).valid,false);});

test("north star requires matched effectiveness improvement, all evaluations, confidence, telemetry, and budget",()=>{const mutations=[
 (x:any)=>x.evaluations.find((e:any)=>e.kind==="effectiveness"&&e.runId==="candidate").score=.5,
 (x:any)=>x.evaluations.find((e:any)=>e.kind==="improvement").passed=false,
 (x:any)=>x.evaluations.find((e:any)=>e.kind==="regression").passed=false,
 (x:any)=>x.evaluations.find((e:any)=>e.kind==="confidence").score=.7,
 (x:any)=>x.events.splice(x.events.findIndex((e:any)=>e.type==="cost-recorded"),1),
 (x:any)=>x.events.splice(x.events.findIndex((e:any)=>e.type==="intervention-count-recorded"&&e.variant==="candidate"),1)
];for(const mutate of mutations){const x=valid();mutate(x);const r=computeOutcomeMetrics(x);assert.equal(r.guardrails.releaseEligible,false);assert.equal(r.northStar.status,"guardrail-blocked");assert.equal(r.northStar.value,0);}});
test("evidence registry resolves every reference to exact run and type",()=>{for(const mutate of [(x:any)=>x.evaluations[0].evidenceIds=["absent"],(x:any)=>x.evidence.find((e:any)=>e.id===x.evaluations[0].evidenceIds[0]).runId="base",(x:any)=>x.evidence.find((e:any)=>e.id===x.evaluations[0].evidenceIds[0]).type="safety"]){const x=valid();mutate(x);const r=validateOutcomeMetricsInput(x);assert.equal(r.valid,false);assert.ok(r.diagnostics.some(d=>d.code==="METRICS_EVIDENCE_INVALID"));}});
test("pairs reject absent side and multiple baseline or candidate runs",()=>{for(const mutate of [(x:any)=>x.events=x.events.filter((e:any)=>e.variant!=="baseline"),(x:any)=>x.events.push({...x.events[0],id:"ambiguous",runId:"base-two"})]){const x=valid();mutate(x);assert.ok(validateOutcomeMetricsInput(x).diagnostics.some(d=>d.code==="METRICS_PAIR_INVALID"));}});
test("recovery provenance requires lifecycle boundaries",()=>{const x=valid();x.events=x.events.filter((e:any)=>e.type!=="recovery-completed");assert.ok(validateOutcomeMetricsInput(x).diagnostics.some(d=>d.code==="METRICS_EVALUATION_INVALID"));});
test("transparent proxies fail closed via structured clone",()=>{let traps=0;const proxy=new Proxy(valid(),{getOwnPropertyDescriptor(t,p){traps++;return Reflect.getOwnPropertyDescriptor(t,p)},ownKeys(t){traps++;return Reflect.ownKeys(t)},getPrototypeOf(t){traps++;return Reflect.getPrototypeOf(t)}});assert.equal(validateOutcomeMetricsInput(proxy).valid,false);assert.ok(traps>0);assert.throws(()=>structuredClone(proxy));});
