import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {dirname,join} from "node:path";
import {fileURLToPath} from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import {USAGE_COST_EVIDENCE_SCHEMA_ID,USAGE_COST_EVIDENCE_VERSION,UsageCostValidationError,computePairedUsageCostDelta,computeUsageCostEvidence,validateUsageCostInput} from "../dist/index.js";
const root=join(dirname(fileURLToPath(import.meta.url)),".."),load=()=>JSON.parse(readFileSync(join(root,"fixtures/usage-cost/valid.json"),"utf8"));
test("versioned schema, fixture, API and exports",()=>{const schema=JSON.parse(readFileSync(join(root,"schema/usage-cost/1.0.0/goose-usage-cost-evidence.schema.json"),"utf8"));assert.equal(schema.$id,USAGE_COST_EVIDENCE_SCHEMA_ID);assert.equal(USAGE_COST_EVIDENCE_VERSION,"1.0.0");const ajv=new Ajv2020({strict:true,formats:{"date-time":true}}),check=ajv.compile(schema),x=load();assert.equal(check(x),true,JSON.stringify(check.errors));assert.equal(validateUsageCostInput(x).valid,true);const pkg=JSON.parse(readFileSync(join(root,"package.json"),"utf8"));assert.ok(pkg.exports["./usage-cost"]&&pkg.exports["./usage-cost-types"]&&pkg.exports["./usage-cost-schema/1.0.0"]);});
test("computes only complete compatible cost and separated totals",()=>{const r=computeUsageCostEvidence(load());assert.equal(r.executor.monetaryCost.value,3.9);assert.equal(r.grader.monetaryCost.value,.85);assert.equal(r.combined.monetaryCost.value,4.75);assert.equal(r.combined.tokens.total.value,1610000);assert.equal(r.combined.actualTurns.value,5);assert.ok(Math.abs(r.qualityPerDollar.value!-0.9/4.75)<1e-12);assert.match(r.evidenceHash,/^sha256:[a-f0-9]{64}$/);});
test("missing categories and incompatible pricing remain null with reasons",()=>{let x=load();x.executor.tokens.cached={value:null,unavailableReason:"provider-omitted"};x.executor.tokens.total={value:null,unavailableReason:"provider-omitted"};let r=computeUsageCostEvidence(x);assert.deepEqual(r.executor.monetaryCost,{value:null,unavailableReason:"pricing-incomplete"});assert.equal(r.combined.monetaryCost.value,null);assert.equal(r.qualityPerDollar.value,null);x=load();x.pricing.model="other";r=computeUsageCostEvidence(x);assert.equal(r.executor.monetaryCost.unavailableReason,"pricing-incompatible");});
test("strict categories, sums, turns, latency and pricing reject",()=>{for(const mutate of [(x:any)=>x.executor.tokens.total.value++,(x:any)=>x.executor.actualTurns.value=1.5,(x:any)=>x.executor.latencyMs.model.value=13000,(x:any)=>x.pricing.rates[1].category="input",(x:any)=>x.executor.tokens.input.value=-1,(x:any)=>x.quality.value=NaN]){const x=load();mutate(x);assert.equal(validateUsageCostInput(x).valid,false);assert.throws(()=>computeUsageCostEvidence(x),UsageCostValidationError);}});
test("null always has a reason and available always has null reason",()=>{for(const mutate of [(x:any)=>x.executor.tokens.input={value:null,unavailableReason:null},(x:any)=>x.executor.tokens.input={value:1,unavailableReason:"not-exposed"}]){const x=load();mutate(x);assert.equal(validateUsageCostInput(x).valid,false);}});
test("canonical evidence and paired delta are deterministic",()=>{const a=computeUsageCostEvidence(load()),x=load();x.pricing.rates.reverse();const b=computeUsageCostEvidence(x);assert.deepEqual(b,a);const d1=computePairedUsageCostDelta(a,b),d2=computePairedUsageCostDelta(a,b);assert.deepEqual(d1,d2);assert.equal(d1.combined.monetaryCost.value,0);assert.match(d1.deltaHash,/^sha256:[a-f0-9]{64}$/);});
test("hostile/proxy and privacy payloads fail closed without secret echo",()=>{let invoked=false;const x=load();Object.defineProperty(x,"executor",{enumerable:true,get(){invoked=true;throw Error("secret-value");}});let r=validateUsageCostInput(x);assert.equal(r.valid,false);assert.equal(invoked,false);assert.ok(!JSON.stringify(r).includes("secret-value"));r=validateUsageCostInput(new Proxy(load(),{ownKeys(){throw Error("credential-value")}}));assert.equal(r.valid,false);const secret=load();secret.apiToken="credential-value-never-echo";r=validateUsageCostInput(secret);assert.equal(r.valid,false);assert.ok(r.diagnostics.some(d=>d.code==="USAGE_PRIVACY_VIOLATION"));assert.ok(!JSON.stringify(r).includes("credential-value-never-echo"));const cycle=load();cycle.self=cycle;assert.equal(validateUsageCostInput(cycle).valid,false);});


test("schema/runtime parity rejects adversarial scalar values",()=>{const schema=JSON.parse(readFileSync(join(root,"schema/usage-cost/1.0.0/goose-usage-cost-evidence.schema.json"),"utf8"));const check=new Ajv2020({strict:true,allErrors:true,formats:{"date-time":true}}).compile(schema);for(const mutate of [(x:any)=>x.executor.tokens.input.value=1.5,(x:any)=>x.executor.actualTurns.value=1.5,(x:any)=>x.executor.identity.providerRequested=" acme",(x:any)=>x.executor.runtime.adapterName="acme ",(x:any)=>x.observedAt="2026-09-18T20:00:00+02:00",(x:any)=>x.observedAt="2026-02-29T20:00:00Z",(x:any)=>x.observedAt="0000-01-01T00:00:00Z",(x:any)=>{x.quality.value=null;x.quality.unavailableReason="provider-omitted"},(x:any)=>{x.executor.latencyMs.wall.value=null;x.executor.latencyMs.wall.unavailableReason="pricing-unavailable"}]){const x=load();mutate(x);assert.equal(check(x),false);assert.equal(validateUsageCostInput(x).valid,false);}});

test("paired delta rejects forged, derived-field-modified, non-finite, and non-normalized evidence",()=>{const good=computeUsageCostEvidence(load());for(const mutate of [(x:any)=>x.evidenceHash="sha256:"+"0".repeat(64),(x:any)=>x.combined.actualTurns.value=999,(x:any)=>x.executor.latencyMs.wall.value=NaN,(x:any)=>x.pricing.rates.reverse()]){const x=structuredClone(good);mutate(x);assert.throws(()=>computePairedUsageCostDelta(x,good),UsageCostValidationError);}});

test("safe-integer boundary is accepted exactly and over-safe token or turn values fail schema and runtime",()=>{const schema=JSON.parse(readFileSync(join(root,"schema/usage-cost/1.0.0/goose-usage-cost-evidence.schema.json"),"utf8")),check=new Ajv2020({strict:true,allErrors:true,formats:{"date-time":true}}).compile(schema),max=Number.MAX_SAFE_INTEGER,x=load();x.executor.tokens.input.value=max;x.executor.tokens.output.value=0;x.executor.tokens.cached.value=0;x.executor.tokens.reasoning.value=0;x.executor.tokens.total.value=max;x.executor.actualTurns.value=max;x.pricing=null;for(const category of ["input","output","cached","reasoning","total"])x.grader.tokens[category].value=0;x.grader.actualTurns.value=0;assert.equal(check(x),true,JSON.stringify(check.errors));assert.equal(validateUsageCostInput(x).valid,true);const evidence=computeUsageCostEvidence(x);assert.equal(evidence.executor.tokens.input.value,max);assert.equal(evidence.executor.actualTurns.value,max);for(const mutate of [(v:any)=>{v.executor.tokens.input.value=max+1;v.executor.tokens.total.value=max+1},(v:any)=>v.executor.actualTurns.value=max+1]){const invalid=load();mutate(invalid);assert.equal(check(invalid),false);assert.equal(validateUsageCostInput(invalid).valid,false);assert.throws(()=>computeUsageCostEvidence(invalid),UsageCostValidationError);}});

test("rejects unsafe pricing rates and cost arithmetic before hashing",()=>{const schema=JSON.parse(readFileSync(join(root,"schema/usage-cost/1.0.0/goose-usage-cost-evidence.schema.json"),"utf8")),check=new Ajv2020({strict:true,allErrors:true,formats:{"date-time":true}}).compile(schema),over=load();over.pricing.rates[0].perMillionTokens=Number.MAX_SAFE_INTEGER+1;assert.equal(check(over),false);assert.equal(validateUsageCostInput(over).valid,false);assert.throws(()=>computeUsageCostEvidence(over),UsageCostValidationError);const overflow=load();overflow.executor.tokens.input.value=Number.MAX_SAFE_INTEGER;overflow.executor.tokens.output.value=0;overflow.executor.tokens.cached.value=0;overflow.executor.tokens.reasoning.value=0;overflow.executor.tokens.total.value=Number.MAX_SAFE_INTEGER;overflow.pricing.rates.find((r:any)=>r.category==="input").perMillionTokens=Number.MAX_SAFE_INTEGER;assert.equal(check(overflow),true,JSON.stringify(check.errors));assert.equal(validateUsageCostInput(overflow).valid,true);assert.throws(()=>computeUsageCostEvidence(overflow),UsageCostValidationError);});

test("paired unavailable deltas preserve valid metric-category reasons",()=>{const a=load(),b=load();a.executor.tokens.cached={value:null,unavailableReason:"provider-omitted"};a.executor.tokens.total={value:null,unavailableReason:"provider-omitted"};b.executor.tokens.cached={value:null,unavailableReason:"adapter-omitted"};b.executor.tokens.total={value:null,unavailableReason:"adapter-omitted"};a.quality={value:null,unavailableReason:"not-exposed"};b.quality={value:null,unavailableReason:"not-applicable"};const d=computePairedUsageCostDelta(computeUsageCostEvidence(a),computeUsageCostEvidence(b));assert.deepEqual(d.executor.tokens.cached,{value:null,unavailableReason:"provider-omitted"});assert.deepEqual(d.executor.monetaryCost,{value:null,unavailableReason:"pricing-incomplete"});assert.deepEqual(d.quality,{value:null,unavailableReason:"not-exposed"});assert.deepEqual(d.qualityPerDollar,{value:null,unavailableReason:"pricing-incomplete"});});
