import {test} from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync,spawnSync} from "node:child_process";
import {fileURLToPath} from "node:url";
import {normalizeResourceTelemetry,timingArtifact} from "../dist/scripts/resource_telemetry.js";
const aggregate=fileURLToPath(new URL("../dist/scripts/aggregate_benchmark.js",import.meta.url));
function fixture(timings:any[]){const root=mkdtempSync(join(tmpdir(),"agent-resource-"));for(const config of ["with_agent","baseline"]){const ep=join(root,"eval-one");mkdirSync(ep,{recursive:true});writeFileSync(join(ep,"eval_metadata.json"),JSON.stringify({eval_id:"one"}));timings.forEach((timing,i)=>{const rp=join(ep,config,`run-${i+1}`);mkdirSync(rp,{recursive:true});writeFileSync(join(rp,"grading.json"),JSON.stringify({summary:{pass_rate:1,passed:1,failed:0,total:1},execution_metrics:{output_chars:9999}}));if(timing!==undefined)writeFileSync(join(rp,"timing.json"),typeof timing==="string"?timing:JSON.stringify(timing));});}return root;}
test("missing and malformed telemetry normalize to null with stable reasons",()=>{const missing=normalizeResourceTelemetry({});for(const k of ["duration_seconds","tokens","turns"] as const){assert.equal(missing[k].value,null);assert.equal(missing[k].availability_reason,"not-exposed");assert.equal(missing[k].source,"unavailable");}assert.equal(missing.cost_usd.availability_reason,"pricing-unavailable");for(const value of [-1,NaN,Infinity,"3"]){const x=normalizeResourceTelemetry({total_tokens:value,total_turns:value,total_duration_seconds:value,cost_usd:value});for(const k of ["duration_seconds","tokens","turns","cost_usd"] as const){assert.equal(x[k].value,null);assert.equal(x[k].availability_reason,"malformed");}}});
test("real zero values remain available and provenance identity is retained",()=>{const a=timingArtifact({duration_seconds:0,tokens:0,turns:0,cost_usd:0,provider:"acme",model:"m1",goose_version:"1.2.3"}),x=normalizeResourceTelemetry(a);for(const k of ["duration_seconds","tokens","turns","cost_usd"] as const){assert.equal(x[k].value,0);assert.equal(x[k].availability_reason,null);}assert.deepEqual(x.identity,{provider:"acme",model:"m1",goose_version:"1.2.3"});assert.equal(x.tokens.source,"goose-output-metadata");});
test("legacy and partial artifacts migrate safely without output character token fallback",()=>{const root=fixture([{total_duration_seconds:2,total_tokens:7},{total_duration_seconds:3},undefined]);try{execFileSync(process.execPath,[aggregate,root,"--minimum-coverage","0.8"]);const b=JSON.parse(readFileSync(join(root,"benchmark.json"),"utf8")),r=b.runs.filter((x:any)=>x.configuration==="with_agent");assert.deepEqual(r.map((x:any)=>x.result.tokens),[7,null,null]);assert.equal(r[1].telemetry.tokens.availability_reason,"not-exposed");assert.equal(b.run_summary.with_agent.tokens.sample_count,1);assert.deepEqual(b.run_summary.with_agent.telemetry_coverage.tokens,{available:1,total:3,rate:1/3,reasons:{"not-exposed":2}});assert.equal(b.run_summary.delta.tokens,null);assert.equal(b.run_summary.efficiency_conclusions.status,"blocked");assert.ok(b.metadata.sample_count===6);}finally{rmSync(root,{recursive:true,force:true})}});
test("coverage threshold is configurable and malformed timing is unavailable",()=>{const root=fixture([{total_duration_seconds:1,total_tokens:4,total_turns:1,cost_usd:0},"{"]);try{execFileSync(process.execPath,[aggregate,root,"--minimum-coverage","0.5"]);const b=JSON.parse(readFileSync(join(root,"benchmark.json"),"utf8"));assert.equal(b.run_summary.with_agent.time_seconds.sample_count,1);assert.equal(b.run_summary.with_agent.time_seconds.p50,1);assert.equal(b.run_summary.with_agent.time_seconds.p95,1);assert.equal(b.run_summary.with_agent.telemetry_coverage.time_seconds.reasons.malformed,1);assert.equal(b.run_summary.efficiency_conclusions.status,"eligible");const bad=spawnSync(process.execPath,[aggregate,root,"--minimum-coverage","NaN"]);assert.equal(bad.status,2);}finally{rmSync(root,{recursive:true,force:true})}});
