import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { RUN_PROFILE_COUNTS, schedulePairs, validateAggregateBudget } from "../dist/scripts/repeated_runs.js";
import { expectedRunDirs, pairedOrderFromSeed, validateExecutionEvidence } from "../dist/scripts/evaluation_provenance.js";

const cli=resolve("dist/scripts/cli.js");
function fixture(aggregate_budget:any={max_runs:6,max_turns:72,timeout_seconds:3600}){const root=mkdtempSync(join(tmpdir(),"repeated-pairs-")),skill=join(root,"demo"),workspace=join(root,"workspace");mkdirSync(join(skill,"evals"),{recursive:true});writeFileSync(join(skill,"SKILL.md"),"---\nname: demo\ndescription: Evaluates demo workflows. Use when testing repeated behavior.\n---\n# Demo\n");writeFileSync(join(skill,"evals","evals.json"),JSON.stringify({skill_name:"demo",aggregate_budget,evals:[{id:1,name:"repeat-demo",subject:"behavior",language:"en",target:{kind:"existing-skill",execution:"execute",path:"."},preconditions:["isolated"],budget:{max_turns:12,timeout_seconds:600},prompt:"Evaluate the demo workflow using the installed Skill.",expected_output:"A graded output.",files:[],capabilities:{filesystem:true,agent_runner:true,browser:false,network:false,tools:[]},assertions:["The output completes the requested demo workflow"],coverage_tags:["language:en"],navigation_expectations:{must_read:["SKILL.md"],read_when_relevant:[],must_not_read:[]}}]}));return{root,skill,workspace};}
function invoke(f:any,args:string[]){const fake=resolve("tests/fixtures/fake-goose.mjs"),env={...process.env,SKILL_CREATOR_GOOSE_COMMAND:process.execPath+" "+fake};return spawnSync(process.execPath,[cli,"full-eval",f.skill,"--workspace",f.workspace,...args,"--format","json"],{encoding:"utf8",env});}

test("profiles and deterministic schedules derive order from the recorded seed",()=>{assert.deepEqual(RUN_PROFILE_COUNTS,{fast:1,standard:3,release:5});const binding={skill_source_sha256:"a".repeat(64),eval_plan_sha256:"b".repeat(64),scenario_sha256:"c".repeat(64)},first=schedulePairs(binding,5),second=schedulePairs(binding,5);assert.deepEqual(first,second);assert.equal(new Set(first.map(x=>x.seed)).size,5);for(const pair of first)assert.deepEqual(pair.order,pairedOrderFromSeed(pair.seed));assert.deepEqual(pairedOrderFromSeed(100),pairedOrderFromSeed(100));assert.notDeepEqual(pairedOrderFromSeed(100),pairedOrderFromSeed(101));});

test("seed-derived ordering remains counterbalanced across repeated pairs",()=>{for(const count of [1,2,3,4,5]){const schedule=schedulePairs({skill_source_sha256:"d".repeat(64),eval_plan_sha256:"e".repeat(64),scenario_sha256:"f".repeat(64)},count),withFirst=schedule.filter(pair=>pair.order[0]==="with_skill").length,baselineFirst=count-withFirst;assert.ok(Math.abs(withFirst-baselineFirst)<=1);for(let index=1;index<schedule.length;index++)assert.notEqual(schedule[index].order[0],schedule[index-1].order[0]);}});

test("aggregate budget is validated before repeated scaffolding",()=>{assert.throws(()=>validateAggregateBudget({aggregate_budget:{max_runs:5,max_turns:72,timeout_seconds:3600}},"standard",[{budget:{max_turns:12,timeout_seconds:600}}]),/max_runs.*required 6/);const f=fixture({max_runs:5,max_turns:72,timeout_seconds:3600});try{const run=invoke(f,["--run-profile","standard"]),result=JSON.parse(run.stdout);assert.equal(result.status,"failure");assert.equal(result.incomplete.code,"invalid-aggregate-budget");assert.equal(readdirSync(f.workspace).filter(x=>x.startsWith("eval-")).length,0);}finally{rmSync(f.root,{recursive:true,force:true});}});

test("standard executes three complete counterbalanced pairs and preserves provenance",()=>{const f=fixture();try{const run=invoke(f,["--run-profile","standard","--execute","--human-review","pass","--tests-status","pass"]);assert.equal(run.status,0,run.stderr);const metadata=JSON.parse(readFileSync(join(f.workspace,"eval-1","eval_metadata.json"),"utf8"));assert.equal(metadata.requested_pairs,3);assert.equal(metadata.execution_schedule.length,3);for(const config of ["with_skill","without_skill"]){const names=readdirSync(join(f.workspace,"eval-1",config)).filter(x=>x.startsWith("run-")).sort();assert.deepEqual(names,["run-1","run-2","run-3"]);for(const name of names){const evidence=JSON.parse(readFileSync(join(f.workspace,"eval-1",config,name,"execution-evidence.json"),"utf8")),pair=metadata.execution_schedule[Number(name.slice(4))-1];assert.equal(evidence.seed,pair.seed);assert.deepEqual(evidence.order,pair.order);assert.equal(evidence.pair_equivalence.max_turns,12);assert.equal(evidence.pair_equivalence.timeout_seconds,600);assert.deepEqual(evidence.pair_equivalence.tools,[]);assert.match(evidence.pair_equivalence.fixture_sha256,/^[a-f0-9]{64}$/);}}const benchmark=JSON.parse(readFileSync(join(f.workspace,"benchmark.json"),"utf8"));assert.equal(benchmark.run_summary.with_skill.pass_rate.count,3);assert.equal(benchmark.run_summary.with_skill.pass_rate.stddev,0);assert.deepEqual(benchmark.run_summary.with_skill.pass_rate.confidence_interval_95,{lower:1,upper:1});assert.equal(benchmark.run_summary.delta.paired.pass_rate.count,3);}finally{rmSync(f.root,{recursive:true,force:true});}});

test("fast aggregate suppresses inferential statistics and stable claims",()=>{const f=fixture({max_runs:2,max_turns:24,timeout_seconds:1200});try{const run=invoke(f,["--run-profile","fast","--execute"]);assert.equal(run.status,3,run.stderr);const benchmark=JSON.parse(readFileSync(join(f.workspace,"benchmark.json"),"utf8")),stats=benchmark.run_summary.delta.paired.pass_rate;assert.equal(stats.count,1);assert.equal(stats.stddev,null);assert.equal(stats.confidence_interval_95,null);assert.equal(stats.statistically_valid,false);assert.equal(benchmark.run_summary.delta.stable_improvement,false);assert.match(benchmark.run_summary.delta.stable_improvement_reason,/one stochastic run/);}finally{rmSync(f.root,{recursive:true,force:true});}});


test("adversarial metadata cannot shrink requested pairs or forge the schedule",()=>{const f=fixture();try{const first=invoke(f,["--run-profile","standard"]);assert.equal(first.status,3);const path=join(f.workspace,"eval-1","eval_metadata.json"),metadata=JSON.parse(readFileSync(path,"utf8"));metadata.requested_pairs=1;writeFileSync(path,JSON.stringify(metadata));assert.throws(()=>expectedRunDirs(f.workspace),/exactly match run_profile/);metadata.requested_pairs=3;metadata.execution_schedule[1].seed++;writeFileSync(path,JSON.stringify(metadata));assert.throws(()=>expectedRunDirs(f.workspace),/strict total deterministic schedule/);}finally{rmSync(f.root,{recursive:true,force:true});}});

test("missing planned directory and cross-pair equivalence tampering fail closed",async()=>{const f=fixture();try{let run=invoke(f,["--run-profile","standard","--execute"]);assert.equal(run.status,3,run.stderr);rmSync(join(f.workspace,"eval-1","without_skill","run-3"),{recursive:true,force:true});assert.equal(expectedRunDirs(f.workspace).length,6);assert.match(validateExecutionEvidence(f.workspace).errors.join("\n"),/missing planned run directory/);const evidencePath=join(f.workspace,"eval-1","without_skill","run-1","execution-evidence.json"),evidence=JSON.parse(readFileSync(evidencePath,"utf8"));evidence.pair_equivalence.timeout_seconds++;writeFileSync(evidencePath,JSON.stringify(evidence));assert.match(validateExecutionEvidence(f.workspace).errors.join("\n"),/pair equivalence mismatch for timeout_seconds/);}finally{rmSync(f.root,{recursive:true,force:true});}});

test("duplicate eval ids are rejected before scaffolding",()=>{const f=fixture();try{const path=join(f.skill,"evals","evals.json"),data=JSON.parse(readFileSync(path,"utf8"));data.evals.push({...data.evals[0],name:"duplicate"});writeFileSync(path,JSON.stringify(data));const run=invoke(f,["--run-profile","standard"]),result=JSON.parse(run.stdout);assert.equal(run.status,1);assert.match(result.job.phases.find((p:any)=>p.name==="evaluation-design").error,/duplicate eval id/);}finally{rmSync(f.root,{recursive:true,force:true});}});

test("release full-eval uses release gates and accepts five valid pairs",()=>{const f=fixture({max_runs:10,max_turns:120,timeout_seconds:6000});try{const run=invoke(f,["--run-profile","release","--execute","--human-review","pass","--tests-status","pass","--triggering-status","pass"]),result=JSON.parse(run.stdout);assert.equal(run.status,0,run.stderr);assert.equal(result.status,"success");assert.equal(result.verification.profile,"release");assert.equal(JSON.parse(readFileSync(join(f.workspace,"benchmark.json"),"utf8")).run_summary.delta.paired.pass_rate.count,5);}finally{rmSync(f.root,{recursive:true,force:true});}});
