import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { generateKeyPairSync, sign } from "node:crypto";
import { resolve } from "node:path";
import { analyzeRecords, analyzeRecordsWithTestTrustPolicy, main, protocolIdentity, validateRecord, type ScreenReaderRecord } from "../dist/scripts/screen_reader_acceptance.js";
import * as attestationModule from "../dist/scripts/screen_reader_attestation.js";
import { ATTESTATION_PAYLOAD_TYPE, createPolicySigningRequest, createUnsignedRequest, pae, verifyAttestation, verifyAttestationWithTestTrustPolicy, type AttestationReceipt, type ReviewerTrustPolicy } from "../dist/scripts/screen_reader_attestation.js";
const protocol=JSON.parse(readFileSync(resolve("assets/screen-reader-acceptance/protocol.json"),"utf8"));
const ids=["headings-landmarks","filters-announcements","deep-link-focus","pagination","disclosure","feedback","status-noncolor"] as const;
const expected=(id:string,mode:"static"|"live")=>protocol.tasks.find((t:{id:string})=>t.id===id).expected_by_mode[mode];
const build="a".repeat(64);
const evidence=(suffix:string)=>({locator:`control:report-${suffix}`,observation:`Focus remained on the identified control and the complete announcement was heard once (${suffix}).`});
function record(id:string,at:"NVDA"|"VoiceOver",browser:"Firefox"|"Safari",os:"Windows"|"macOS"):ScreenReaderRecord{return{schema_version:1,protocol:protocolIdentity,record_id:id,synthetic:false,availability:"performed",unavailable_reason:null,reviewed_at:"2026-09-18T15:00:00Z",reviewer_code:"REV-A11Y7",privacy_reviewed:true,retention:{policy_version:"a11y-v1",delete_after:"2026-10-18"},environment:{os:{name:os,version:os==="Windows"?"11.0+24H2":"15.6.1"},assistive_technology:{name:at,version:at==="NVDA"?"2026.1":"15.6.1"},browser:{name:browser,version:browser==="Firefox"?"142.0":"18.6"},report_build:build},tasks:["static","live"].flatMap(mode=>ids.map(task_id=>({mode:mode as "static"|"live",task_id,expected:expected(task_id,mode as "static"|"live"),observed:`The ${task_id} outcome and focus behavior were observed in ${mode} mode.`,pass:true,evidence:evidence(`${mode}-${task_id}`)}))),findings:[]}}
const errors=(r:unknown)=>validateRecord(r).errors.join("\n");
function credentials(reviewer_code="REV-A11Y7"){const {publicKey,privateKey}=generateKeyPairSync("ed25519"),keyid="reviewer-test-key";const policy:ReviewerTrustPolicy={schema_version:1,qualified_reviewers:[{keyid,reviewer_code,public_key_pem:publicKey.export({type:"spki",format:"pem"}).toString(),actions:["manual-screen-reader-attest"]}]};return{privateKey,keyid,policy}}
function receipt(r:ScreenReaderRecord,c:ReturnType<typeof credentials>,issued="2026-09-18T15:01:00Z",expires="2026-09-19T15:01:00Z"):AttestationReceipt{const request=createUnsignedRequest(r,issued,expires);return{payloadType:ATTESTATION_PAYLOAD_TYPE,payload:request.payload,signatures:[{keyid:c.keyid,sig:sign(null,Buffer.from(request.signing_input,"base64"),c.privateKey).toString("base64")}]}}
function analyzed(records:ScreenReaderRecord[],now=new Date("2026-09-18T18:00:00Z")){const c=credentials(),receipts=records.map(r=>receipt(r,c));return analyzeRecordsWithTestTrustPolicy(records,receipts,c.policy,now)}

test("record is bound to the canonical protocol version and SHA-256",()=>{const r=record("SR-ACTUAL01","NVDA","Firefox","Windows");assert.equal(validateRecord(r).valid,true,errors(r));for(const [key,value] of [["version","9.9.9"],["sha256","0".repeat(64)]] as const){const bad=structuredClone(r) as any;bad.protocol[key]=value;assert.match(errors(bad),/canonical/)} });
test("task mode and exact mode-specific expected string cannot false-pass",()=>{const r=record("SR-ACTUAL02","NVDA","Firefox","Windows");r.tasks[0].expected="Expected headings behavior.";assert.match(errors(r),/exactly match canonical/);const swapped=record("SR-ACTUAL03","NVDA","Firefox","Windows");swapped.tasks[0].expected=expected("headings-landmarks","live");assert.match(errors(swapped),/exactly match canonical/)});
test("strict semver-like OS, AT, and browser versions reject placeholders",()=>{for(const field of ["os","assistive_technology","browser"] as const){for(const fake of ["1","unknown","11 24H2"]){const r=record("SR-VERSION1","NVDA","Firefox","Windows") as any;r.environment[field].version=fake;assert.match(errors(r),/semver-like/,`${field} accepted ${fake}`)}}});
test("structured evidence requires a bounded locator and substantive observation",()=>{const claim=record("SR-EVIDENCE","NVDA","Firefox","Windows") as any;claim.tasks[0].evidence={locator:"anything somewhere",observation:"It passed successfully."};const result=errors(claim);assert.match(result,/bounded semantic or DOM locator/);assert.match(result,/claim-only evidence/);const scalar=record("SR-EVIDEN2","NVDA","Firefox","Windows") as any;scalar.tasks[0].evidence="Reviewer says pass";assert.match(errors(scalar),/structured locator\/observation/)});
test("review timestamp cannot be future and retention is review-day through 90 days",()=>{const future=record("SR-FUTURE01","NVDA","Firefox","Windows");future.reviewed_at="2999-01-01T00:00:00Z";assert.match(errors(future),/future/);const early=record("SR-RETAIN01","NVDA","Firefox","Windows");early.retention.delete_after="2026-09-17";assert.match(errors(early),/on or after/);const late=record("SR-RETAIN02","NVDA","Firefox","Windows");late.retention.delete_after="2026-12-18";assert.match(errors(late),/no more than 90/);const edge=record("SR-RETAIN03","NVDA","Firefox","Windows");edge.retention.delete_after="2026-12-17";assert.equal(validateRecord(edge).valid,true,errors(edge))});
test("PASS requires all qualifying records to share one nonempty report build SHA-256",()=>{const nvda=record("SR-ACTUAL04","NVDA","Firefox","Windows"),vo=record("SR-ACTUAL05","VoiceOver","Safari","macOS");assert.equal(analyzed([nvda,vo]).status,"PASS");vo.environment.report_build="b".repeat(64);assert.equal(analyzed([nvda,vo]).status,"FAIL");assert.equal(analyzed([nvda,vo]).report_build.consistent,false);const empty=record("SR-ACTUAL06","NVDA","Firefox","Windows");empty.environment.report_build="";assert.match(errors(empty),/lowercase SHA-256/);assert.throws(()=>analyzed([empty,vo]),/report_build/)});
test("PASS still requires matrix, tasks, and zero P0/P1",()=>{const nvda=record("SR-ACTUAL07","NVDA","Firefox","Windows"),vo=record("SR-ACTUAL08","VoiceOver","Safari","macOS");assert.equal(analyzed([nvda]).status,"FAIL");vo.tasks[0].pass=false;assert.equal(analyzed([nvda,vo]).status,"FAIL");vo.tasks[0].pass=true;vo.findings.push({code:"SR-BLOCK",severity:"P1",task_id:"feedback",mode:"live",summary:"Required flow blocked.",evidence:evidence("blocked-feedback"),privacy_reviewed:true});assert.equal(analyzed([nvda,vo]).status,"FAIL")});
test("unavailable and synthetic records remain explicit non-evidence",()=>{const fixture=JSON.parse(readFileSync(resolve("assets/screen-reader-acceptance/fixtures/synthetic-unavailable.json"),"utf8"));assert.equal(validateRecord(fixture).valid,true,errors(fixture));assert.equal(analyzed([fixture]).status,"FAIL");const synthetic=record("SR-SYNTH999","NVDA","Firefox","Windows");synthetic.synthetic=true;assert.match(errors(synthetic),/synthetic records cannot pass/)});
test("privacy validation rejects identifiers",()=>{const r=record("SR-PRIVACY1","NVDA","Firefox","Windows");r.tasks[0].evidence.observation="Captured at /home/alice/report during the task.";assert.match(errors(r),/home path is prohibited/)});


test("unsigned or generic self-declared manual records cannot qualify",()=>{const nvda=record("SR-UNSIGN01","NVDA","Firefox","Windows"),vo=record("SR-UNSIGN02","VoiceOver","Safari","macOS");assert.equal(analyzeRecords([nvda,vo],[],new Date("2026-09-18T18:00:00Z")).status,"FAIL");const generic:any={payloadType:"application/json",payload:Buffer.from("{}").toString("base64"),signatures:[]};assert.equal(analyzeRecords([nvda,vo],[generic],new Date("2026-09-18T18:00:00Z")).status,"FAIL")});
test("attestation requires trusted Ed25519 signer, action, current validity, and exact record digest",()=>{const r=record("SR-ATTEST01","NVDA","Firefox","Windows"),trusted=credentials(),valid=receipt(r,trusted);assert.equal(verifyAttestationWithTestTrustPolicy(r,valid,trusted.policy,new Date("2026-09-18T18:00:00Z")).valid,true);const other=credentials();assert.equal(verifyAttestationWithTestTrustPolicy(r,valid,other.policy,new Date("2026-09-18T18:00:00Z")).valid,false);assert.equal(verifyAttestationWithTestTrustPolicy(r,valid,trusted.policy,new Date("2026-09-20T00:00:00Z")).valid,false);const edited=structuredClone(r);edited.tasks[0].observed+=" altered";assert.match(verifyAttestationWithTestTrustPolicy(edited,valid,trusted.policy,new Date("2026-09-18T18:00:00Z")).errors.join("\n"),/exact record/);const wrongAction=structuredClone(trusted.policy);wrongAction.qualified_reviewers[0].actions=["other"];assert.equal(verifyAttestationWithTestTrustPolicy(r,valid,wrongAction,new Date("2026-09-18T18:00:00Z")).valid,false)});
test("unsigned request binds protocol, report build, environment, pseudonyms, complete results, issuance and expiry",()=>{const r=record("SR-REQUEST1","NVDA","Firefox","Windows"),request=createUnsignedRequest(r,"2026-09-18T15:01:00Z","2026-09-19T15:01:00Z"),payload=JSON.parse(Buffer.from(request.payload,"base64").toString("utf8"));assert.equal(payload.protocol_sha256,protocolIdentity.sha256);assert.equal(payload.report_build,build);assert.equal(payload.session_code,r.record_id);assert.equal(payload.reviewer_code,r.reviewer_code);assert.match(payload.task_results_sha256,/^[a-f0-9]{64}$/);assert.match(payload.environment_sha256,/^[a-f0-9]{64}$/);assert.equal(payload.issued_at,"2026-09-18T15:01:00Z");assert.equal(payload.expires_at,"2026-09-19T15:01:00Z")});

test("production trust root is inaccessible to in-process mutation and rejects attacker keys",()=>{const r=record("SR-ATTACK01","NVDA","Firefox","Windows"),attacker=credentials(),forged=receipt(r,attacker);assert.equal("canonicalTrustPolicy" in attestationModule,false);assert.equal(Object.isExtensible(attestationModule),false);assert.equal(Reflect.set(attestationModule as object,"canonicalTrustPolicy",attacker.policy),false);assert.equal(verifyAttestation(r,forged,new Date("2026-09-18T18:00:00Z")).valid,false);assert.equal(analyzeRecordsWithTestTrustPolicy([r],[forged],attacker.policy,new Date("2026-09-18T18:00:00Z")).qualifying_records.length,1);assert.equal(analyzeRecords([r],[forged],new Date("2026-09-18T18:00:00Z")).qualifying_records.length,0)});
test("policy-signing request exposes only canonical public policy bytes and digests",()=>{const proposed=credentials().policy,request=createPolicySigningRequest(proposed);assert.equal(JSON.parse(Buffer.from(request.payload,"base64").toString("utf8")).qualified_reviewers.length,1);assert.match(request.proposed_policy_sha256,/^[a-f0-9]{64}$/);assert.match(request.current_policy_sha256,/^[a-f0-9]{64}$/);assert.match(request.notice,/no private key/i)});

test("production CLI rejects every caller-supplied policy spelling and unknown options",()=>{assert.throws(()=>main(["--trust-policy","attacker.json"]),/forbidden/);assert.throws(()=>main(["--trust-policy=attacker.json"]),/forbidden/);assert.throws(()=>main(["--attacker-option","records.json"]),/unknown option/)});
