import { createHash } from "node:crypto";
import { CANDIDATE_SELECTION_VERSION, CandidateSelectionValidationError, type CandidateMetricEvidence, type CandidateSelectionDecisionV1, type CandidateSelectionInputV1, type CandidateSelectionTrace, type CandidateSelectionValidation, type SelectionCandidate, type SelectionDimension } from "./candidate-selection-types.js";
const DIMS=["effectiveness","productivity","stability","safety"] as const;
const SHA=/^[a-f0-9]{64}$/; const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/; const MAX_CANDIDATES=128,MAX_EVIDENCE=256;
const rec=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const own=(v:Record<string,unknown>,keys:readonly string[])=>Object.keys(v).every(k=>keys.includes(k));
const finite01=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v)&&v>=0&&v<=1;
const pos=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v)&&v>0&&v<=1_000_000;
const diagnostic=(path:string,message:string,remediation:string)=>({code:"CANDIDATE_SELECTION_INVALID" as const,path,message,remediation});
function dataOnly(v:unknown,seen=new WeakSet<object>()):boolean{
  if(typeof v!=="object"||v===null)return true;
  if(seen.has(v))return false;seen.add(v);
  const array=Array.isArray(v);
  if(Object.getPrototypeOf(v)!==(array?Array.prototype:Object.prototype))return false;
  const keys=Reflect.ownKeys(v),ds=Object.getOwnPropertyDescriptors(v);
  if(keys.some(k=>typeof k!=="string"))return false;
  if(array){
    if(keys.length!==(v as unknown[]).length+1||keys[keys.length-1]!=="length")return false;
    const length=ds.length;
    if(!length||!("value" in length)||length.enumerable||length.configurable||!length.writable)return false;
    for(let i=0;i<(v as unknown[]).length;i++)if(keys[i]!==String(i))return false;
  }
  for(const key of Object.keys(ds)){
    if(array&&key==="length")continue;
    const d=ds[key];
    if(!d||!("value" in d)||!d.enumerable||!d.configurable||!d.writable||!dataOnly(d.value,seen))return false;
  }
  return true;
}
function metric(v:unknown):v is CandidateMetricEvidence{return rec(v)&&own(v,["estimate","lowerBound","upperBound","sampleSize","evidenceHashes"])&&finite01(v.estimate)&&finite01(v.lowerBound)&&finite01(v.upperBound)&&v.lowerBound<=v.estimate&&v.estimate<=v.upperBound&&Number.isSafeInteger(v.sampleSize)&&(v.sampleSize as number)>=1&&(v.sampleSize as number)<=1_000_000&&Array.isArray(v.evidenceHashes)&&v.evidenceHashes.length>=1&&v.evidenceHashes.length<=MAX_EVIDENCE&&v.evidenceHashes.every(x=>typeof x==="string"&&SHA.test(x))&&new Set(v.evidenceHashes).size===v.evidenceHashes.length;}
function validateUnsafe(value:unknown):CandidateSelectionValidation{const ds:CandidateSelectionValidation["diagnostics"]=[];if(!rec(value)||!own(value,["schemaVersion","objective","uncertainty","candidates","override"]))return{valid:false,diagnostics:[diagnostic("/","Input must be a closed plain object.","Provide only the versioned selection fields.")]};if(value.schemaVersion!==CANDIDATE_SELECTION_VERSION)ds.push(diagnostic("/schemaVersion","Unsupported candidate selection version.","Use 1.0.0."));const o=value.objective;if(!rec(o)||!own(o,["kind","weights","tieTolerance","thresholds","criticalSafetyMinimum"])||o.kind!=="weighted-conservative-utility")ds.push(diagnostic("/objective","Objective must declare the closed weighted conservative utility contract.","Declare kind, weights, tieTolerance, thresholds, and criticalSafetyMinimum."));else{if(!rec(o.weights)||!own(o.weights,DIMS)||!DIMS.every(d=>pos((o.weights as Record<string,unknown>)[d]))||Object.keys(o.weights).length!==4)ds.push(diagnostic("/objective/weights","All four finite positive weights are required.","Provide one positive finite weight per dimension."));if(!finite01(o.tieTolerance))ds.push(diagnostic("/objective/tieTolerance","tieTolerance must be between zero and one.","Provide a finite normalized tolerance."));if(!rec(o.thresholds)||!own(o.thresholds,DIMS)||Object.keys(o.thresholds).length!==4||!DIMS.every(d=>rec((o.thresholds as any)[d])&&own((o.thresholds as any)[d],["minimum"])&&finite01((o.thresholds as any)[d].minimum)))ds.push(diagnostic("/objective/thresholds","Every dimension requires exactly one finite minimum.","Provide closed thresholds for all dimensions."));if(!finite01(o.criticalSafetyMinimum))ds.push(diagnostic("/objective/criticalSafetyMinimum","Critical safety minimum must be between zero and one.","Provide a finite critical veto threshold."));else if(rec(o.thresholds)&&rec(o.thresholds.safety)&&finite01(o.thresholds.safety.minimum)&&o.criticalSafetyMinimum>o.thresholds.safety.minimum)ds.push(diagnostic("/objective/criticalSafetyMinimum","Critical safety veto cannot exceed the ordinary safety threshold.","Set criticalSafetyMinimum no higher than thresholds.safety.minimum."));}
const u=value.uncertainty;if(!rec(u)||!own(u,["minimumSamples","maximumSamples","maximumIntervalWidth"])||!Number.isSafeInteger(u.minimumSamples)||(u.minimumSamples as number)<1||(u.minimumSamples as number)>1_000_000||!Number.isSafeInteger(u.maximumSamples)||(u.maximumSamples as number)<(u.minimumSamples as number)||(u.maximumSamples as number)>1_000_000||!rec(u.maximumIntervalWidth)||!own(u.maximumIntervalWidth,DIMS)||Object.keys(u.maximumIntervalWidth).length!==4||!DIMS.every(d=>finite01((u.maximumIntervalWidth as any)[d])))ds.push(diagnostic("/uncertainty","Uncertainty and sample limits must be complete, finite, and coherent.","Bound samples and interval width for every dimension."));
if(!Array.isArray(value.candidates)||value.candidates.length<2||value.candidates.length>MAX_CANDIDATES)ds.push(diagnostic("/candidates","Between 2 and 128 candidates are required.","Provide a bounded comparison set."));else{const ids=new Set<string>(),hashes=new Set<string>();value.candidates.forEach((c,i)=>{const p=`/candidates/${i}`;if(!rec(c)||!own(c,["candidateId","candidateHash","metrics"])||typeof c.candidateId!=="string"||!ID.test(c.candidateId)||typeof c.candidateHash!=="string"||!SHA.test(c.candidateHash)||!rec(c.metrics)||!own(c.metrics,DIMS)||Object.keys(c.metrics).length!==4||!DIMS.every(d=>metric((c.metrics as any)[d])))ds.push(diagnostic(p,"Candidate shape, hashes, or metrics are invalid.","Provide a closed candidate with bounded evidence for all dimensions."));else{if(ids.has(c.candidateId)||hashes.has(c.candidateHash))ds.push(diagnostic(p,"Candidate IDs and hashes must be unique.","Remove duplicate candidate identities."));ids.add(c.candidateId);hashes.add(c.candidateHash);}});}
if(value.override!==undefined){const x=value.override;if(!rec(x)||!own(x,["candidateId","nonSafetyOnly","identity","rationale"])||typeof x.candidateId!=="string"||!ID.test(x.candidateId)||x.nonSafetyOnly!==true||!rec(x.identity)||!own(x.identity,["actorId","role"])||typeof x.identity.actorId!=="string"||!ID.test(x.identity.actorId)||typeof x.identity.role!=="string"||!ID.test(x.identity.role)||typeof x.rationale!=="string"||x.rationale.trim().length<12||x.rationale.length>2000)ds.push(diagnostic("/override","Override requires a candidate, bounded identity, rationale, and nonSafetyOnly=true.","Provide an attributable non-safety override rationale."));else if(Array.isArray(value.candidates)&&!value.candidates.some(c=>rec(c)&&c.candidateId===x.candidateId))ds.push(diagnostic("/override/candidateId","Override candidate is absent.","Reference one submitted candidate."));}
return{valid:ds.length===0,diagnostics:ds};}
export function validateCandidateSelection(value:unknown):CandidateSelectionValidation{try{if(!dataOnly(value))return{valid:false,diagnostics:[diagnostic("/","Input must be acyclic plain data without accessors, sparse arrays, or exotic prototypes.","Materialize a bounded plain JSON value.")]};return validateUnsafe(value);}catch{return{valid:false,diagnostics:[diagnostic("/","Input could not be safely inspected.","Provide unproxied bounded plain JSON.")]};}}
const cmp=(a:string,b:string)=>a<b?-1:a>b?1:0;
function canonical(v:unknown):unknown{return Array.isArray(v)?v.map(canonical):rec(v)?Object.fromEntries(Object.keys(v).sort(cmp).map(k=>[k,canonical(v[k])])):v;}
function normalized(input:CandidateSelectionInputV1):CandidateSelectionInputV1{return{schemaVersion:CANDIDATE_SELECTION_VERSION,objective:{...input.objective,weights:{...input.objective.weights},thresholds:{...input.objective.thresholds}},uncertainty:{...input.uncertainty,maximumIntervalWidth:{...input.uncertainty.maximumIntervalWidth}},candidates:input.candidates.map(c=>({...c,metrics:Object.fromEntries(DIMS.map(d=>[d,{...c.metrics[d],evidenceHashes:[...c.metrics[d].evidenceHashes].sort(cmp)}])) as any})).sort((a,b)=>cmp(a.candidateId,b.candidateId)),...(input.override?{override:{...input.override,identity:{...input.override.identity},rationale:input.override.rationale.trim()}}:{})};}
export function canonicalSerializeCandidateSelection(value:unknown):string{const checked=validateCandidateSelection(value);if(!checked.valid)throw new CandidateSelectionValidationError(checked.diagnostics);return JSON.stringify(canonical(normalized(value as CandidateSelectionInputV1)));}
export function hashCandidateSelectionInput(value:unknown):string{return createHash("sha256").update(canonicalSerializeCandidateSelection(value)).digest("hex");}
const dominates=(a:SelectionCandidate,b:SelectionCandidate,t:number)=>DIMS.every(d=>a.metrics[d].lowerBound+t>=b.metrics[d].lowerBound)&&DIMS.some(d=>a.metrics[d].lowerBound>b.metrics[d].lowerBound+t);
export function selectCandidate(value:unknown):CandidateSelectionDecisionV1{const checked=validateCandidateSelection(value);if(!checked.valid)throw new CandidateSelectionValidationError(checked.diagnostics);const input=normalized(value as CandidateSelectionInputV1),sum=DIMS.reduce((n,d)=>n+input.objective.weights[d],0);const traces:CandidateSelectionTrace[]=input.candidates.map(c=>{const thresholdFailures=DIMS.filter(d=>c.metrics[d].lowerBound<input.objective.thresholds[d].minimum);const uncertaintyFailures=DIMS.filter(d=>c.metrics[d].sampleSize<input.uncertainty.minimumSamples||c.metrics[d].sampleSize>input.uncertainty.maximumSamples||c.metrics[d].upperBound-c.metrics[d].lowerBound>input.uncertainty.maximumIntervalWidth[d]);const veto=c.metrics.safety.lowerBound<input.objective.criticalSafetyMinimum;return{candidateId:c.candidateId,candidateHash:c.candidateHash,evidenceHashes:[...new Set(DIMS.flatMap(d=>c.metrics[d].evidenceHashes))].sort(cmp),conservativeUtility:DIMS.reduce((n,d)=>n+input.objective.weights[d]*c.metrics[d].lowerBound,0)/sum,thresholdFailures,uncertaintyFailures,criticalSafetyVeto:veto,paretoDominatedBy:[] as string[],disposition:"eligible" as CandidateSelectionTrace["disposition"],reason:"pareto-conflict" as CandidateSelectionTrace["reason"]};});const byId=new Map(input.candidates.map(c=>[c.candidateId,c]));
const safelyEligible=(t:CandidateSelectionTrace)=>!t.criticalSafetyVeto&&!t.thresholdFailures.includes("safety")&&!t.uncertaintyFailures.includes("safety");
const eligible=traces.filter(t=>safelyEligible(t)&&t.thresholdFailures.length===0&&t.uncertaintyFailures.length===0);
const eligibleIds=new Set(eligible.map(t=>t.candidateId));
for(const t of eligible)t.paretoDominatedBy=eligible.filter(c=>c.candidateId!==t.candidateId&&dominates(byId.get(c.candidateId)!,byId.get(t.candidateId)!,input.objective.tieTolerance)).map(c=>c.candidateId).sort(cmp);
let selected:CandidateSelectionTrace|undefined,reason:CandidateSelectionDecisionV1["reason"]="no-eligible-candidate";if(input.override){const target=traces.find(t=>t.candidateId===input.override!.candidateId)!;if(!safelyEligible(target))throw new CandidateSelectionValidationError([diagnostic("/override/candidateId","A non-safety override cannot bypass a critical veto, safety threshold, or safety uncertainty limit.","Choose a safety-qualified candidate or gather more safety evidence.")]);selected=target;reason="non-safety-human-override";}else{const best=eligible.reduce((n,t)=>Math.max(n,t.conservativeUtility),-Infinity);const contenders=eligible.filter(t=>best-t.conservativeUtility<=input.objective.tieTolerance);if(contenders.length===1){selected=contenders[0];reason="objective-winner";}else{const frontier=contenders.filter(t=>!t.paretoDominatedBy.some(id=>contenders.some(e=>e.candidateId===id)));if(frontier.length===1){selected=frontier[0];reason="unique-pareto-winner";}else if(frontier.length>1)reason="pareto-conflict";}}
for(const t of traces){if(selected?.candidateId===t.candidateId){t.disposition="selected";t.reason=input.override?"non-safety-human-override":"selected";}else{t.disposition="rejected";t.reason=t.criticalSafetyVeto?"critical-safety-veto":t.thresholdFailures.includes("safety")?"safety-threshold":t.uncertaintyFailures.includes("safety")?"insufficient-safety-evidence":t.thresholdFailures.length?"non-safety-threshold":t.uncertaintyFailures.length?"insufficient-evidence":eligibleIds.has(t.candidateId)&&t.paretoDominatedBy.length?"pareto-dominated":"pareto-conflict";}}
return{schemaVersion:CANDIDATE_SELECTION_VERSION,status:selected?"selected":"inconclusive",inputHash:hashCandidateSelectionInput(input),selectedCandidateId:selected?.candidateId??null,selectedCandidateHash:selected?.candidateHash??null,humanDecisionRequired:!selected,reason,objective:{formula:"sum(weight[dimension] * lowerBound[dimension]) / sum(weights)",dimensions:[...DIMS],weights:{...input.objective.weights},tieTolerance:input.objective.tieTolerance,thresholds:Object.fromEntries(DIMS.map(d=>[d,{...input.objective.thresholds[d]}])) as CandidateSelectionDecisionV1["objective"]["thresholds"],criticalSafetyMinimum:input.objective.criticalSafetyMinimum},uncertainty:{minimumSamples:input.uncertainty.minimumSamples,maximumSamples:input.uncertainty.maximumSamples,maximumIntervalWidth:{...input.uncertainty.maximumIntervalWidth}},traces,override:input.override??null};}
