/** Agent-creator-local normalized telemetry. No runtime sibling package dependency. */
export const TELEMETRY_SCHEMA_VERSION = "2.0" as const;
export type AvailabilityReason = "not-exposed" | "malformed" | "not-applicable" | "pricing-unavailable";
export type MetricSource = "runner-wall-clock" | "goose-output-metadata" | "legacy-timing-artifact" | "grading-artifact" | "unavailable";
export interface NullableTelemetryMetric { value: number | null; availability_reason: AvailabilityReason | null; source: MetricSource; }
export interface ResourceIdentity { provider: string | null; model: string | null; goose_version: string | null; }
export interface NormalizedResourceTelemetry { schema_version: typeof TELEMETRY_SCHEMA_VERSION; duration_seconds: NullableTelemetryMetric; tokens: NullableTelemetryMetric; turns: NullableTelemetryMetric; cost_usd: NullableTelemetryMetric; identity: ResourceIdentity; }
const SOURCES = new Set<MetricSource>(["runner-wall-clock","goose-output-metadata","legacy-timing-artifact","grading-artifact","unavailable"]);
const finite = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) && value >= 0 ? (Object.is(value, -0) ? 0 : value) : null;
const integer = (value: unknown): number | null => { const n=finite(value); return n !== null && Number.isSafeInteger(n) ? n : null; };
export function metric(value: unknown, source: MetricSource, reason: AvailabilityReason = "not-exposed", integral=false): NullableTelemetryMetric { const n=integral?integer(value):finite(value), validSource=SOURCES.has(source); return n===null||!validSource?{value:null,availability_reason:value===undefined||value===null?reason:"malformed",source:"unavailable"}:{value:n,availability_reason:null,source}; }
const text=(value:unknown):string|null=>typeof value==="string"&&value.trim()===value&&value.length>0?value:null;
/** Reads v2 and legacy timing artifacts. Invalid legacy values become null, never zero. */
export function normalizeResourceTelemetry(value: unknown, gradingTiming?: unknown): NormalizedResourceTelemetry {
 const raw=typeof value==="object"&&value!==null?value as any:{}, grading=typeof gradingTiming==="object"&&gradingTiming!==null?gradingTiming as any:{};
 if(raw.schema_version===TELEMETRY_SCHEMA_VERSION&&raw.metrics){const m=raw.metrics,p=raw.provenance??{};return {schema_version:TELEMETRY_SCHEMA_VERSION,duration_seconds:metric(m.duration_seconds?.value,m.duration_seconds?.source??"legacy-timing-artifact",m.duration_seconds?.availability_reason??"not-exposed"),tokens:metric(m.tokens?.value,m.tokens?.source??"legacy-timing-artifact",m.tokens?.availability_reason??"not-exposed",true),turns:metric(m.turns?.value,m.turns?.source??"legacy-timing-artifact",m.turns?.availability_reason??"not-exposed",true),cost_usd:metric(m.cost_usd?.value,m.cost_usd?.source??"legacy-timing-artifact",m.cost_usd?.availability_reason??"pricing-unavailable"),identity:{provider:text(p.provider),model:text(p.model),goose_version:text(p.goose_version)}};}
 const duration=raw.total_duration_seconds!==undefined?metric(raw.total_duration_seconds,"legacy-timing-artifact"):metric(grading.total_duration_seconds,"grading-artifact");
 return {schema_version:TELEMETRY_SCHEMA_VERSION,duration_seconds:duration,tokens:metric(raw.total_tokens??raw.tokens,"legacy-timing-artifact","not-exposed",true),turns:metric(raw.total_turns??raw.turns,"legacy-timing-artifact","not-exposed",true),cost_usd:metric(raw.cost_usd,"legacy-timing-artifact","pricing-unavailable"),identity:{provider:text(raw.provider),model:text(raw.model),goose_version:text(raw.goose_version??raw.host_version)}};
}
export function timingArtifact(input:{duration_seconds:unknown;tokens?:unknown;turns?:unknown;cost_usd?:unknown;provider?:unknown;model?:unknown;goose_version?:unknown}) { const normalized={schema_version:TELEMETRY_SCHEMA_VERSION,duration_seconds:metric(input.duration_seconds,"runner-wall-clock"),tokens:metric(input.tokens,"goose-output-metadata","not-exposed",true),turns:metric(input.turns,"goose-output-metadata","not-exposed",true),cost_usd:metric(input.cost_usd,"goose-output-metadata","pricing-unavailable"),identity:{provider:text(input.provider),model:text(input.model),goose_version:text(input.goose_version)}}; return {schema_version:TELEMETRY_SCHEMA_VERSION,total_duration_seconds:normalized.duration_seconds.value,total_tokens:normalized.tokens.value,total_turns:normalized.turns.value,cost_usd:normalized.cost_usd.value,duration_availability_reason:normalized.duration_seconds.availability_reason,token_availability_reason:normalized.tokens.availability_reason,turn_availability_reason:normalized.turns.availability_reason,cost_availability_reason:normalized.cost_usd.availability_reason,metrics:normalized,provenance:{...normalized.identity,metric_sources:{duration_seconds:normalized.duration_seconds.source,tokens:normalized.tokens.source,turns:normalized.turns.source,cost_usd:normalized.cost_usd.source}}}; }
