import { after, before, test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmodSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import path from "node:path";
const root=path.join(import.meta.dirname,".."),work=mkdtempSync(path.join(tmpdir(),"facade-install-test-")),stage=path.join(work,"stage"),destination=path.join(work,"installed");
const config=JSON.parse(readFileSync(path.join(root,"bun-release.json"),"utf8")),releaseKey=process.platform+"-"+process.arch;
const run=(command:string,args:string[],cwd=root)=>spawnSync(command,args,{cwd,encoding:"utf8",timeout:30000});
function inventory(directory:string,base=directory):any[]{const rows:any[]=[];for(const entry of readdirSync(directory,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name,"en"))){const absolute=path.join(directory,entry.name),relative=path.relative(base,absolute).split(path.sep).join("/"),stat=lstatSync(absolute);if(entry.isDirectory())rows.push(...inventory(absolute,base));else rows.push({path:relative,mode:(stat.mode&0o777).toString(8).padStart(3,"0"),size:stat.size,sha256:createHash("sha256").update(readFileSync(absolute)).digest("hex")});}return rows;}
before(()=>{mkdirSync(path.join(stage,"skills","example","scripts"),{recursive:true});writeFileSync(path.join(stage,"plugin.json"),JSON.stringify({name:"agent-plugins"}));const executable=path.join(stage,"skills","example","scripts","example"+(process.platform==="win32"?".exe":""));writeFileSync(executable,"fixture");if(process.platform!=="win32")chmodSync(executable,0o755);const manifest={schemaVersion:1,releaseKey,bunTarget:config.targets[releaseKey],bunVersion:config.bunVersion,files:inventory(stage)};writeFileSync(path.join(stage,"release-manifest.json"),JSON.stringify(manifest,null,2)+"\n");});
after(()=>rmSync(work,{recursive:true,force:true}));
test("Make facade advertises and delegates canonical commands",()=>{const help=run("make",["help"]);assert.equal(help.status,0,help.stderr);for(const target of ["test","bundle","release","install"])assert.ok(help.stdout.includes("make "+target));const expected:any={test:"npm test",bundle:"npm run bundle",release:"npm run release",install:"npm run install:staged"};for(const [target,command] of Object.entries(expected)){const dry=run("make",["-n",target]);assert.equal(dry.status,0,dry.stderr);assert.ok(dry.stdout.includes(String(command)),dry.stdout);}});
test("installer help and dry-run do not write",()=>{const help=run(process.execPath,["scripts/install-staged-plugin.mjs","--help"]);assert.equal(help.status,0);assert.match(help.stdout,/--dry-run/);assert.match(help.stdout,/project-local|\.agents\/plugins/);const result=run(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--destination",destination,"--dry-run"]);assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,"dry-run");assert.equal(lstatSync(destination,{throwIfNoEntry:false}),undefined);const fakeHome=path.join(work,"home");const local=spawnSync(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--dry-run"],{cwd:root,encoding:"utf8",env:{...process.env,HOME:fakeHome}});assert.equal(local.status,0,local.stderr);assert.equal(JSON.parse(local.stdout).destination,path.join(root,".agents","plugins","agent-plugins"));assert.equal(lstatSync(fakeHome,{throwIfNoEntry:false}),undefined);});
test("installer validates, refuses overwrite, and force replaces",()=>{let result=run(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--destination",destination]);assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(readFileSync(path.join(destination,"plugin.json"),"utf8")).name,"agent-plugins");writeFileSync(path.join(destination,"marker"),"keep");result=run(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--destination",destination]);assert.notEqual(result.status,0);assert.match(result.stderr,/already exists/);assert.equal(readFileSync(path.join(destination,"marker"),"utf8"),"keep");result=run(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--destination",destination,"--force"]);assert.equal(result.status,0,result.stderr);assert.equal(lstatSync(path.join(destination,"marker"),{throwIfNoEntry:false}),undefined);});
test("installer rejects tampering",()=>{const plugin=path.join(stage,"plugin.json"),original=readFileSync(plugin,"utf8");writeFileSync(plugin,"tampered");const result=run(process.execPath,["scripts/install-staged-plugin.mjs","--source",stage,"--destination",path.join(work,"bad")]);assert.notEqual(result.status,0);assert.match(result.stderr,/checksum validation/);writeFileSync(plugin,original);});

test("force never permits a symlink destination or destination ancestor",{skip:process.platform==="win32"},()=>{for(const dryRun of [false,true]){for(const kind of ["destination","ancestor"]){const caseRoot=path.join(work,`symlink-${kind}-${dryRun?"dry":"write"}`),outside=path.join(caseRoot,"outside"),container=path.join(caseRoot,"container");mkdirSync(outside,{recursive:true});mkdirSync(container,{recursive:true});const marker=path.join(outside,"outside-marker");writeFileSync(marker,"untouched");let attackedDestination:string;if(kind==="destination"){attackedDestination=path.join(container,"plugin");symlinkSync(outside,attackedDestination,"dir");}else{const linkedAncestor=path.join(container,"linked");symlinkSync(outside,linkedAncestor,"dir");attackedDestination=path.join(linkedAncestor,"plugin");}
const args=["scripts/install-staged-plugin.mjs","--source",stage,"--destination",attackedDestination,"--force",...(dryRun?["--dry-run"]:[])];const result=run(process.execPath,args);assert.notEqual(result.status,0,`${kind} ${dryRun?"dry-run":"write"} unexpectedly succeeded`);assert.match(result.stderr,/symbolic link/);assert.equal(readFileSync(marker,"utf8"),"untouched");assert.equal(lstatSync(path.join(outside,"plugin.json"),{throwIfNoEntry:false}),undefined);assert.equal(Boolean(lstatSync(attackedDestination,{throwIfNoEntry:false})?.isSymbolicLink()),kind==="destination");}}});
