import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { auditPluginMigration, migratePlugin } from "../dist/scripts/migrate_plugin.js";
const PS="https://agent-plugins.org/schemas/1.0.0/plugin.schema.json";
function fixture(fn:(root:string)=>void){const t=mkdtempSync(join(tmpdir(),"migrate-plugin-"));try{fn(t)}finally{rmSync(t,{recursive:true,force:true})}}
function manifest(extra:Record<string,unknown>={}){return{name:"demo",version:"1.0.0",description:"demo",...extra}}
test("dry-run audits all compatibility classes without mutation",()=>fixture(root=>{mkdirSync(join(root,"skills","one"),{recursive:true});mkdirSync(join(root,"agents"));mkdirSync(join(root,"hooks"));writeFileSync(join(root,"skills","one","SKILL.md"),"---\nname: one\ndescription: demo\n---\n");writeFileSync(join(root,"agents","review.yaml"),"name: review\n");writeFileSync(join(root,"hooks","hooks.json"),JSON.stringify({hooks:{}}));writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({mcpServers:{tool:{command:"node"}},legacyFlag:true})));const before=readFileSync(join(root,"plugin.json"),"utf8");const r=auditPluginMigration(root);assert.equal(r.status,"ready");assert.deepEqual(new Set(r.findings.map(x=>x.classification)),new Set(["portable-core","goose-extension","legacy-compatible","migratable"]));assert.ok(r.proposedMoves.some(x=>x.to==="extensions/io.github.bioinfornatics.agent-plugins.goose/hooks.json"));assert.ok(r.proposedDocuments.some(x=>x.path==="mcp.json"));assert.equal(readFileSync(join(root,"plugin.json"),"utf8"),before);assert.equal(existsSync(join(root,"mcp.json")),false)}));
test("explicit approved mutation preserves backups and writes portable documents",()=>fixture(root=>{mkdirSync(join(root,"hooks"),{recursive:true});writeFileSync(join(root,"hooks","hooks.json"),JSON.stringify({hooks:{}}));writeFileSync(join(root,".mcp.json"),JSON.stringify({mcpServers:{tool:{command:"node",args:["server.js"]}}}));writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest()));assert.equal(migratePlugin(root,{apply:true}).status,"blocked");const r=migratePlugin(root,{apply:true,approval:true,backupDirectory:join(root,"backup")});assert.equal(r.status,"applied");assert.ok(existsSync(join(root,"backup","plugin.json")));assert.ok(existsSync(join(root,"backup",".mcp.json")));assert.ok(existsSync(join(root,"backup","hooks","hooks.json")));assert.ok(existsSync(join(root,"extensions","io.github.bioinfornatics.agent-plugins.goose","hooks.json")));const m=JSON.parse(readFileSync(join(root,"plugin.json"),"utf8"));assert.equal(m.$schema,PS);assert.equal(m.extensions["io.github.bioinfornatics.agent-plugins.goose"].version,1);const mc=JSON.parse(readFileSync(join(root,"mcp.json"),"utf8"));assert.equal(mc.mcpServers.tool.type,"stdio");assert.equal(existsSync(join(root,".mcp.json")),false)}));
test("ambiguous MCP, unsafe paths, secrets, and inactive schemas block safely",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({$schema:"https://agent-plugins.org/schemas/1.1.0/plugin.schema.json",mcpServers:{x:{command:"../escape",env:{API_KEY:"sk-abcdefghijklmnopqrstuvwxyz"}}}})));writeFileSync(join(root,".mcp.json"),JSON.stringify({mcpServers:{x:{command:"node"}}}));const before=readFileSync(join(root,"plugin.json"),"utf8");const r=migratePlugin(root,{apply:true,approval:true});assert.equal(r.status,"blocked");assert.ok(r.findings.some(x=>x.message.includes("precedence is undefined")));assert.ok(r.findings.some(x=>x.message.includes("Unsafe")));assert.ok(r.findings.some(x=>x.message.includes("secret")));assert.ok(r.findings.some(x=>x.message.includes("inactive")));assert.equal(readFileSync(join(root,"plugin.json"),"utf8"),before);assert.equal(existsSync(join(root,".plugin-migration-backups")),false)}));
test("noncanonical Skills propose safe moves and collisions block",()=>fixture(root=>{mkdirSync(join(root,"old"),{recursive:true});mkdirSync(join(root,"skills","review"),{recursive:true});writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({$schema:PS})));writeFileSync(join(root,"old","SKILL.md"),"---\nname: review\ndescription: x\n---\n");writeFileSync(join(root,"skills","review","SKILL.md"),"---\nname: review\ndescription: y\n---\n");const r=auditPluginMigration(root);assert.equal(r.status,"blocked");assert.ok(r.findings.some(x=>x.artifact==="old/SKILL.md"&&x.classification==="unsupported"))}));
test("historical Block namespace migrates to the distributor-owned namespace",()=>fixture(root=>{mkdirSync(join(root,"extensions","io.github.block.goose"),{recursive:true});writeFileSync(join(root,"extensions","io.github.block.goose","hooks.json"),JSON.stringify({hooks:{PostToolUse:[{hooks:[{command:"echo ok"}]}]}}));writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({$schema:PS,extensions:{"io.github.block.goose":{version:1,hooks:"extensions/io.github.block.goose/hooks.json"}}})));const audit=auditPluginMigration(root);assert.equal(audit.status,"ready");assert.ok(audit.proposedMoves.some(x=>x.from==="extensions/io.github.block.goose/hooks.json"&&x.to==="extensions/io.github.bioinfornatics.agent-plugins.goose/hooks.json"));const applied=migratePlugin(root,{apply:true,approval:true});assert.equal(applied.status,"applied");const updated=JSON.parse(readFileSync(join(root,"plugin.json"),"utf8"));assert.equal(updated.extensions["io.github.block.goose"],undefined);assert.equal(updated.extensions["io.github.bioinfornatics.agent-plugins.goose"].version,1);assert.equal(existsSync(join(root,"extensions","io.github.bioinfornatics.agent-plugins.goose","hooks.json")),true)}));
