import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assessEvidenceReceipt, discoverPluginComponents } from "../dist/scripts/component_evidence.js";
import { verifyPlugin } from "../dist/scripts/verify_plugin_gates.js";
import { sourceHash } from "../dist/scripts/package_manifest.js";

function fullPlugin() {
  const tmp=mkdtempSync(join(tmpdir(),"typed-plugin-")),root=join(tmp,"complete");
  mkdirSync(join(root,"skills","writer"),{recursive:true});
  mkdirSync(join(root,"agents"),{recursive:true});
  mkdirSync(join(root,"hooks"),{recursive:true});
  writeFileSync(join(root,"plugin.json"),JSON.stringify({$schema:"https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",name:"complete",version:"1.0.0",description:"Complete plugin"}));
  writeFileSync(join(root,"skills","writer","SKILL.md"),"---\nname: writer\ndescription: Writes verified output. Use for writing.\n---\n\n# Writer\n");
  writeFileSync(join(root,"agents","reviewer.md"),"# Reviewer\n");
  writeFileSync(join(root,"hooks","hooks.json"),JSON.stringify({hooks:{PreToolUse:[{matcher:"developer__shell",hooks:[{type:"command",command:"echo ok"}]}]}}));
  writeFileSync(join(root,"mcp.json"),JSON.stringify({$schema:"https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",mcpServers:{docs:{type:"stdio",command:"node",args:["server.js"]}}}));
  writeFileSync(join(root,"server.js"),"");
  return{tmp,root};
}
function typed(kind:string,name:string,hash:string,payload:any,status="pass",applicability:any={status:"applicable"}) {
  return{schema_version:"1.0",artifact:kind,name,status,source_sha256:hash,generated_at:new Date(0).toISOString(),applicability,checks:[{id:"behavior",status:"pass",evidence:["run:1"]}],payload};
}
function receipts(tmp:string,root:string) {
  const paths:string[]=[],components=discoverPluginComponents(root);
  for(const component of components){
    const payload=component.kind==="skill"?{evaluated_behaviors:["write"]}:component.kind==="agent"?{evaluated_tasks:["review"]}:component.kind==="hook"?{events:["PreToolUse"],safety_cases:["safe command"]}:{servers:["docs"],capabilities:["tools/list"]};
    const path=join(tmp,component.kind+"-"+component.id+".json");writeFileSync(path,JSON.stringify(typed(component.kind,component.id,component.source_sha256,payload)));paths.push(path);
  }
  return paths;
}
test("discovers Skill, agent, hook, and MCP components with independent source hashes",()=>{const{tmp,root}=fullPlugin();try{const components=discoverPluginComponents(root);assert.deepEqual(components.map(x=>x.key),["agent:reviewer","hook:goose-hooks","mcp:mcp","skill:writer"]);assert.ok(components.every(x=>/^[a-f0-9]{64}$/.test(x.source_sha256)));assert.equal(new Set(components.map(x=>x.source_sha256)).size,4);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("full plugins require typed evidence even when generic tests-status passes",()=>{const{tmp,root}=fullPlugin();try{const skill=discoverPluginComponents(root).find(x=>x.kind==="skill")!,legacy=join(tmp,"legacy.json");writeFileSync(legacy,JSON.stringify({schema_version:"1.0",artifact:"skill",name:skill.id,status:"pass",source_sha256:skill.source_sha256}));const result=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:[legacy],testsStatus:"pass"});assert.equal(result.status,"blocked");assert.equal(result.gates.components.status,"blocked");assert.match(result.gates.components.evidence.join("\n"),/typed evidence envelope required|receipt missing/);assert.equal(result.components["skill:writer"].typed,false);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("component aggregation reports explicit applicability, N/A reasons, and freshness",()=>{const{tmp,root}=fullPlugin();try{const paths=receipts(tmp,root),components=discoverPluginComponents(root),agent=components.find(x=>x.kind==="agent")!,agentPath=paths.find(x=>x.includes("agent-reviewer"))!;writeFileSync(agentPath,JSON.stringify(typed("agent","reviewer",agent.source_sha256,{evaluated_tasks:["review"]},"na",{status:"na",reason:"No delegated agent behavior in this release"})));const result=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:paths});assert.equal(result.status,"pass");assert.equal(result.components["agent:reviewer"].status,"na");assert.equal(result.components["agent:reviewer"].applicable,false);assert.equal(result.components["agent:reviewer"].fresh,true);assert.equal(result.component_summary.na,1);writeFileSync(agentPath,JSON.stringify(typed("agent","reviewer",agent.source_sha256,{evaluated_tasks:["review"]},"na",{status:"na"})));const invalid=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:paths});assert.equal(invalid.gates.components.status,"blocked");assert.match(invalid.gates.components.evidence.join("\n"),/requires a reason/);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("stale hashes and payload omissions block their exact component",()=>{const{tmp,root}=fullPlugin();try{const paths=receipts(tmp,root),hookPath=paths.find(x=>x.includes("hook-goose-hooks"))!;writeFileSync(hookPath,JSON.stringify(typed("hook","goose-hooks","0".repeat(64),{events:["PreToolUse"],safety_cases:[]})));const result=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:paths});assert.equal(result.gates.components.status,"blocked");assert.equal(result.components["hook:goose-hooks"].fresh,false);assert.match(result.gates.components.evidence.join("\n"),/stale source hash/);assert.match(result.gates.components.evidence.join("\n"),/safety_cases/);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("evaluation requires typed integration coverage and handoff evidence for full plugins",()=>{const{tmp,root}=fullPlugin();try{const paths=receipts(tmp,root),workspace=join(tmp,"integration");mkdirSync(workspace);writeFileSync(join(workspace,"review.html"),"reviewed");writeFileSync(join(workspace,"benchmark.json"),JSON.stringify({metadata:{evaluated_source_sha256:sourceHash(root)},run_summary:{without_skill:{pass_rate:{mean:0}},with_skill:{pass_rate:{mean:1}}}}));let result=verifyPlugin({pluginPath:root,profile:"evaluation",componentReceipts:paths,integration:workspace,testsStatus:"pass",humanReview:"pass"});assert.equal(result.gates.integration.status,"blocked");assert.match(result.gates.integration.evidence.join("\n"),/integration receipt|receipt missing/);const keys=discoverPluginComponents(root).map(x=>x.key),integrationPath=join(tmp,"integration-receipt.json");writeFileSync(integrationPath,JSON.stringify(typed("integration","complete",sourceHash(root),{covered_components:keys,scenarios:[{id:"route and enforce",covered_components:keys,handoffs:[{from:"skill:writer",to:"hook:goose-hooks"}]}],handoffs:[{from:"skill:writer",to:"hook:goose-hooks",scenario:"route and enforce",evidence:["trace:1"]}]})));result=verifyPlugin({pluginPath:root,profile:"evaluation",componentReceipts:[...paths,integrationPath],integration:workspace,testsStatus:"pass",humanReview:"pass"});assert.equal(result.gates.integration.status,"pass");assert.deepEqual(result.integration_evidence.covered_components,keys);writeFileSync(integrationPath,JSON.stringify(typed("integration","complete",sourceHash(root),{covered_components:keys.slice(1),scenarios:[{id:"partial",covered_components:keys.slice(1),handoffs:[]}],handoffs:[]})));result=verifyPlugin({pluginPath:root,profile:"evaluation",componentReceipts:[...paths,integrationPath],integration:workspace,testsStatus:"pass",humanReview:"pass"});assert.equal(result.gates.integration.status,"blocked");assert.match(result.gates.integration.evidence.join("\n"),/coverage missing|handoff evidence missing/);}finally{rmSync(tmp,{recursive:true,force:true});}});

test("failed or blocked checks override a claimed top-level pass",()=>{const{tmp,root}=fullPlugin();try{for(const status of ["fail","blocked"]){const paths=receipts(tmp,root),skill=discoverPluginComponents(root).find(x=>x.kind==="skill")!,path=paths.find(x=>x.includes("skill-writer"))!,receipt=typed("skill","writer",skill.source_sha256,{evaluated_behaviors:["write"]});receipt.checks=[{id:"adversarial",status,evidence:["trace"],reason:"deliberate negative"}];writeFileSync(path,JSON.stringify(receipt));const result=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:paths});assert.equal(result.components["skill:writer"].status,status);assert.equal(result.status,status==="fail"?"fail":"blocked");}}finally{rmSync(tmp,{recursive:true,force:true});}});
test("integration rejects unknown keys and undeclared or unlisted handoffs",()=>{const{tmp,root}=fullPlugin();try{const paths=receipts(tmp,root),keys=discoverPluginComponents(root).map(x=>x.key),bad=join(tmp,"integration.json"),base={covered_components:[...keys,"skill:ghost"],scenarios:[{id:"declared",covered_components:keys,handoffs:[]}],handoffs:[{from:"skill:writer",to:"hook:goose-hooks",scenario:"missing",evidence:["trace"]}]};writeFileSync(bad,JSON.stringify(typed("integration","complete",sourceHash(root),base)));const result=verifyPlugin({pluginPath:root,profile:"evaluation",componentReceipts:[...paths,bad],testsStatus:"pass",humanReview:"pass"});assert.equal(result.gates.components.status,"pass");assert.equal(result.gates.integration.status,"blocked");assert.match(result.gates.integration.evidence.join("\n"),/unknown component keys|undeclared scenario/);const unknown=join(tmp,"unknown.json");writeFileSync(unknown,JSON.stringify(typed("agent","ghost","0".repeat(64),{evaluated_tasks:["x"]})));const extra=verifyPlugin({pluginPath:root,profile:"static",componentReceipts:[...paths,unknown]});assert.equal(extra.gates.components.status,"blocked");assert.match(extra.gates.components.evidence.join("\n"),/unknown component receipt key/);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("each integration scenario contains both endpoints of every referenced handoff",()=>{const{tmp,root}=fullPlugin();try{const keys=discoverPluginComponents(root).map(x=>x.key),handoff={from:"skill:writer",to:"hook:goose-hooks"},payload={covered_components:keys,scenarios:[{id:"route",covered_components:[handoff.from,handoff.to],handoffs:[handoff]},{id:"remaining coverage",covered_components:keys.filter(key=>key!==handoff.from&&key!==handoff.to),handoffs:[]}],handoffs:[{...handoff,scenario:"route",evidence:["trace"]}]},receipt=typed("integration","complete",sourceHash(root),payload);let assessment=assessEvidenceReceipt(receipt,"integration",sourceHash(root),keys);assert.equal(assessment.status,"pass");payload.scenarios[0].covered_components=[handoff.from];assessment=assessEvidenceReceipt(receipt,"integration",sourceHash(root),keys);assert.equal(assessment.status,"blocked");assert.match(assessment.problems.join("\n"),/scenario route handoff endpoints outside covered_components: hook:goose-hooks/);}finally{rmSync(tmp,{recursive:true,force:true});}});
test("component freshness includes referenced MCP runtime files but excludes evidence workspace",()=>{const{tmp,root}=fullPlugin();try{let before=discoverPluginComponents(root).find(x=>x.kind==="mcp")!.source_sha256;writeFileSync(join(root,"server.js"),"changed runtime");let after=discoverPluginComponents(root).find(x=>x.kind==="mcp")!.source_sha256;assert.notEqual(after,before);before=after;mkdirSync(join(root,"vendor","node_modules","runtime"),{recursive:true});writeFileSync(join(root,"vendor","node_modules","runtime","index.js"),"shipped dependency");after=discoverPluginComponents(root).find(x=>x.kind==="mcp")!.source_sha256;assert.notEqual(after,before);before=after;mkdirSync(join(root,"evaluations","run"),{recursive:true});writeFileSync(join(root,"evaluations","run","receipt.json"),"generated evidence");after=discoverPluginComponents(root).find(x=>x.kind==="mcp")!.source_sha256;assert.equal(after,before);}finally{rmSync(tmp,{recursive:true,force:true});}});
