import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {spawnSync} from "node:child_process";
import {fileURLToPath} from "node:url";
import {computeGoldenMetrics,evaluateGoldenCandidate,inspectGoldenEvidence,listGoldenJourneys,runGoldenJourney,verifyGoldenArchive} from "../dist/scripts/golden_journeys.js";
const ROOT=join(fileURLToPath(new URL(".",import.meta.url)),".."),CLI=join(ROOT,"dist/scripts/cli.js");

test("three immutable natural-language golden journeys",()=>{const all=listGoldenJourneys();assert.equal(all.length,3);for(const f of all){assert.ok(f.natural_language_request.length>40);assert.ok(f.thresholds.repetitions>=5);assert.ok(f.scenario_suite.length>=3)}});

test("candidate policies, independent challenges, change records, and intervention-derived metrics",async()=>{for(const f of listGoldenJourneys()){const w=mkdtempSync(join(tmpdir(),"golden-"));try{const s:any=await runGoldenJourney({journey:f.id,workspace:w,now:new Date("2026-01-01T00:00:00Z")});assert.equal(s.status,"pending-production-approval");assert.equal(s.activation.allowed,false);assert.ok(s.validation.revised.valid,JSON.stringify(s.validation));assert.ok(s.records.every((r:any)=>r.executed&&r.duration_ms>0&&r.fixture&&r.input_fingerprint));assert.equal(new Set(s.records.map((r:any)=>r.input_fingerprint)).size,s.records.length);assert.equal(s.review.challenge.branches.length,Number(s.configuration.challenge_branches));for(const b of s.review.challenge.branches){assert.equal(b.independent,true);assert.equal(b.inspection.candidate_path,join(w,s.candidate.initial_relative_path));assert.ok(b.inspection.records_sha256);assert.ok(b.inspection.criteria_sha256);assert.match(b.content,new RegExp(b.capability))}assert.equal(s.review.improvement.changes.length,s.review.challenge.branches.length);for(const change of s.review.improvement.changes){assert.ok(change.content);assert.equal(change.operation,"enable-capability");const verified=s.review.improvement.verification.find((v:any)=>v.finding_id===change.finding_id);assert.equal(verified.changed,true);assert.equal(verified.behavior_passed,true)}const count=(records:any[])=>records.flatMap((r:any)=>r.metric_events).filter((e:any)=>e.kind==="manual-fallback").reduce((n:number,e:any)=>n+e.count,0),baseInterventions=count(s.baseline_records),currentInterventions=count(s.records);assert.ok(s.records.every((r:any)=>!("manual_interventions" in r)&&r.metric_events.every((e:any)=>e.source==="evaluator"&&Number.isFinite(e.count)&&e.count>=0)));assert.equal(s.metrics.productivity,(baseInterventions-currentInterventions)/baseInterventions);assert.equal(s.metrics.inputs.interventions_saved,baseInterventions-currentInterventions);assert.equal(s.metrics.inputs.intervention_source,"evaluator-owned metric_events");assert.match(s.metrics.inputs.duration_claim,/no speed improvement/);assert.equal(s.metrics.thresholds_met,true);assert.equal(verifyGoldenArchive(w).valid,true);assert.equal(inspectGoldenEvidence(w,new Date("2026-01-03T00:00:00Z"),1000).status,"stale")}finally{rmSync(w,{recursive:true,force:true})}}});

test("candidate -100 and NaN metric corruption cannot affect evaluator-owned productivity or thresholds",async()=>{const w=mkdtempSync(join(tmpdir(),"golden-corrupt-"));try{const s:any=await runGoldenJourney({journey:"dependency-review-agent",workspace:w});const root=join(w,s.candidate.relative_path),policy=join(root,"behavior-policy.mjs"),clean=readFileSync(policy,"utf8");assert.doesNotMatch(clean,/manual_interventions|actions:/);writeFileSync(policy,clean.replaceAll("return {","return {manual_interventions:-100,actions:Number.NaN,"));const records:any[]=await evaluateGoldenCandidate("dependency-review-agent",root,join(w,"corrupt"),Number(s.configuration.repetitions));assert.ok(records.every((r:any)=>r.passed&&!("manual_interventions" in r)&&!("actions" in r)));const metrics:any=computeGoldenMetrics(records,s.baseline_records,Number(s.configuration.repetitions));metrics.thresholds_met=metrics.repetitions.completed>=s.metrics.repetitions.required&&metrics.effectiveness>=0.8&&metrics.productivity>=0.2&&metrics.outcome_success>=0.75;assert.equal(metrics.productivity,s.metrics.productivity);assert.equal(metrics.thresholds_met,s.metrics.thresholds_met);const invalid=structuredClone(records);invalid[0].metric_events=[{source:"evaluator",kind:"manual-fallback",count:-100}];assert.throws(()=>computeGoldenMetrics(invalid,s.baseline_records,Number(s.configuration.repetitions)),/finite and nonnegative/);invalid[0].metric_events[0].count=Number.NaN;assert.throws(()=>computeGoldenMetrics(invalid,s.baseline_records,Number(s.configuration.repetitions)),/finite and nonnegative/)}finally{rmSync(w,{recursive:true,force:true})}});

test("actual timer heartbeats accompany active children; cancellation checkpoints and resume skips completed work",async()=>{const w=mkdtempSync(join(tmpdir(),"golden-cancel-"));try{const controller=new AbortController(),checkpoint=join(w,"repetition-checkpoint.json"),timer=setInterval(()=>{try{const value=JSON.parse(readFileSync(checkpoint,"utf8"));if(value.phase==="improvement"&&value.revised_records?.length)controller.abort()}catch{}},2);const cancelled:any=await runGoldenJourney({journey:"dependency-review-agent",workspace:w,profile:"expert",overrides:{repetitions:20,challenge_branches:5},signal:controller.signal,heartbeatMs:2});clearInterval(timer);assert.equal(cancelled.status,"cancelled");assert.equal(cancelled.checkpoint.phase,"improvement");assert.ok(cancelled.checkpoint.revised_records.length>0);assert.ok(cancelled.heartbeats.some((h:any)=>h.status==="running"&&h.phase==="evaluation"));assert.ok(cancelled.checkpoint.remaining_repetitions>=0);const baselineBefore=cancelled.checkpoint.baseline_records.length,initialBefore=cancelled.checkpoint.initial_records.length,revisedBefore=cancelled.checkpoint.revised_records.length;const resumed:any=await runGoldenJourney({journey:"dependency-review-agent",workspace:w,profile:"expert",overrides:{repetitions:20,challenge_branches:5},resume:true,heartbeatMs:2});assert.equal(resumed.metrics.repetitions.completed,20);assert.equal(resumed.review.challenge.branches.length,5);assert.ok(resumed.baseline_records.length>=baselineBefore);assert.ok(resumed.records.length>=revisedBefore);assert.equal(new Set(resumed.records.map((r:any)=>`${r.repetition}:${r.scenario_id}`)).size,resumed.records.length);assert.equal(new Set(resumed.baseline_records.map((r:any)=>`${r.repetition}:${r.scenario_id}`)).size,resumed.baseline_records.length);assert.equal(verifyGoldenArchive(w).valid,true)}finally{rmSync(w,{recursive:true,force:true})}});

test("implementation has no fixed productivity delay and archive rejects transitive tampering",async()=>{const source=readFileSync(join(ROOT,"scripts/golden_journeys.ts"),"utf8")+readFileSync(join(ROOT,"scripts/golden_behavior_runner.ts"),"utf8");assert.doesNotMatch(source,/Atomics\.wait|setTimeout\s*\(/);const w=mkdtempSync(join(tmpdir(),"golden-tamper-"));try{const s:any=await runGoldenJourney({journey:"idea-api-review-skill",workspace:w});const record=join(w,"ci-archive/records.json");writeFileSync(record,readFileSync(record,"utf8")+" ");assert.equal(verifyGoldenArchive(w).valid,false);writeFileSync(record,JSON.stringify(s.records,null,2)+"\n");const candidate=join(w,s.candidate.relative_path,"skills/api-review/SKILL.md");writeFileSync(candidate,readFileSync(candidate,"utf8")+"\ntamper\n");assert.equal(inspectGoldenEvidence(w).status,"invalid");await assert.rejects(()=>runGoldenJourney({journey:"idea-api-review-skill",workspace:w,resume:true}),/resume rejected/)}finally{rmSync(w,{recursive:true,force:true})}});

test("CLI executes asynchronously but exits pending approval",()=>{const w=mkdtempSync(join(tmpdir(),"golden-cli-"));try{const r=spawnSync(process.execPath,[CLI,"golden-e2e","--journey","idea-api-review-skill","--workspace",w,"--format","json"],{encoding:"utf8"});assert.equal(r.status,4,r.stderr);const s=JSON.parse(r.stdout);assert.equal(s.activation.allowed,false);assert.ok(s.phases.every((p:any)=>p.evidence.executed&&!p.evidence.llm_executed))}finally{rmSync(w,{recursive:true,force:true})}});
