import { test } from "node:test";
import assert from "node:assert/strict";
import { runIndependentReview, type BranchHost, type BranchRequest, type PublicBranchOutput, type ReviewConfig } from "../dist/scripts/independent_review.js";

const config=():ReviewConfig=>({runId:"review-1",task:"review proposal",approvedContext:{evidence:[{id:"ev-1",content:"observed"}],contracts:[{id:"contract-1",content:"must work"}],scenarios:[{id:"scenario-1",content:"offline"}]},criteria:[{id:"criterion-1",text:"evidence based"}],matrix:{builders:1,domainChallengers:1,uxChallengers:1,evaluationChallengers:1,verifiers:1,maxConcurrency:2,branchBudgetMs:1000,totalBudgetMs:5000}});
const output=(request:BranchRequest):PublicBranchOutput=>({summary:request.role,claims:[{id:request.branchId+"-claim",subject:"readiness",statement:request.role==="ux-challenger"?"not ready":"ready",position:request.role==="ux-challenger"?"oppose":"support",evidenceIds:request.role==="evaluation-challenger"?[]:["ev-1"],criterionIds:["criterion-1"],risk:request.role==="domain-challenger"?"domain ambiguity":undefined}],proposedChanges:[{id:request.branchId+"-change",description:"tighten behavior",evidenceIds:["ev-1"],contractIds:["contract-1"],scenarioIds:["scenario-1"]}]});

test("isolates roles, freezes approved inputs, and never leaks private builder reasoning",async()=>{const requests:BranchRequest[]=[];let active=0,max=0;const host:BranchHost={async run(request){requests.push(request);active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;assert.ok(Object.isFrozen(request.approvedContext));assert.ok(Object.isFrozen(request.frozenCriteria));if(request.role!=="verifier")assert.equal(request.peerOutputs,undefined);else{assert.equal(request.peerOutputs?.length,4);assert.ok(!JSON.stringify(request).includes("SECRET_CHAIN"));}return{publicOutput:output(request),privateReasoning:"SECRET_CHAIN"}}};const result=await runIndependentReview(config(),host);assert.equal(result.branches.length,5);assert.equal(max,2);assert.equal(result.failuresIsolated,true);assert.equal((result.branches.find(x=>x.role==="builder")!.rawOutput as any).privateReasoning,"SECRET_CHAIN");assert.equal(result.convergence.autoResolved,false);assert.ok(result.convergence.agreements.length);assert.ok(result.convergence.contradictions.length);assert.ok(result.convergence.missingEvidence.some(x=>x.branchId.startsWith("evaluation")));assert.ok(result.convergence.risks.some(x=>x.statement==="domain ambiguity"));});

test("isolates failure and rejects adversarial provenance or unlinked changes",async()=>{const host:BranchHost={async run(request){if(request.role==="domain-challenger")throw new Error("host failure");const value=output(request);if(request.role==="ux-challenger")value.claims[0].evidenceIds=["private-builder-evidence"];if(request.role==="evaluation-challenger")value.proposedChanges[0]={id:"bad",description:"unlinked",evidenceIds:["ev-1"]};return{publicOutput:value}}};const result=await runIndependentReview(config(),host);assert.equal(result.branches.filter(x=>x.status==="failed").length,3);assert.equal(result.branches.find(x=>x.role==="builder")?.status,"succeeded");assert.equal(result.branches.find(x=>x.role==="verifier")?.status,"succeeded");assert.match(result.branches.find(x=>x.role==="ux-challenger")!.error!,/unapproved evidence/);assert.match(result.branches.find(x=>x.role==="evaluation-challenger")!.error!,/must link evidence/);});

test("enforces per-branch budget and preserves timeout provenance",async()=>{const c=config();c.matrix={...c.matrix,domainChallengers:0,uxChallengers:0,evaluationChallengers:0,branchBudgetMs:15,totalBudgetMs:100};const host:BranchHost={run(request,signal){if(request.role==="builder")return new Promise((_resolve,reject)=>signal.addEventListener("abort",()=>reject(new Error("aborted")),{once:true}));return Promise.resolve({publicOutput:output(request)})}};const result=await runIndependentReview(c,host);assert.equal(result.branches.find(x=>x.role==="builder")?.status,"timed-out");assert.equal(result.branches.find(x=>x.role==="verifier")?.status,"succeeded");});

import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

test("CLI drives a fake branch host and sends verifier only public outputs",()=>{const dir=mkdtempSync(join(tmpdir(),"independent-review-")),configPath=join(dir,"config.json"),hostPath=join(dir,"host.mjs");writeFileSync(configPath,JSON.stringify(config()));writeFileSync(hostPath,`let text="";for await(const chunk of process.stdin)text+=chunk;const r=JSON.parse(text);if(r.role==="verifier"&&JSON.stringify(r).includes("PRIVATE_BUILDER_CHAIN"))process.exit(9);if(r.role!=="verifier"&&r.peerOutputs)process.exit(8);process.stdout.write(JSON.stringify({privateReasoning:"PRIVATE_BUILDER_CHAIN",publicOutput:{summary:r.role,claims:[{id:r.branchId+"-claim",subject:"safe",statement:"yes",position:"support",evidenceIds:["ev-1"],criterionIds:["criterion-1"]}],proposedChanges:[{id:r.branchId+"-change",description:"change",evidenceIds:["ev-1"],scenarioIds:["scenario-1"]}]}}));`);const cli=resolve("dist/scripts/cli.js"),run=spawnSync(process.execPath,[cli,"independent-review","--config",configPath,"--host",process.execPath,"--host-arg",hostPath,"--format","json"],{encoding:"utf8"});assert.equal(run.status,0,run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.branches.length,5);assert.equal(result.convergence.autoResolved,false);assert.equal(result.branches.find((x:any)=>x.role==="builder").rawOutput.privateReasoning,"PRIVATE_BUILDER_CHAIN");});
