import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { componentHash, verifyPlugin } from "../dist/scripts/verify_plugin_gates.js";
import { sourceHash } from "../dist/scripts/package_manifest.js";
const ROOT=resolve(join(fileURLToPath(new URL(".",import.meta.url)),"..")),CLI=join(ROOT,"dist","scripts","cli.js"),DIST=join(ROOT,"dist","scripts");
const producer=(name:string)=>JSON.parse(readFileSync(join(ROOT,"tests","fixtures","benchmarks",name),"utf8"));
function setup(name:"skill-benchmark.json"|"agent-benchmark.json") {
 const tmp=mkdtempSync(join(tmpdir(),"plugin-eff-path-")),plugin=join(tmp,"plugin"),skill=join(plugin,"skills","demo"),ws=join(plugin,"evaluations","work"),integration=join(ws,"integration"),receipt=join(ws,"components","demo","receipt.json"),archive=join(ws,"plugin.zip");
 mkdirSync(skill,{recursive:true});mkdirSync(integration,{recursive:true});mkdirSync(join(receipt,".."),{recursive:true});
 writeFileSync(join(plugin,"plugin.json"),JSON.stringify({$schema:"https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",name:"efficiency-plugin",version:"1.0.0",description:"Efficiency fixture plugin"}));
 writeFileSync(join(skill,"SKILL.md"),["---","name: demo","description: Handles demo work.","---","","# Demo",""].join("\n"));
 writeFileSync(receipt,JSON.stringify({schema_version:"1.0",artifact:"skill",name:"demo",status:"pass",source_sha256:componentHash(skill)}));
 const benchmark=producer(name);benchmark.metadata={...(benchmark.metadata??{}),evaluated_source_sha256:sourceHash(plugin)};writeFileSync(join(integration,"benchmark.json"),JSON.stringify(benchmark));writeFileSync(join(integration,"review.html"),"reviewed");return{tmp,plugin,ws,integration,receipt,archive};
}
test("real Skill producer fixture passes verifyPlugin release and CLI verify paths",()=>{const f=setup("skill-benchmark.json");try{execFileSync(process.execPath,[join(DIST,"package_goose_plugin.js"),f.plugin,f.archive]);const options={pluginPath:f.plugin,profile:"release" as const,componentReceipts:[f.receipt],integration:f.integration,archive:f.archive,testsStatus:"pass",humanReview:"pass",maxEfficiencyRegressions:{p50_wall_latency_ms:1000,p95_wall_latency_ms:1180,"tokens.total":8},missingEfficiencyTelemetry:"block" as const};const direct=verifyPlugin(options);assert.equal(direct.status,"pass");assert.equal(direct.efficiency.dimensions.p50_wall_latency_ms.current,2000);const cli=spawnSync(process.execPath,[CLI,"verify",f.plugin,"--profile","release","--component-receipt",f.receipt,"--integration",f.integration,"--archive",f.archive,"--tests-status","pass","--human-review","pass","--max-p50-wall-latency-regression-ms","1000","--max-p95-wall-latency-regression-ms","1180","--max-total-token-regression","8","--missing-efficiency-telemetry","block","--format","json"],{encoding:"utf8"});assert.equal(cli.status,0,cli.stderr);assert.equal(JSON.parse(cli.stdout).efficiency.dimensions["tokens.total"].paired_delta,8)}finally{rmSync(f.tmp,{recursive:true,force:true})}});
test("real Agent producer fixture passes verifyPlugin, full-eval, and CLI paths with percentile and scalar gates",()=>{const f=setup("agent-benchmark.json");try{execFileSync(process.execPath,[join(DIST,"package_goose_plugin.js"),f.plugin,f.archive]);const options={pluginPath:f.plugin,profile:"release" as const,componentReceipts:[f.receipt],integration:f.integration,archive:f.archive,testsStatus:"pass",humanReview:"pass",maxEfficiencyRegressions:{p50_wall_latency_ms:1000,p95_wall_latency_ms:1400,actual_turns:1,"tokens.total":10,cost:.01},missingEfficiencyTelemetry:"block" as const};const direct=verifyPlugin(options);assert.equal(direct.status,"pass");assert.equal(direct.efficiency.dimensions.p95_wall_latency_ms.current,2900);const verify=spawnSync(process.execPath,[CLI,"verify",f.plugin,"--profile","release","--component-receipt",f.receipt,"--integration",f.integration,"--archive",f.archive,"--tests-status","pass","--human-review","pass","--max-p50-wall-latency-regression-ms","1000","--max-p95-wall-latency-regression-ms","1400","--max-turn-regression","1","--max-total-token-regression","10","--max-cost-regression","0.01","--missing-efficiency-telemetry","block","--format","json"],{encoding:"utf8"});assert.equal(verify.status,0,verify.stdout+verify.stderr);assert.equal(JSON.parse(verify.stdout).efficiency.dimensions.p95_wall_latency_ms.paired_delta,1400);rmSync(f.archive,{force:true});const run=spawnSync(process.execPath,[CLI,"full-eval",f.plugin,"--workspace",f.ws,"--component-receipt",f.receipt,"--integration",f.integration,"--archive",f.archive,"--tests-status","pass","--human-review","pass","--max-p50-wall-latency-regression-ms","1000","--max-p95-wall-latency-regression-ms","1400","--max-turn-regression","1","--max-total-token-regression","10","--max-cost-regression","0.01","--missing-efficiency-telemetry","block","--format","json"],{encoding:"utf8"});assert.equal(run.status,0,run.stdout+run.stderr);const result=JSON.parse(run.stdout);assert.equal(result.status,"success");assert.equal(result.verification.efficiency.dimensions.p95_wall_latency_ms.current,2900);assert.equal(result.verification.efficiency.dimensions.p50_wall_latency_ms.paired_delta,1000)}finally{rmSync(f.tmp,{recursive:true,force:true})}});
