import test from "node:test";
import assert from "node:assert/strict";
import {LiveBudget,aggregateTelemetry,budgetSnapshot,normalizeRunTelemetry} from "../dist/scripts/usage_budget.js";
const t=(over:any={})=>normalizeRunTelemetry({run_id:over.run_id??"r",actual_turns:over.turns??2,wall_time_ms:over.wall??10,tokens:{input:over.input??3,output:over.output??4,cached:over.cached??1,reasoning:over.reasoning??2,total:over.tokens??10},cost:over.cost===undefined?0.2:over.cost,currency:"USD"});
test("actual runs, turns, wall time, token categories, and nullable cost aggregate",()=>{const a=aggregateTelemetry([t(),t({run_id:"r2",turns:3,wall:15,input:4,output:5,cached:2,reasoning:3,tokens:14,cost:null})]);assert.equal(a.runs,2);assert.equal(a.turns,5);assert.equal(a.wall_time_ms,25);assert.deepEqual(a.tokens,{input:7,output:9,cached:3,reasoning:5,total:24});assert.equal(a.cost,null);assert.equal(a.availability.cost,"unavailable");assert.equal(a.coverage.cost,1)});
for(const [name,caps,record,reason] of [
 ["runs",{max_runs:1},t(),"runs"],["turns",{max_turns:2},t(),"turns"],["wall",{max_wall_time_ms:10},t(),"wall-time"],["tokens",{max_tokens:10},t(),"tokens.total"],["token category",{max_tokens:{reasoning:2}},t(),"tokens.reasoning"],["cost",{max_cost:.2},t(),"cost"]
] as const)test("live cap: "+name,()=>{const b=new LiveBudget(caps);assert.equal(b.canStart().allowed,true);const s=b.add(record);assert.equal(s.exhausted,true);assert.equal(s.stop_reason,"aggregate-budget-exhausted:"+reason);assert.equal(b.canStart().allowed,false)});
test("planned is distinct from consumed and resume cannot exceed persisted consumption",()=>{const prior=[t({turns:3})],b=new LiveBudget({max_turns:3},prior),s=b.snapshot();assert.equal(s.planned.max_turns,3);assert.equal(s.consumed.turns,3);assert.equal(s.remaining.turns,0);assert.equal(b.canStart().allowed,false)});
test("missing telemetry blocks a configured cap by default and allow policy records availability",()=>{const missing=normalizeRunTelemetry({run_id:"missing"});let s=budgetSnapshot({max_turns:4},[missing]);assert.equal(s.stop_reason,"telemetry-unavailable:turns");assert.equal(s.availability.turns,"unavailable");s=budgetSnapshot({max_turns:4,missing_telemetry:"allow"},[missing]);assert.equal(s.exhausted,false);assert.equal(s.remaining.turns,null)});
