import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { appendFileSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ExecutionLease, atomicCheckpoint, beginAttempt, cancellationDecision, chargeBudget, cleanupCheckpointPartials, elapsedBudgetMs, finishAttempt, mayRetry, newReliabilityLedger, normalizePlan, processAlive, readLease, remainingBudgetMs, repairInterruptedJsonl, retryBackoffMs } from "../dist/scripts/execution_reliability.js";

test("retry policy is bounded and total budget survives ledger updates",()=>{const plan=normalizePlan({max_attempts:3,backoff_ms:10,max_backoff_ms:15,total_budget_ms:30});assert.equal(retryBackoffMs(1,plan),10);assert.equal(retryBackoffMs(2,plan),15);assert.deepEqual(mayRetry({attempts:1,retryable:false,consumed_ms:0},plan).reason,"nonretryable");assert.equal(mayRetry({attempts:3,retryable:true,consumed_ms:0},plan).reason,"retry-limit-exhausted");let ledger=newReliabilityLedger(0);ledger=chargeBudget(ledger,25,plan);assert.equal(mayRetry({attempts:1,retryable:true,consumed_ms:ledger.consumed_ms},plan).reason,"total-budget-exhausted")});
test("logical job attempts receive distinct stable records",()=>{let records=beginAttempt([],0);records=finishAttempt(records,"failed",{retryable:true,now:5});records=beginAttempt(records,10);assert.equal(records[0].number,1);assert.equal(records[1].number,2);assert.notEqual(records[0].attempt_id,records[1].attempt_id)});
test("lease heartbeats and stale owners are recovered",()=>{const dir=mkdtempSync(join(tmpdir(),"lease-")),path=join(dir,"run.lease"),plan=normalizePlan({lease_ms:20,heartbeat_ms:5,stale_after_ms:25});try{const lease=ExecutionLease.acquire(path,plan);lease.heartbeat();assert.equal(existsSync(path),true);lease.release();assert.equal(existsSync(path),false)}finally{rmSync(dir,{recursive:true,force:true})}});
test("fault-injected partial checkpoint never replaces valid evidence",()=>{const dir=mkdtempSync(join(tmpdir(),"checkpoint-")),path=join(dir,"state.json");try{atomicCheckpoint(path,{revision:1,completed:["a"]});assert.throws(()=>atomicCheckpoint(path,{revision:2,completed:["a","b"]},point=>{if(point==="checkpoint-partial-write")throw new Error("crash")}),/crash/);assert.deepEqual(JSON.parse(readFileSync(path,"utf8")),{revision:1,completed:["a"]});cleanupCheckpointPartials(path);assert.equal(existsSync(path+".tmp"),false)}finally{rmSync(dir,{recursive:true,force:true})}});
test("hard process crash leaves the last atomic checkpoint recoverable",()=>{const dir=mkdtempSync(join(tmpdir(),"crash-")),path=join(dir,"state.json"),module=new URL("../dist/scripts/execution_reliability.js",import.meta.url).href;try{atomicCheckpoint(path,{revision:1,completed:["validation"]});const code=`import {atomicCheckpoint} from ${JSON.stringify(module)};atomicCheckpoint(process.argv[1],{revision:2,completed:["validation","planning"]});`;const child=spawnSync(process.execPath,["--input-type=module","-e",code,path],{env:{...process.env,PLUGIN_CREATOR_FAULT_INJECTION:"process-crash:checkpoint-partial-write"}});assert.notEqual(child.status,0);assert.deepEqual(JSON.parse(readFileSync(path,"utf8")),{revision:1,completed:["validation"]});cleanupCheckpointPartials(path)}finally{rmSync(dir,{recursive:true,force:true})}});
test("interrupted event writes repair only their partial tail",()=>{const dir=mkdtempSync(join(tmpdir(),"events-")),path=join(dir,"events.jsonl");try{atomicCheckpoint(path,{complete:true});const original=readFileSync(path,"utf8");appendFileSync(path,'{"partial"');assert.equal(repairInterruptedJsonl(path),true);assert.equal(readFileSync(path,"utf8"),original)}finally{rmSync(dir,{recursive:true,force:true})}});
test("cancellation honors cooperative completion then forced grace",()=>{assert.equal(cancellationDecision(0,1,10,true),"cooperative");assert.equal(cancellationDecision(0,5,10,false),"wait");assert.equal(cancellationDecision(0,10,10,false),"forced")});


test("lease takeover immediately recovers a dead fresh owner",()=>{const dir=mkdtempSync(join(tmpdir(),"lease-owner-")),path=join(dir,"run.lease"),plan=normalizePlan({lease_ms:5,heartbeat_ms:1,stale_after_ms:5});try{const fresh=new Date().toISOString(),future=new Date(Date.now()+60_000).toISOString();writeFileSync(path,JSON.stringify({schema_version:"1.1",owner:"dead",generation:1,fencing_token:"dead-token",pid:999999999,process_group_id:999999999,acquired_at:fresh,heartbeat_at:fresh,expires_at:future}));const started=Date.now(),recovered=ExecutionLease.acquire(path,plan);assert.notEqual(readLease(path)?.owner,"dead");assert.ok(Date.now()-started<100,"dead PID must be reclaimed without waiting for freshness expiry");recovered.release()}finally{rmSync(dir,{recursive:true,force:true})}});
test("takeover generation fences the stale owner from checkpointing",async()=>{const dir=mkdtempSync(join(tmpdir(),"lease-fence-")),path=join(dir,"run.lease"),plan=normalizePlan({lease_ms:10,heartbeat_ms:2,stale_after_ms:12});try{const stale=ExecutionLease.acquire(path,plan);await new Promise(r=>setTimeout(r,20));const current=ExecutionLease.acquire(path,plan),record=readLease(path);assert.ok(record!.generation>stale.generation);let wrote=false;assert.throws(()=>stale.checkpoint(()=>{wrote=true}),/fenced/);assert.equal(wrote,false);assert.throws(()=>stale.heartbeat(),/fenced/);current.checkpoint(()=>{wrote=true});assert.equal(wrote,true);stale.release();assert.equal(readLease(path)?.owner,current.owner);current.release()}finally{rmSync(dir,{recursive:true,force:true})}});
test("expired frozen live owner is fenced, reclaimed, and terminated",async()=>{if(process.platform==="win32")return;const dir=mkdtempSync(join(tmpdir(),"lease-frozen-")),path=join(dir,"run.lease"),ready=join(dir,"ready"),module=new URL("../dist/scripts/execution_reliability.js",import.meta.url).href,plan={lease_ms:40,heartbeat_ms:10,stale_after_ms:60,cancellation_grace_ms:20};const code=`import {ExecutionLease} from ${JSON.stringify(module)};import {writeFileSync} from "node:fs";const lease=ExecutionLease.acquire(process.argv[1],${JSON.stringify(plan)});writeFileSync(process.argv[2],String(process.pid));lease.startHeartbeat();setInterval(()=>{},1000);`;const child=spawn(process.execPath,["--input-type=module","-e",code,path,ready],{detached:true,stdio:"ignore"});try{for(let i=0;i<100&&!existsSync(ready);i++)await new Promise(r=>setTimeout(r,10));assert.equal(existsSync(ready),true);process.kill(child.pid!,"SIGSTOP");await new Promise(r=>setTimeout(r,80));const recovered=ExecutionLease.acquire(path,normalizePlan(plan));assert.notEqual(readLease(path)?.pid,child.pid);assert.equal(processAlive(child.pid!),false);recovered.release()}finally{try{process.kill(-child.pid!,"SIGKILL")}catch{}rmSync(dir,{recursive:true,force:true})}});
test("concurrent dead-mutex cleanup preserves each successor lock",async()=>{if(process.platform==="win32")return;const dir=mkdtempSync(join(tmpdir(),"lease-mutex-")),path=join(dir,"run.lease"),ready=join(dir,"ready"),log=join(dir,"owners"),module=new URL("../dist/scripts/execution_reliability.js",import.meta.url).href,plan={lease_ms:40,heartbeat_ms:10,stale_after_ms:60,cancellation_grace_ms:20};const holderCode=`import {ExecutionLease} from ${JSON.stringify(module)};import {writeFileSync} from "node:fs";const lease=ExecutionLease.acquire(process.argv[1],${JSON.stringify(plan)});lease.checkpoint(()=>{writeFileSync(process.argv[2],String(process.pid));Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0)});`,contenderCode=`import {ExecutionLease} from ${JSON.stringify(module)};import {appendFileSync} from "node:fs";const lease=ExecutionLease.acquire(process.argv[1],${JSON.stringify(plan)});lease.checkpoint(()=>appendFileSync(process.argv[2],lease.owner+"\\n"));lease.release();`;const holder=spawn(process.execPath,["--input-type=module","-e",holderCode,path,ready],{stdio:"ignore"});try{for(let i=0;i<100&&!existsSync(ready);i++)await new Promise(r=>setTimeout(r,10));assert.equal(existsSync(ready),true);holder.kill("SIGKILL");await new Promise<void>(resolve=>holder.once("exit",()=>resolve()));const contenders=Array.from({length:4},()=>spawn(process.execPath,["--input-type=module","-e",contenderCode,path,log],{stdio:"ignore"}));const exits=await Promise.all(contenders.map(child=>new Promise<number|null>(resolve=>child.once("exit",code=>resolve(code)))));assert.deepEqual(exits,[0,0,0,0]);const owners=readFileSync(log,"utf8").trim().split("\n");assert.equal(new Set(owners).size,4);assert.equal(existsSync(path+".mutex"),false)}finally{try{holder.kill("SIGKILL")}catch{}rmSync(dir,{recursive:true,force:true})}});
test("wall clock budget includes orchestration and wait time",()=>{const ledger=newReliabilityLedger(100);assert.equal(elapsedBudgetMs(ledger,130),30);const plan=normalizePlan({total_budget_ms:40});assert.equal(remainingBudgetMs(ledger,plan,130),10);assert.equal(mayRetry({attempts:1,retryable:true,consumed_ms:0,remaining_ms:10},normalizePlan({...plan,backoff_ms:10})).reason,"total-budget-exhausted")});
