import test from "node:test";import assert from "node:assert/strict";import{createHash}from"node:crypto";import{mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join,resolve}from"node:path";import{spawnSync}from"node:child_process";import{analyzeDecisionResearch,protocolIdentity,validateDecisionResearch}from"../dist/scripts/decision_comprehension.js";
const ROOT=resolve(import.meta.dirname,".."),SKILL_ROOT=resolve(ROOT,"../../skills/plugin-creator"),CLI=join(ROOT,"dist/scripts/cli.js");
function input(synthetic=false){const task=(id:string,journey:string,expected:string)=>({task_id:id,journey,completed_unassisted:true,time_to_first_candidate_seconds:60,facilitator_interventions:0,selected_decision:expected,expected_decision:expected,decision_confidence:4,missing_evidence_identified:["source provenance"],highest_regression_time_seconds:journey==="evaluation-regression-report"?30:null,highest_regression_accurate:journey==="evaluation-regression-report"?true:null});return{schema_version:"1.0",study:{anonymous:true,direct_identifiers_collected:false,protocol:{...protocolIdentity}},sessions:Array.from({length:8},(_,i)=>({session_id:"anon-session-"+i,cohort:i%2?"developer":"nonexpert",synthetic,consent:{informed:true,recorded:true,withdrawal_explained:true,consented_at:"2026-09-18T12:00:00Z"},retention:{policy_version:"research-v1",delete_after:"2026-12-17"},facilitator:{script_version:"1.0.0",neutral_prompts_only:true},tasks:[task("validation-invalid","validation-report","validation-failure"),task("evaluation-regression","evaluation-regression-report","evaluation-failure"),task(i%2?"release-blocked":"release-approval","release-decision-report",i%2?"blocked":"approval-required")],findings:[]}))}}
const errors=(x:unknown)=>validateDecisionResearch(x).errors.join("\n");
test("passes governed thresholds and reports candidate time separately",()=>{const r:any=analyzeDecisionResearch(input());assert.equal(r.status,"pass");assert.equal(r.metrics.median_highest_severity_regression_seconds,30);assert.equal(r.metrics.median_time_to_first_candidate_seconds,60);assert.deepEqual(Object.keys(r.coverage.expected_decision_categories),["validation-failure","evaluation-failure","blocked","approval-required"]);assert.equal(r.commands_executed,false)});
test("inspects entries even below eight and rejects direct identifier content",()=>{const v:any=input();v.sessions=v.sessions.slice(0,7);v.sessions[0].email="person@example.test";v.sessions[0].consent.recorded=false;const e=errors(v);assert.match(e,/at least 8/);assert.match(e,/direct identifier/);assert.match(e,/email is prohibited/);assert.match(e,/consent.recorded/)});
test("privacy scan covers all strings, duplicate IDs, dates, names orgs URLs IPs paths",()=>{for(const [label,text] of [["email","alice@example.test"],["URL","https://example.test/a"],["IP","192.168.1.42"],["name","Dr Alice Smith"],["organization","Example University"],["path","/home/alice/private"]]){const v:any=input();v.sessions[1].session_id=v.sessions[0].session_id;v.sessions[0].tasks[0].missing_evidence_identified=[text];const e=errors(v);assert.match(e,/duplicate session ID/);assert.match(e,/prohibited/,label)}const late:any=input();late.sessions[0].retention.delete_after="2026-12-18";assert.match(errors(late),/more than 90/);const future:any=input();future.sessions[0].consent.consented_at="2999-01-01T00:00:00Z";assert.match(errors(future),/future/)});
test("protocol identity uses exact shipped bytes without an inline duplicate",()=>{const bytes=readFileSync(join(SKILL_ROOT,"assets/decision-comprehension/protocol.json"));assert.equal(protocolIdentity.sha256,createHash("sha256").update(bytes).digest("hex"));assert.equal(protocolIdentity.version,JSON.parse(bytes.toString("utf8")).version);assert.doesNotMatch(readFileSync(join(ROOT,"scripts/decision_comprehension.ts"),"utf8"),/const protocolData=/)});
test("all-string privacy scan rejects expanded PII classes exactly",()=>{for(const [label,text] of [["untitled name","Alice Smith"],["international phone","+44 20 7946 0958"],["street address","123 Main Street"],["handle","contact @alice_dev"],["employer","works at Acme Labs"],["organization","Acme GmbH"],["IPv6","2001:db8:85a3::8a2e:370:7334"],["email","alice@example.test"],["URL","www.example.test/profile"],["home",String.raw`C:\Users\alice\notes.txt`]]){const v:any=input();v.sessions[0].tasks[0].missing_evidence_identified=[text];assert.match(errors(v),/prohibited/,label)}});
test("completed_unassisted requires zero interventions and completion uses both fields",()=>{const invalid:any=input();invalid.sessions[0].tasks[0].facilitator_interventions=1;assert.match(errors(invalid),/cannot be true when facilitator_interventions is nonzero/);const valid:any=input();for(const s of valid.sessions)for(const t of s.tasks)t.completed_unassisted=false;valid.sessions[0].tasks[0].completed_unassisted=true;const r:any=analyzeDecisionResearch(valid);assert.equal(r.metrics.unassisted_completion_rate,1/24)});
test("canonical protocol and task decisions prevent expected-decision gaming",()=>{for(const mutate of [(v:any)=>v.study.protocol.sha256="0".repeat(64),(v:any)=>v.sessions[0].facilitator.script_version="9.9.9",(v:any)=>v.sessions[0].tasks[0].task_id="release-blocked",(v:any)=>v.sessions[0].tasks[0].expected_decision="blocked"]){const v:any=input();mutate(v);assert.equal(validateDecisionResearch(v).valid,false,JSON.stringify(v))}});
test("coverage requires every golden journey per cohort and every expected category",()=>{const v:any=input();for(const s of v.sessions)s.tasks[2]={...s.tasks[2],task_id:"release-blocked",expected_decision:"blocked",selected_decision:"blocked"};const r:any=analyzeDecisionResearch(v);assert.equal(r.status,"blocked");assert.equal(r.gate_findings.find((x:any)=>x.id==="decision-category-coverage").passed,false)});
test("120-second gate applies to highest regression, not first candidate",()=>{const v:any=input();for(const s of v.sessions)for(const t of s.tasks)t.time_to_first_candidate_seconds=999;assert.equal(analyzeDecisionResearch(v).status,"pass");for(const s of v.sessions)s.tasks[1].highest_regression_time_seconds=121;const r:any=analyzeDecisionResearch(v);assert.equal(r.status,"blocked");assert.equal(r.gate_findings.find((x:any)=>x.id==="median-highest-severity-regression").passed,false)});
test("structured P0/P1 findings block and suggest deterministic unexecuted commands",()=>{const v:any=input();v.sessions[0].findings=[{code:"DC-BLOCK",severity:"P1",classification:"workflow",summary:"Required release decision is blocked.",evidence:{locator:"report:release-status",observation:"The participant selected approval while the evidence panel showed blocked."}}];const r:any=analyzeDecisionResearch(v);assert.equal(r.status,"blocked");assert.deepEqual(r.suggested_bd_commands,['bd create --type bug --priority 1 --title "Decision research P1: DC-BLOCK" --description "Review structured evidence in the decision-comprehension report."']);assert.equal(r.commands_executed,false)});
test("synthetic is non-evidence and published fixture stays blocked",()=>{const f=JSON.parse(readFileSync(join(SKILL_ROOT,"assets/decision-comprehension/synthetic-sessions.json"),"utf8"));assert.equal(validateDecisionResearch(f).valid,true,errors(f));const r:any=analyzeDecisionResearch(f);assert.equal(r.status,"blocked");assert.equal(r.evidence.session_count,0)});
test("CLI runs offline with pass, blocked, invalid exits",()=>{const w=mkdtempSync(join(tmpdir(),"decision-research-"));try{const good=join(w,"good.json"),synthetic=join(w,"synthetic.json");writeFileSync(good,JSON.stringify(input()));writeFileSync(synthetic,JSON.stringify(input(true)));let r=spawnSync(process.execPath,[CLI,"decision-research","--input",good,"--format","json"],{encoding:"utf8",env:{PATH:""}});assert.equal(r.status,0,r.stderr);r=spawnSync(process.execPath,[CLI,"decision-research","--input",synthetic,"--format","json"],{encoding:"utf8",env:{PATH:""}});assert.equal(r.status,3);r=spawnSync(process.execPath,[CLI,"decision-research","--input",join(w,"missing.json"),"--format","json"],{encoding:"utf8",env:{PATH:""}});assert.equal(r.status,2)}finally{rmSync(w,{recursive:true,force:true})}});
