#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { validate } from "./validate_goose_plugin.js";
import { validateAgentPluginSchema } from "./validate_agent_plugin_schema.js";
import { fullEval, type FullEvalOptions } from "./full_eval.js";
import { runCiEval } from "./ci_eval.js";
import { renderCiProgress, renderHistoricalReview, renderMachineJsonl, renderTerminalProgress, type TerminalVerbosity } from "./progress_projections.js";
import { replayExecutionEvents } from "./execution_event_stream.js";
import { loadPortablePlugin } from "./portable_loader.js";
import type { ValidationMode } from "./validation_outcomes.js";
import type { ReviewConfig } from "./independent_review.js";
export const EXIT_SUCCESS=0, EXIT_FAILURE=1, EXIT_USAGE=2, EXIT_BLOCKED=3;
type Format="text"|"json"|"jsonl"|"ci"|"review"; interface Common{format:Format;quiet:boolean;help:boolean;mode:ValidationMode;args:string[]}
const HERE=dirname(fileURLToPath(import.meta.url));
const HELP="Usage: plugin-creator <init|validate|migrate|verify|package|full-eval|ci-eval|independent-review> [options]\n\nCommon options:\n  --format text|json|jsonl|ci|review  Output format (default: text)\n  --mode portable-load|strict-authoring  Validation mode\n  --quiet             Suppress normal output\n  --help              Show help\n\nfull-eval options:\n  <plugin-dir> [--workspace DIR] [--component-receipt FILE ...]\n  [--integration DIR] [--archive ZIP] [--tests-status STATUS]\n  [--human-review pass|pending|na] [--approval FILE --approval-trust-policy FILE --test-evidence FILE] [--total-budget-ms MS] [--heartbeat-ms MS] [--stale-after-ms MS] [--lease-ms MS] [--cancellation-grace-ms MS]\n  [--production] [--dry-run] [--resume] [--cancel] [--progress quiet|normal|verbose]\n\nindependent-review options:\n  --config FILE --host COMMAND [--host-arg ARG ...]  Run isolated review branches\n\nci-eval options:\n  --config FILE        Provider-neutral, non-interactive CI configuration\n\nCI exit codes: 0 success, 1 evaluation failure, 2 invalid config, 3 blocked capability/evidence, 4 pending approval.";
function parseCommon(args:string[]):Common|string{let format:Format="text",mode:ValidationMode="strict-authoring",quiet=false,help=false;const rest:string[]=[];for(let i=0;i<args.length;i++){const a=args[i];if(a==="--quiet"||a==="-q")quiet=true;else if(a==="--help"||a==="-h")help=true;else if(a==="--mode"){const v=args[++i];if(!["portable-load","strict-authoring"].includes(v))return"--mode must be portable-load or strict-authoring";mode=v as ValidationMode;}else if(a.startsWith("--mode=")){const v=a.slice(7);if(!["portable-load","strict-authoring"].includes(v))return"--mode must be portable-load or strict-authoring";mode=v as ValidationMode;}else if(a==="--format"){ const v=args[++i];if(!["text","json","jsonl","ci","review"].includes(v))return"--format must be text, json, jsonl, ci, or review";format=v as Format;}else if(a.startsWith("--format=")){const v=a.slice(9);if(!["text","json","jsonl","ci","review"].includes(v))return"--format must be text, json, jsonl, ci, or review";format=v as Format;}else rest.push(a);}return{format,quiet,help,mode,args:rest};}
function emit(value:unknown,text:string,o:Common){if(!o.quiet)console.log(o.format==="json"?JSON.stringify(value,null,2):text);}
function usage(message?:string){if(message)console.error(message);console.error(HELP);return EXIT_USAGE;}
function child(script:string,args:string[]){return spawnSync(process.execPath,[join(HERE,script),...args],{encoding:"utf8"});}
function wrapped(command:"init"|"package",o:Common){if(!o.args.length)return usage(command+" requires a target");const r=child(command==="init"?"init_goose_plugin.js":"package_goose_plugin.js",o.args),out=(r.stdout??"").trim(),err=(r.stderr??"").trim(),code=r.status??1;if(code){console.error(err||out);return code===2?2:1;}const output=out.split(/\r?\n/).filter(Boolean).at(-1)??"";emit({ok:true,command,output},output,o);return 0;}
function runValidate(o:Common){if(o.args.length!==1)return usage("validate requires exactly one plugin directory");const target=resolve(o.args[0]);if(o.mode==="portable-load"){const outcome=loadPortablePlugin(target,o.mode);emit({ok:outcome.status==="accepted",command:"validate",target,outcome},"Portable load: "+outcome.status,o);return outcome.status==="accepted"?0:1;}const schema=validateAgentPluginSchema(target,"auto","strict-authoring"),structural=validate(target),ok=schema.valid&&!structural.errors.length;const lines=[...schema.documents.map(d=>(d.valid?"VALID: ":"INVALID: ")+d.file+" ("+d.type+")"),...schema.errors.map(e=>"SCHEMA ERROR: "+e.path+": "+e.message),...structural.warnings.map(w=>"WARNING: "+w),...structural.errors.map(e=>"ERROR: "+e),...(ok?["OK: "+target]:[])];emit({ok,command:"validate",target,schema,structural},lines.join("\n"),o);return ok?0:1;}
function runMigrate(o:Common){if(!o.args.length)return usage("migrate requires a plugin directory");const r=child("migrate_plugin.js",o.args),raw=(r.stdout??"").trim();let report:any;try{report=JSON.parse(raw);}catch{console.error((r.stderr??raw).trim());return r.status===2?2:1;}emit(report,"Migration: "+String(report.status).toUpperCase(),o);return report.status==="blocked"?3:0;}
function runVerify(o:Common){if(!o.args.length)return usage("verify requires a plugin directory");const r=child("verify_plugin_gates.js",o.args),raw=(r.stdout??"").trim();let receipt:any;try{receipt=JSON.parse(raw);}catch{console.error((r.stderr??raw).trim());return r.status===2?2:1;}emit(receipt,"Plugin "+receipt.name+": "+String(receipt.status).toUpperCase()+" ("+receipt.profile+")",o);return receipt.status==="pass"?0:receipt.status==="blocked"?3:1;}
async function runFullEval(o:Common){
 if(!o.args[0]||o.args[0].startsWith("-"))return usage("full-eval requires a plugin directory");
 const options:FullEvalOptions={pluginPath:o.args[0]},receipts:string[]=[];let progressMode:TerminalVerbosity=o.quiet?"quiet":"normal";const value=new Set(["--workspace","--component-receipt","--integration","--archive","--tests-status","--human-review","--approval","--approval-trust-policy","--test-evidence","--min-pass-rate","--min-delta","--total-budget-ms","--heartbeat-ms","--stale-after-ms","--lease-ms","--cancellation-grace-ms","--progress"]);
 for(let i=1;i<o.args.length;i++){const a=o.args[i];if(a==="--production")options.production=true;else if(a==="--dry-run")options.dryRun=true;else if(a==="--resume")options.resume=true;else if(a==="--cancel")options.cancel=true;else if(value.has(a)){const v=o.args[++i];if(!v||v.startsWith("--"))return usage(a+" requires a value");if(a==="--progress"){if(!["quiet","normal","verbose"].includes(v))return usage("--progress must be quiet, normal, or verbose");progressMode=v as TerminalVerbosity;}else if(a==="--component-receipt")receipts.push(v);else if(a==="--workspace")options.workspace=v;else if(a==="--integration")options.integration=v;else if(a==="--archive")options.archive=v;else if(a==="--tests-status")options.testsStatus=v;else if(a==="--human-review")options.humanReview=v;else if(a==="--approval")options.approval=v;else if(a==="--approval-trust-policy")options.approvalTrustPolicy=v;else if(a==="--test-evidence")options.testEvidence=v;else if(a==="--min-pass-rate")options.minPassRate=Number(v);else if(a==="--min-delta")options.minDelta=Number(v);else if(a==="--total-budget-ms")options.reliability={...options.reliability,total_budget_ms:Number(v)};else if(a==="--heartbeat-ms")options.reliability={...options.reliability,heartbeat_ms:Number(v)};else if(a==="--stale-after-ms")options.reliability={...options.reliability,stale_after_ms:Number(v)};else if(a==="--lease-ms")options.reliability={...options.reliability,lease_ms:Number(v)};else options.reliability={...options.reliability,cancellation_grace_ms:Number(v)};}else return usage("Unknown full-eval option: "+a);}
 if(receipts.length)options.componentReceipts=receipts;
 try{const result=await fullEval(options);if(!o.quiet){if(o.format==="json")console.log(JSON.stringify(result,null,2));else{const events=options.dryRun?[]:replayExecutionEvents(result.event_file).events,projection=o.format==="jsonl"?renderMachineJsonl(events):o.format==="ci"?renderCiProgress(events):o.format==="review"?renderHistoricalReview(events):renderTerminalProgress(events,progressMode);if(projection.output)process.stdout.write(projection.output+(projection.output.endsWith("\n")?"":"\n"));}}return result.exit_code;}catch(error){if(o.format==="jsonl")console.error(JSON.stringify({kind:"full-eval-error",message:(error as Error).message}));else console.error((error as Error).message);return 1;}
}
export async function runCli(argv:string[]):Promise<number>{const[command,...raw]=argv;if(!command||command==="--help"||command==="-h"){console.log(HELP);return 0;}if(!["init","validate","migrate","verify","package","full-eval","ci-eval","independent-review"].includes(command))return usage("Unknown command: "+command);const o=parseCommon(raw);if(typeof o==="string")return usage(o);if(o.help){console.log(HELP);return 0;}if(command==="independent-review"){const ci=o.args.indexOf("--config"),hi=o.args.indexOf("--host"),configPath=ci>=0?o.args[ci+1]:undefined,host=hi>=0?o.args[hi+1]:undefined,hostArgs:string[]=[];for(let i=0;i<o.args.length;i++)if(o.args[i]==="--host-arg"){if(!o.args[i+1])return usage("--host-arg requires a value");hostArgs.push(o.args[++i])}if(!configPath||!host)return usage("independent-review requires --config FILE --host COMMAND");try{const {runIndependentReview,commandBranchHost}=await import("./independent_review.js"),config=JSON.parse(readFileSync(resolve(configPath),"utf8")) as ReviewConfig,result=await runIndependentReview(config,commandBranchHost(host,hostArgs));emit(result,"Independent review: "+result.runId+" ("+result.branches.filter(x=>x.status==="succeeded").length+"/"+result.branches.length+" branches succeeded)",o);return result.branches.some(x=>x.status!=="succeeded")?EXIT_FAILURE:EXIT_SUCCESS}catch(error){console.error((error as Error).message);return EXIT_USAGE;}}if(command==="ci-eval"){const i=o.args.indexOf("--config"),path=i>=0?o.args[i+1]:undefined;if(!path||o.args.length!==2)return usage("ci-eval requires --config FILE");const result=await runCiEval(resolve(path));if(!o.quiet)console.log(JSON.stringify(result,null,2));return result.exit_code;}if(command==="validate")return runValidate(o);if(command==="migrate")return runMigrate(o);if(command==="verify")return runVerify(o);if(command==="full-eval")return await runFullEval(o);return wrapped(command as "init"|"package",o);}
if(process.argv[1]&&resolve(fileURLToPath(import.meta.url))===resolve(process.argv[1]))process.exitCode=await runCli(process.argv.slice(2));
