#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { validate } from "./validate_goose_plugin.js";
import { validateAgentPluginSchema } from "./validate_agent_plugin_schema.js";
import { fullEval, type FullEvalOptions } from "./full_eval.js";
import { loadPortablePlugin } from "./portable_loader.js";
import type { ValidationMode } from "./validation_outcomes.js";
export const EXIT_SUCCESS=0, EXIT_FAILURE=1, EXIT_USAGE=2, EXIT_BLOCKED=3;
type Format="text"|"json"; interface Common{format:Format;quiet:boolean;help:boolean;mode:ValidationMode;args:string[]}
const HERE=dirname(fileURLToPath(import.meta.url));
const HELP="Usage: plugin-creator <init|validate|verify|package|full-eval> [options]\n\nCommon options:\n  --format text|json  Output format (default: text)\n  --mode portable-load|strict-authoring  Validation mode\n  --quiet             Suppress normal output\n  --help              Show help\n\nfull-eval options:\n  <plugin-dir> [--workspace DIR] [--component-receipt FILE ...]\n  [--integration DIR] [--archive ZIP] [--tests-status STATUS]\n  [--human-review pass|pending|na] [--dry-run] [--resume]\n\nExit codes: 0 success, 1 failure, 2 usage, 3 blocked.";
function parseCommon(args:string[]):Common|string{let format:Format="text",mode:ValidationMode="strict-authoring",quiet=false,help=false;const rest:string[]=[];for(let i=0;i<args.length;i++){const a=args[i];if(a==="--quiet"||a==="-q")quiet=true;else if(a==="--help"||a==="-h")help=true;else if(a==="--mode"){const v=args[++i];if(!["portable-load","strict-authoring"].includes(v))return"--mode must be portable-load or strict-authoring";mode=v as ValidationMode;}else if(a.startsWith("--mode=")){const v=a.slice(7);if(!["portable-load","strict-authoring"].includes(v))return"--mode must be portable-load or strict-authoring";mode=v as ValidationMode;}else if(a==="--format"){ const v=args[++i];if(v!=="text"&&v!=="json")return"--format must be text or json";format=v;}else if(a.startsWith("--format=")){const v=a.slice(9);if(v!=="text"&&v!=="json")return"--format must be text or json";format=v;}else rest.push(a);}return{format,quiet,help,mode,args:rest};}
function emit(value:unknown,text:string,o:Common){if(!o.quiet)console.log(o.format==="json"?JSON.stringify(value,null,2):text);}
function usage(message?:string){if(message)console.error(message);console.error(HELP);return EXIT_USAGE;}
function child(script:string,args:string[]){return spawnSync(process.execPath,[join(HERE,script),...args],{encoding:"utf8"});}
function wrapped(command:"init"|"package",o:Common){if(!o.args.length)return usage(command+" requires a target");const r=child(command==="init"?"init_goose_plugin.js":"package_goose_plugin.js",o.args),out=(r.stdout??"").trim(),err=(r.stderr??"").trim(),code=r.status??1;if(code){console.error(err||out);return code===2?2:1;}const output=out.split(/\r?\n/).filter(Boolean).at(-1)??"";emit({ok:true,command,output},output,o);return 0;}
function runValidate(o:Common){if(o.args.length!==1)return usage("validate requires exactly one plugin directory");const target=resolve(o.args[0]);if(o.mode==="portable-load"){const outcome=loadPortablePlugin(target,o.mode);emit({ok:outcome.status==="accepted",command:"validate",target,outcome},"Portable load: "+outcome.status,o);return outcome.status==="accepted"?0:1;}const schema=validateAgentPluginSchema(target,"auto","strict-authoring"),structural=validate(target),ok=schema.valid&&!structural.errors.length;const lines=[...schema.documents.map(d=>(d.valid?"VALID: ":"INVALID: ")+d.file+" ("+d.type+")"),...schema.errors.map(e=>"SCHEMA ERROR: "+e.path+": "+e.message),...structural.warnings.map(w=>"WARNING: "+w),...structural.errors.map(e=>"ERROR: "+e),...(ok?["OK: "+target]:[])];emit({ok,command:"validate",target,schema,structural},lines.join("\n"),o);return ok?0:1;}
function runVerify(o:Common){if(!o.args.length)return usage("verify requires a plugin directory");const r=child("verify_plugin_gates.js",o.args),raw=(r.stdout??"").trim();let receipt:any;try{receipt=JSON.parse(raw);}catch{console.error((r.stderr??raw).trim());return r.status===2?2:1;}emit(receipt,"Plugin "+receipt.name+": "+String(receipt.status).toUpperCase()+" ("+receipt.profile+")",o);return receipt.status==="pass"?0:receipt.status==="blocked"?3:1;}
function runFullEval(o:Common){
 if(!o.args[0]||o.args[0].startsWith("-"))return usage("full-eval requires a plugin directory");
 const options:FullEvalOptions={pluginPath:o.args[0]},receipts:string[]=[];const value=new Set(["--workspace","--component-receipt","--integration","--archive","--tests-status","--human-review","--min-pass-rate","--min-delta"]);
 for(let i=1;i<o.args.length;i++){const a=o.args[i];if(a==="--dry-run")options.dryRun=true;else if(a==="--resume")options.resume=true;else if(value.has(a)){const v=o.args[++i];if(!v||v.startsWith("--"))return usage(a+" requires a value");if(a==="--component-receipt")receipts.push(v);else if(a==="--workspace")options.workspace=v;else if(a==="--integration")options.integration=v;else if(a==="--archive")options.archive=v;else if(a==="--tests-status")options.testsStatus=v;else if(a==="--human-review")options.humanReview=v;else if(a==="--min-pass-rate")options.minPassRate=Number(v);else options.minDelta=Number(v);}else return usage("Unknown full-eval option: "+a);}
 if(receipts.length)options.componentReceipts=receipts;
 try{const result=fullEval(options);const text=["full-eval: "+result.status,...result.phases.map(p=>"["+p.status+"] "+p.name+": "+p.detail),...result.next_actions.map(a=>"NEXT: "+a)].join("\n");emit(result,text,o);return result.exit_code;}catch(error){console.error((error as Error).message);return 1;}
}
export function runCli(argv:string[]):number{const[command,...raw]=argv;if(!command||command==="--help"||command==="-h"){console.log(HELP);return 0;}if(!["init","validate","verify","package","full-eval"].includes(command))return usage("Unknown command: "+command);const o=parseCommon(raw);if(typeof o==="string")return usage(o);if(o.help){console.log(HELP);return 0;}if(command==="validate")return runValidate(o);if(command==="verify")return runVerify(o);if(command==="full-eval")return runFullEval(o);return wrapped(command as "init"|"package",o);}
if(process.argv[1]&&resolve(fileURLToPath(import.meta.url))===resolve(process.argv[1]))process.exitCode=runCli(process.argv.slice(2));
