import { randomUUID } from "node:crypto";
import { closeSync, existsSync, fsyncSync, linkSync, mkdirSync, openSync, readFileSync, readdirSync, renameSync, rmSync, statSync, truncateSync, unlinkSync, writeFileSync, writeSync } from "node:fs";
import { dirname, basename } from "node:path";

export interface ExecutionReliabilityPlan { lease_ms:number; heartbeat_ms:number; stale_after_ms:number; max_attempts:number; backoff_ms:number; max_backoff_ms:number; cancellation_grace_ms:number; total_budget_ms:number }
export const DEFAULT_EXECUTION_RELIABILITY_PLAN:ExecutionReliabilityPlan={lease_ms:30_000,heartbeat_ms:5_000,stale_after_ms:45_000,max_attempts:3,backoff_ms:25,max_backoff_ms:250,cancellation_grace_ms:250,total_budget_ms:120_000};
export interface AttemptRecord { attempt_id:string; number:number; started_at:string; completed_at?:string; status:"running"|"succeeded"|"failed"|"cancelled"; retryable?:boolean; stop_reason?:string; elapsed_ms?:number }
export interface TerminationReport { outcome:"already-exited"|"terminated"|"killed"|"survivors"; signals:Array<{signal:"SIGTERM"|"SIGKILL";targets:number[];at:string}>; survivors:number[] }
export interface ReliabilityLedger { started_at:string; consumed_ms:number; attempts:number; stop_reason?:string; cancellation?:{requested_at:string;forced_at?:string;grace_ms:number;termination?:TerminationReport} }
export function newReliabilityLedger(now=Date.now()):ReliabilityLedger{return{started_at:new Date(now).toISOString(),consumed_ms:0,attempts:0}}
export function normalizePlan(plan:Partial<ExecutionReliabilityPlan>={}):ExecutionReliabilityPlan {const p={...DEFAULT_EXECUTION_RELIABILITY_PLAN,...plan};for(const [key,value] of Object.entries(p))if(!Number.isFinite(value)||value<0)throw new Error("invalid execution reliability plan: "+key);if(p.max_attempts<1||p.heartbeat_ms<1||p.heartbeat_ms>p.stale_after_ms||p.lease_ms>p.stale_after_ms)throw new Error("invalid execution reliability plan thresholds");return p}
export function beginAttempt(records:AttemptRecord[]|undefined,now=Date.now()):AttemptRecord[]{const prior=records??[];return[...prior,{attempt_id:randomUUID(),number:prior.length+1,started_at:new Date(now).toISOString(),status:"running"}]}
export function finishAttempt(records:AttemptRecord[],status:AttemptRecord["status"],options:{retryable?:boolean;stop_reason?:string;now?:number}={}):AttemptRecord[]{if(!records.length||records.at(-1)!.status!=="running")throw new Error("no running execution attempt");const now=options.now??Date.now(),last=records.at(-1)!;return[...records.slice(0,-1),{...last,status,retryable:options.retryable,stop_reason:options.stop_reason,completed_at:new Date(now).toISOString(),elapsed_ms:Math.max(0,now-Date.parse(last.started_at))}]}
export function retryBackoffMs(attempt:number,plan:ExecutionReliabilityPlan):number{return Math.min(plan.max_backoff_ms,plan.backoff_ms*Math.max(1,2**Math.max(0,attempt-1)))}
export function elapsedBudgetMs(ledger:ReliabilityLedger,now=Date.now()):number{return Math.max(ledger.consumed_ms,Math.max(0,now-Date.parse(ledger.started_at)))}
export function remainingBudgetMs(ledger:ReliabilityLedger,plan:ExecutionReliabilityPlan,now=Date.now()):number{return Math.max(0,plan.total_budget_ms-elapsedBudgetMs(ledger,now))}
export function mayRetry(input:{attempts:number;retryable:boolean;consumed_ms:number;remaining_ms?:number},plan:ExecutionReliabilityPlan):{retry:boolean;reason?:string;backoff_ms:number}{if(!input.retryable)return{retry:false,reason:"nonretryable",backoff_ms:0};if(input.attempts>=plan.max_attempts)return{retry:false,reason:"retry-limit-exhausted",backoff_ms:0};const backoff=retryBackoffMs(input.attempts,plan),remaining=input.remaining_ms??plan.total_budget_ms-input.consumed_ms;if(remaining<=backoff)return{retry:false,reason:"total-budget-exhausted",backoff_ms:0};return{retry:true,backoff_ms:backoff}}
export function chargeBudget(ledger:ReliabilityLedger,_elapsedMs:number,plan:ExecutionReliabilityPlan,now=Date.now()):ReliabilityLedger {const consumed_ms=elapsedBudgetMs(ledger,now);return{...ledger,consumed_ms,attempts:ledger.attempts+1,...(consumed_ms>=plan.total_budget_ms?{stop_reason:"total-budget-exhausted"}:{})}}
export const sleep=(ms:number):void=>{if(ms>0)Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms)};

export interface LeaseRecord {schema_version:"1.1";owner:string;generation:number;fencing_token:string;pid:number;process_group_id:number;acquired_at:string;heartbeat_at:string;expires_at:string}
export function processAlive(pid:number):boolean{try{process.kill(pid,0);if(process.platform==="linux"){try{const stat=readFileSync("/proc/"+pid+"/stat","utf8"),state=stat.slice(stat.lastIndexOf(")")+2,stat.lastIndexOf(")")+3);if(state==="Z")return false}catch{}}return true}catch(error:any){return error?.code==="EPERM"}}
export function readLease(path:string):LeaseRecord|null{try{const v=JSON.parse(readFileSync(path,"utf8"));return v?.schema_version==="1.1"&&typeof v.owner==="string"&&Number.isInteger(v.generation)&&typeof v.fencing_token==="string"&&Number.isInteger(v.pid)&&Number.isInteger(v.process_group_id)&&typeof v.heartbeat_at==="string"&&typeof v.expires_at==="string"?v:null}catch{return null}}
function replaceJson(path:string,value:unknown):void{const tmp=path+".tmp-"+process.pid+"-"+randomUUID();writeFileSync(tmp,JSON.stringify(value),{mode:0o600});renameSync(tmp,path)}
function withMutex<T>(path:string,fn:()=>T):T{mkdirSync(dirname(path),{recursive:true});for(let i=0;i<400;i++){let fd:number|undefined;try{fd=openSync(path,"wx",0o600);try{return fn()}finally{closeSync(fd);rmSync(path,{force:true})}}catch(error:any){if(fd!==undefined)try{closeSync(fd)}catch{}if(error?.code!=="EEXIST")throw error;sleep(5)}}throw new Error("timed out acquiring execution fence mutex")}
function fenceGeneration(path:string):number{try{const x=JSON.parse(readFileSync(path,"utf8"));return Number.isInteger(x.generation)?x.generation:0}catch{return 0}}
function ownProcessGroup():number{return process.platform==="win32"?process.pid:process.pid}
export function leaseIsStale(lease:LeaseRecord,plan:ExecutionReliabilityPlan,now=Date.now()):boolean{return now>=Date.parse(lease.expires_at)||now-Date.parse(lease.heartbeat_at)>=plan.stale_after_ms||!processAlive(lease.pid)}
export class ExecutionLease {private timer:NodeJS.Timeout|null=null;private constructor(readonly path:string,readonly owner:string,readonly generation:number,readonly fencingToken:string,readonly plan:ExecutionReliabilityPlan){}
 static acquire(path:string,plan=DEFAULT_EXECUTION_RELIABILITY_PLAN,now=Date.now()):ExecutionLease {const p=normalizePlan(plan),owner=randomUUID(),token=randomUUID(),mutex=path+".mutex",fence=path+".fence";mkdirSync(dirname(path),{recursive:true});for(let n=0;n<100;n++){let won:ExecutionLease|null=null,busy=false,stalePid:number|undefined;withMutex(mutex,()=>{const current=readLease(path);if(current&&!leaseIsStale(current,p,now)){busy=true;return}if(current&&processAlive(current.pid)&&current.pid!==process.pid)stalePid=current.pid;const generation=Math.max(fenceGeneration(fence),current?.generation??0)+1;replaceJson(fence,{schema_version:"1.0",generation,fencing_token:token,updated_at:new Date(now).toISOString()});replaceJson(path,{schema_version:"1.1",owner,generation,fencing_token:token,pid:process.pid,process_group_id:ownProcessGroup(),acquired_at:new Date(now).toISOString(),heartbeat_at:new Date(now).toISOString(),expires_at:new Date(now+p.lease_ms).toISOString()} satisfies LeaseRecord);won=new ExecutionLease(path,owner,generation,token,p)});if(won){if(stalePid)forceTerminate(stalePid,p.cancellation_grace_ms);return won}if(!busy)continue;sleep(Math.min(25,p.heartbeat_ms));now=Date.now()}throw new Error("full-eval workspace is leased by another active run")}
 private assertCurrentUnlocked():LeaseRecord{const current=readLease(this.path),fence=this.path+".fence";if(!current||current.owner!==this.owner||current.generation!==this.generation||current.fencing_token!==this.fencingToken||fenceGeneration(fence)!==this.generation)throw new Error("full-eval execution lease was fenced");return current}
 heartbeat(now=Date.now()):void{withMutex(this.path+".mutex",()=>{const current=this.assertCurrentUnlocked();replaceJson(this.path,{...current,heartbeat_at:new Date(now).toISOString(),expires_at:new Date(now+this.plan.lease_ms).toISOString()})})}
 checkpoint(fn:()=>void):void{withMutex(this.path+".mutex",()=>{this.assertCurrentUnlocked();fn()})}
 startHeartbeat():void{if(this.timer)return;this.timer=setInterval(()=>{try{this.heartbeat()}catch{}},this.plan.heartbeat_ms);this.timer.unref()}
 release():void{if(this.timer){clearInterval(this.timer);this.timer=null}withMutex(this.path+".mutex",()=>{const current=readLease(this.path);if(current?.owner===this.owner&&current.generation===this.generation)rmSync(this.path,{force:true})})}
}

export interface CancellationRequest {schema_version:"1.0";requested_at:string;requester_pid:number;target_owner?:string;target_pid?:number}
export function requestCancellation(path:string,lease:LeaseRecord|null,now=Date.now()):CancellationRequest{const request:CancellationRequest={schema_version:"1.0",requested_at:new Date(now).toISOString(),requester_pid:process.pid,...(lease?{target_owner:lease.owner,target_pid:lease.pid}:{})};mkdirSync(dirname(path),{recursive:true});replaceJson(path,request);return request}
export function readCancellation(path:string):CancellationRequest|null{try{const x=JSON.parse(readFileSync(path,"utf8"));return x?.schema_version==="1.0"&&typeof x.requested_at==="string"?x:null}catch{return null}}
export function clearCancellation(path:string):void{rmSync(path,{force:true})}
function linuxDescendants(root:number):number[]{if(process.platform!=="linux")return[root];const rows=new Map<number,{ppid:number;pgrp:number}>();for(const name of readdirSync("/proc")){if(!/^\d+$/.test(name))continue;try{const text=readFileSync("/proc/"+name+"/stat","utf8"),tail=text.slice(text.lastIndexOf(")")+2).split(" ");rows.set(Number(name),{ppid:Number(tail[1]),pgrp:Number(tail[2])})}catch{}}const found=new Set([root]);let changed=true;while(changed){changed=false;for(const [pid,row] of rows)if(found.has(row.ppid)&&!found.has(pid)){found.add(pid);changed=true}}return [...found]}
export function forceTerminate(pid:number,graceMs:number):TerminationReport{const initial=linuxDescendants(pid).filter(processAlive);if(!initial.length)return{outcome:"already-exited",signals:[],survivors:[]};const signals:TerminationReport["signals"]=[],send=(signal:"SIGTERM"|"SIGKILL",targets:number[])=>{const live=targets.filter(processAlive);if(!live.length)return;signals.push({signal,targets:[...live],at:new Date().toISOString()});for(const target of [...live].reverse())try{process.kill(target,signal)}catch{}};send("SIGTERM",initial);let deadline=Date.now()+Math.max(0,graceMs);while(initial.some(processAlive)&&Date.now()<deadline)sleep(10);let survivors=initial.filter(processAlive);if(survivors.length){send("SIGKILL",survivors);deadline=Date.now()+Math.max(250,graceMs);while(survivors.some(processAlive)&&Date.now()<deadline)sleep(10);survivors=survivors.filter(processAlive)}return{outcome:survivors.length?"survivors":signals.some(x=>x.signal==="SIGKILL")?"killed":"terminated",signals,survivors}}

export type FaultPoint="checkpoint-before-write"|"checkpoint-partial-write"|"checkpoint-before-rename"|"checkpoint-after-rename";
export type FaultInjector=(point:FaultPoint,path:string)=>void;
export function environmentFaultInjector(point:FaultPoint):void{const fault=process.env.PLUGIN_CREATOR_FAULT_INJECTION;if(fault===point)throw new Error("injected execution fault: "+point);if(fault==="process-crash:"+point)process.kill(process.pid,"SIGKILL")}
export function atomicCheckpoint(path:string,value:unknown,inject:FaultInjector=environmentFaultInjector):void {mkdirSync(dirname(path),{recursive:true});const tmp=path+".tmp-"+process.pid+"-"+randomUUID(),bytes=Buffer.from(JSON.stringify(value,null,2)+"\n");inject("checkpoint-before-write",path);const fd=openSync(tmp,"wx",0o600);try{const split=Math.max(1,Math.floor(bytes.length/2));writeSync(fd,bytes.subarray(0,split));fsyncSync(fd);inject("checkpoint-partial-write",path);writeSync(fd,bytes.subarray(split));fsyncSync(fd)}finally{closeSync(fd)}try{inject("checkpoint-before-rename",path);renameSync(tmp,path);inject("checkpoint-after-rename",path)}finally{rmSync(tmp,{force:true})}}
export function cleanupCheckpointPartials(path:string):void {const prefix=basename(path)+".tmp-",dir=dirname(path);if(!existsSync(dir))return;for(const name of readdirSync(dir))if(name.startsWith(prefix))rmSync(dir+"/"+name,{force:true})}
export function repairInterruptedJsonl(path:string):boolean {if(!existsSync(path))return false;const data=readFileSync(path);if(!data.length||data.at(-1)===10)return false;const newline=data.lastIndexOf(10);truncateSync(path,newline<0?0:newline+1);return true}
export function cancellationDecision(requestedAt:number,now:number,graceMs:number,cooperativeComplete:boolean):"cooperative"|"wait"|"forced" {if(cooperativeComplete)return"cooperative";return now-requestedAt>=graceMs?"forced":"wait"}
