import type { ComponentOutcome, TypedDiagnostic } from "./validation_outcomes.js";
export type McpTransport="stdio"|"streamable-http"|"sse";
export interface McpCapabilities{transports:readonly McpTransport[];redirectOriginProtection:boolean}
export type McpRuntimeFailure="start"|"connect"|"authenticate"|"handshake";
const rule="Agent Plugins 1.0.0 section 7.2.2";
function d(id:string,code:string,message:string,remediation:string,severity:TypedDiagnostic["severity"]="error"):TypedDiagnostic{return{code,rule,message,severity,scope:"runtime-process",sourcePath:"mcp.json",remediation,componentType:"mcp",componentId:id}}
export function validateMcpCapabilities(capabilities:McpCapabilities):TypedDiagnostic[]{const supported=capabilities.transports.filter(x=>x==="stdio"||x==="streamable-http");return supported.length?[]:[d("*","mcp.capability.missing-standard-transport","An MCP-capable client must support stdio or streamable-http.","Enable at least one standard transport.")]}
export function mcpServerCapabilityOutcome(id:string,transport:McpTransport,capabilities:McpCapabilities):ComponentOutcome{if(!capabilities.transports.includes(transport))return{status:"skipped-unsupported",scope:"component-entry",sourcePath:"mcp.json",componentType:"mcp",componentId:id,diagnostics:[d(id,"mcp.transport-unsupported","Transport "+transport+" is unsupported.","Enable the transport or skip this server.","warning")]};if((transport==="streamable-http"||transport==="sse")&&!capabilities.redirectOriginProtection)return{status:"skipped-unsupported",scope:"component-entry",sourcePath:"mcp.json",componentType:"mcp",componentId:id,diagnostics:[d(id,"mcp.redirect-protection-unsupported","Client cannot guarantee that configured headers stay on the configured origin across redirects.","Implement redirect-origin protection before connecting.")]};return{status:"accepted",scope:"component-entry",sourcePath:"mcp.json",componentType:"mcp",componentId:id,diagnostics:[]}}
export function mcpRuntimeFailureOutcome(id:string,failure:McpRuntimeFailure,detail?:string):ComponentOutcome{return{status:"runtime-failed",scope:"runtime-process",sourcePath:"mcp.json",componentType:"mcp",componentId:id,diagnostics:[d(id,"mcp.runtime."+failure,"MCP server failed during "+failure+(detail?": "+detail:""),"Correct the runtime condition and retry only this server.")]}}
