#!/usr/bin/env node
/** Deterministic, fail-closed migration audit for legacy Goose/Open Plugins. */
import { copyFileSync, cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { inspectLegacyMcp } from "./mcp_compatibility.js";
import { resolveContainedPath } from "./path_containment.js";
import { findSchemaIdentifier, getDefaultSchemaVersion } from "./schema_registry.js";

export type MigrationClassification = "portable-core" | "goose-extension" | "legacy-compatible" | "migratable" | "unsupported";
export interface MigrationFinding { artifact:string; classification:MigrationClassification; message:string; blocking:boolean }
export interface ProposedMove { from:string; to:string; reason:string }
export interface ProposedDocument { path:string; document:unknown; reason:string }
export interface MigrationOptions { apply?:boolean; approval?:boolean; backupDirectory?:string }
export interface MigrationReport { root:string; mode:"dry-run"|"apply"; status:"ready"|"blocked"|"applied"; findings:MigrationFinding[]; proposedMoves:ProposedMove[]; proposedDocuments:ProposedDocument[]; backupDirectory?:string; changed:string[] }

const PORTABLE_FIELDS=new Set(["$schema","name","version","description","author","homepage","repository","license","keywords","extensions"]);
const DEFAULT=getDefaultSchemaVersion();
const PLUGIN_SCHEMA=DEFAULT.schemas.manifest.id;
const MCP_SCHEMA=DEFAULT.schemas.mcp.id;
const SECRET_KEY=/(?:^|[_-])(api[_-]?key|token|secret|password|passwd|private[_-]?key|authorization|credential)(?:$|[_-])/i;
const SECRET_VALUE=/(?:-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|(?:sk|ghp|github_pat|xox[baprs])[-_][A-Za-z0-9_-]{12,}|AKIA[0-9A-Z]{16}|Bearer\s+[A-Za-z0-9._~+\/-]{12,})/;
const object=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const slash=(p:string)=>p.split(sep).join("/");
function json(path:string):{value?:unknown,error?:string}{try{return{value:JSON.parse(readFileSync(path,"utf8"))}}catch(e){return{error:(e as Error).message}}}
function frontmatterName(path:string):string|undefined{try{return /^---\r?\n[\s\S]*?^name:\s*([a-z0-9](?:[a-z0-9.-]*[a-z0-9])?)\s*$[\s\S]*?^---/m.exec(readFileSync(path,"utf8"))?.[1]}catch{return undefined}}
function walk(root:string):string[]{const out:string[]=[];function visit(dir:string){for(const n of readdirSync(dir).sort()){if([".git",".beads","node_modules","dist",".plugin-migration-backups"].includes(n))continue;const p=join(dir,n),rel=slash(relative(root,p)),s=lstatSync(p);out.push(rel);if(s.isDirectory()&&!s.isSymbolicLink())visit(p)}}visit(root);return out}
function inspectValues(value:unknown,artifact:string,findings:MigrationFinding[],path=""):void{if(Array.isArray(value)){value.forEach((v,i)=>inspectValues(v,artifact,findings,path+"/"+i));return}if(!object(value))return;for(const[k,v]of Object.entries(value)){const p=path+"/"+k;if(SECRET_KEY.test(k)&&typeof v==="string"&&v.trim()&&!/^\$\{[A-Z][A-Z0-9_]*\}$/.test(v))findings.push({artifact:artifact+p,classification:"unsupported",message:"Likely embedded secret; replace it with an environment-variable reference.",blocking:true});if(typeof v==="string"&&SECRET_VALUE.test(v))findings.push({artifact:artifact+p,classification:"unsupported",message:"Likely secret material detected (value redacted).",blocking:true});inspectValues(v,artifact,findings,p)}}
function unsafeString(v:string):boolean{return isAbsolute(v)||v.startsWith("~"+sep)||v.startsWith("~/")||v.startsWith("file:")||v.split(/[\\/]+/).includes("..")}
function inspectPaths(value:unknown,artifact:string,findings:MigrationFinding[],path=""):void{if(Array.isArray(value)){value.forEach((v,i)=>inspectPaths(v,artifact,findings,path+"/"+i));return}if(!object(value))return;for(const[k,v]of Object.entries(value)){const p=path+"/"+k;if(typeof v==="string"&&/(?:path|file|cwd|command|hooks?|skills?|agents?)$/i.test(k)&&!v.includes("${")){if(unsafeString(v))findings.push({artifact:artifact+p,classification:"unsupported",message:"Unsafe or non-portable path: "+v,blocking:true})}inspectPaths(v,artifact,findings,p)}}
function add(findings:MigrationFinding[],artifact:string,classification:MigrationClassification,message:string,blocking=false){findings.push({artifact,classification,message,blocking})}
function unique<T extends {artifact:string;message:string}>(xs:T[]):T[]{return xs.filter((x,i)=>xs.findIndex(y=>y.artifact===x.artifact&&y.message===x.message)===i)}

export function auditPluginMigration(rootArg:string):MigrationReport{
 const root=resolve(rootArg),findings:MigrationFinding[]=[],proposedMoves:ProposedMove[]=[],proposedDocuments:ProposedDocument[]=[];
 const rootCheck=resolveContainedPath(root,root,{expectedKind:"directory"});if(!rootCheck.contained||rootCheck.kindOutcome!=="match"){add(findings,".","unsupported","Plugin root must be an existing directory.",true);return{root,mode:"dry-run",status:"blocked",findings,proposedMoves,proposedDocuments,changed:[]}}
 const entries=walk(root);for(const rel of entries){const path=join(root,rel),c=resolveContainedPath(root,path,{expectedKind:"any"});if(!c.contained){add(findings,rel,"unsupported","Filesystem entry resolves outside the plugin root ("+c.status+").",true);continue}if(lstatSync(path).isSymbolicLink()||!statSync(path).isFile())continue;if(statSync(path).size>1024*1024)continue;try{const text=readFileSync(path,"utf8");if(SECRET_VALUE.test(text))add(findings,rel,"unsupported","Likely secret material detected (value redacted).",true);if(/\.(?:json)$/i.test(rel)){const parsed=json(path);if(object(parsed.value)){inspectValues(parsed.value,rel,findings);inspectPaths(parsed.value,rel,findings)}}}catch{/* Binary and unreadable files are not interpreted. */}}
 const manifestPath=join(root,"plugin.json"),parsed=existsSync(manifestPath)?json(manifestPath):{error:"missing"};let manifest:Record<string,unknown>|undefined;
 if(parsed.error||!object(parsed.value))add(findings,"plugin.json","unsupported",parsed.error==="missing"?"Manifest is missing.":"Manifest is not valid JSON object: "+(parsed.error??"wrong top-level type"),true);else{
  manifest=parsed.value;inspectValues(manifest,"plugin.json",findings);inspectPaths(manifest,"plugin.json",findings);
  const rewritten:{[key:string]:unknown}={...manifest};let rewrite=false;
  for(const key of Object.keys(manifest).sort()){if(PORTABLE_FIELDS.has(key))add(findings,"plugin.json:/"+key,key==="extensions"?"goose-extension":"portable-core",key==="extensions"?"Client extension envelope.":"Portable manifest field.");else if(key==="mcpServers"){add(findings,"plugin.json:/mcpServers","migratable","Inline MCP can migrate to mcp.json.");delete rewritten[key];rewrite=true}else add(findings,"plugin.json:/"+key,"legacy-compatible","Unknown field is preserved by legacy tooling but ignored by portable loaders.")}
  const sid=manifest.$schema;if(typeof sid!=="string"){add(findings,"plugin.json:/$schema","migratable","Add the active Agent Plugins manifest schema.");rewritten.$schema=PLUGIN_SCHEMA;rewrite=true}else{const found=findSchemaIdentifier(sid);if(!found||found.type!=="manifest"||!found.version.activeForValidation)add(findings,"plugin.json:/$schema","unsupported",found?"Schema "+found.version.version+" is recognized but inactive.":"Unknown manifest schema identifier.",true);else add(findings,"plugin.json:/$schema","portable-core","Active Agent Plugins schema "+found.version.version+".")}
  if(rewrite)proposedDocuments.push({path:"plugin.json",document:rewritten,reason:"Normalize the portable manifest and remove migrated inline declarations."})
 }
 const canonicalSkills=entries.filter(x=>/^skills\/[^/]+\/SKILL\.md$/.test(x));for(const p of canonicalSkills)add(findings,p,"portable-core","Canonical Agent Skill.");
 const otherSkills=entries.filter(x=>/(^|\/)SKILL\.md$/.test(x)&&!canonicalSkills.includes(x));for(const p of otherSkills){const name=frontmatterName(join(root,p));if(!name)add(findings,p,"unsupported","Noncanonical Skill has no unambiguous portable name.",true);else{const to="skills/"+name+"/SKILL.md";if(entries.includes(to)||proposedMoves.some(m=>m.to===to))add(findings,p,"unsupported","Skill target "+to+" is ambiguous or already exists.",true);else{add(findings,p,"migratable","Move Skill directory to the canonical skills/<name> location.");proposedMoves.push({from:slash(dirname(p)),to:"skills/"+name,reason:"Canonical Agent Skill location."})}}}
 const mcp=inspectLegacyMcp(root);if(mcp.status==="portable")add(findings,"mcp.json","portable-core","Canonical portable MCP document.");else if(mcp.status==="migratable"){const from=mcp.sources[0]==="dot-mcp"?".mcp.json":"plugin.json:/mcpServers";add(findings,from,"migratable",mcp.diagnostics.join(" "));proposedDocuments.push({path:"mcp.json",document:mcp.proposedMcp,reason:"Convert the legacy MCP declaration to a closed portable MCP document."});if(from===".mcp.json")proposedMoves.push({from:".mcp.json",to:"mcp.json",reason:"Replace the legacy filename with the portable MCP document."})}else if(mcp.status==="blocked")for(const d of mcp.diagnostics)add(findings,"MCP","unsupported",d,true);
 for(const f of ["mcp.json",".mcp.json"]){const p=join(root,f);if(existsSync(p)){const q=json(p);if(q.error||!object(q.value))add(findings,f,"unsupported","Invalid MCP JSON: "+(q.error??"wrong top-level type"),true);else{inspectValues(q.value,f,findings);inspectPaths(q.value,f,findings);const sid=q.value.$schema;if(f==="mcp.json"&&sid===undefined){add(findings,f+":/$schema","migratable","Add the active Agent Plugins MCP schema.");proposedDocuments.push({path:f,document:{$schema:MCP_SCHEMA,...q.value},reason:"Add the active portable MCP schema identifier."})}else if(f==="mcp.json"){const found=typeof sid==="string"?findSchemaIdentifier(sid):undefined;if(!found||found.type!=="mcp"||!found.version.activeForValidation)add(findings,f+":/$schema","unsupported","Unsupported or mismatched MCP schema version.",true);else if(sid!==MCP_SCHEMA)add(findings,f+":/$schema","unsupported","MCP schema does not match the active migration target.",true)}}}}
 const legacyHooks="hooks/hooks.json",canonicalHooks="extensions/io.github.block.goose/hooks.json",hasLegacy=entries.includes(legacyHooks),hasCanonical=entries.includes(canonicalHooks);if(hasLegacy&&hasCanonical)add(findings,"hooks","unsupported","Both legacy and canonical Goose hooks exist; precedence is ambiguous.",true);else if(hasLegacy){add(findings,legacyHooks,"migratable","Move legacy hooks into the namespaced Goose extension.");proposedMoves.push({from:legacyHooks,to:canonicalHooks,reason:"Canonical namespaced Goose hook location."});if(manifest){const ext=object(manifest.extensions)?{...manifest.extensions}:{};ext["io.github.block.goose"]={version:1,hooks:canonicalHooks};proposedDocuments.push({path:"plugin.json",document:{...manifest,$schema:PLUGIN_SCHEMA,extensions:ext,...("mcpServers"in manifest?{mcpServers:undefined}:{})},reason:"Declare the namespaced Goose hooks extension."})}}else if(hasCanonical)add(findings,canonicalHooks,"goose-extension","Namespaced Goose hooks extension.");
 for(const p of entries.filter(x=>/^agents\/[^/]+\.(?:ya?ml|json|md)$/.test(x)))add(findings,p,"goose-extension","Goose custom agent; portable runtimes may ignore it.");
 for(const artifact of entries.filter(x=>/(^|\/)(?:agents?|hooks?)\//.test(x)&&!findings.some(f=>f.artifact===x)))add(findings,artifact,"legacy-compatible","Runtime-specific supporting artifact.");
 const cleanDocs:ProposedDocument[]=[];for(const d of proposedDocuments){const prior=cleanDocs.find(x=>x.path===d.path);if(!prior)cleanDocs.push(d);else if(d.path==="plugin.json"&&object(prior.document)&&object(d.document)){const merged={...prior.document,...d.document};for(const k of Object.keys(merged))if(merged[k]===undefined)delete merged[k];prior.document=merged;prior.reason+=" "+d.reason}else add(findings,d.path,"unsupported","Multiple incompatible document rewrites were proposed.",true)}
 const fs=unique(findings).sort((a,b)=>a.artifact.localeCompare(b.artifact)||a.classification.localeCompare(b.classification));const blocked=fs.some(x=>x.blocking);return{root,mode:"dry-run",status:blocked?"blocked":"ready",findings:fs,proposedMoves:blocked?[]:proposedMoves,proposedDocuments:blocked?[]:cleanDocs,changed:[]}
}
function backup(root:string,rel:string,backupRoot:string):void{const src=join(root,rel);if(!existsSync(src))return;const dst=join(backupRoot,rel);mkdirSync(dirname(dst),{recursive:true});const s=lstatSync(src);if(s.isDirectory())cpSync(src,dst,{recursive:true,errorOnExist:true});else copyFileSync(src,dst)}
export function migratePlugin(rootArg:string,options:MigrationOptions={}):MigrationReport{const report=auditPluginMigration(rootArg);if(!options.apply)return report;report.mode="apply";if(!options.approval){add(report.findings,"migration","unsupported","Mutation requires apply=true and approval=true.",true);report.status="blocked";return report}if(report.status==="blocked")return report;const stamp=new Date().toISOString().replace(/[:.]/g,"-");const backupRoot=options.backupDirectory ? (isAbsolute(options.backupDirectory) ? resolve(options.backupDirectory) : resolve(report.root,options.backupDirectory)) : join(report.root,".plugin-migration-backups",stamp);const bc=resolveContainedPath(report.root,backupRoot,{expectedKind:"missing"});if(!bc.contained||bc.kindOutcome!=="match"){add(report.findings,"backup","unsupported","Backup directory must be a new path inside the plugin root.",true);report.status="blocked";return report}const touched=new Set<string>();for(const d of report.proposedDocuments)touched.add(d.path);for(const m of report.proposedMoves)touched.add(m.from);for(const p of touched)if(!p.includes(":/"))backup(report.root,p,backupRoot);mkdirSync(backupRoot,{recursive:true});for(const m of report.proposedMoves){if(m.from.includes(":/"))continue;const src=join(report.root,m.from),dst=join(report.root,m.to);if(m.to==="mcp.json"&&report.proposedDocuments.some(d=>d.path==="mcp.json")){if(existsSync(src))rmSync(src,{force:true});continue;}if(existsSync(dst)){add(report.findings,m.to,"unsupported","Migration target appeared after audit; no mutation performed for this move.",true);report.status="blocked";return report}mkdirSync(dirname(dst),{recursive:true});renameSync(src,dst);report.changed.push(m.to)}for(const d of report.proposedDocuments){const p=join(report.root,d.path);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(d.document,null,2)+"\n");report.changed.push(d.path)}report.backupDirectory=slash(relative(report.root,backupRoot));report.changed=[...new Set(report.changed)].sort();report.status="applied";return report}
function main(){const {positionals,values}=parseArgs({args:process.argv.slice(2),allowPositionals:true,options:{apply:{type:"boolean",default:false},approve:{type:"boolean",default:false},backup:{type:"string"}}});if(!positionals[0]){console.error("usage: migrate_plugin.js <plugin-directory> [--apply --approve] [--backup <new-contained-directory>]");process.exit(2)}const r=migratePlugin(positionals[0],{apply:values.apply,approval:values.approve,backupDirectory:values.backup});console.log(JSON.stringify(r,null,2));process.exit(r.status==="blocked"?1:0)}
if(process.argv[1]&&resolve(fileURLToPath(import.meta.url))===resolve(process.argv[1]))main();