import type { ExecutionEvent, ProtectedArtifactRef } from "./execution_event_stream.js";

export type TerminalVerbosity="quiet"|"normal"|"verbose";
export type DisplaySurface="terminal"|"ci"|"html";
export interface ProgressBudget { consumed_ms:number; total_ms:number; remaining_ms:number; percent:number }
export interface ProgressCounts { total:number; planned:number; running:number; succeeded:number; failed:number; blocked:number; cancelled:number; skipped:number; completed:number }
export interface ProgressSnapshot {
 schema_version:"1.0"; run_id:string|null; sequence:number; timestamp:string|null; lifecycle:"live"|"completed";
 state:"planned"|"running"|"blocked"|"cancelled"|"failed"|"completed";
 phase:{name:string|null;state:string|null}; counts:ProgressCounts; budget:ProgressBudget;
 failures:Array<{job_id:string|null;phase:string|null}>; artifacts:ProtectedArtifactRef[];
 resume:{available:boolean;guidance:string|null};
}
export interface ProgressProjection { snapshot:ProgressSnapshot; output:string }

const TERMINAL_EVENTS=new Set(["completion","cancellation"]);
const DONE=new Set(["succeeded","failed","blocked","cancelled","skipped"]);
const ANSI=/[\u001b\u009b](?:(?:\][^\u0007]*(?:\u0007|\u001b\\))|(?:\[[0-?]*[ -/]*[@-~])|(?:[PX^_][^\u001b]*(?:\u001b\\))|(?:[@-_]))/g;
const CONTROL=/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g;
function object(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)}
function artifact(value:unknown):value is ProtectedArtifactRef{return object(value)&&value.kind==="protected-artifact-ref"&&typeof value.ref==="string"}
function artifactUri(value:ProtectedArtifactRef):string{return "artifact://"+value.ref.replace(/^sha256:/,"")}
function escapeHtml(value:string):string{return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}
/** Shared untrusted-text boundary for every human-facing projection. */
export function sanitizeDisplayText(value:unknown,surface:DisplaySurface):string{
 let text=String(value??"").replace(ANSI,"").replace(/\r\n?|\n/g," ").replace(CONTROL,"").replace(/\s+/g," ").trim();
 if(surface==="ci")text=text.replace(/%/g,"%25").replace(/:/g,"%3A");
 return surface==="html"?escapeHtml(text):text;
}
function safe(value:unknown,surface:DisplaySurface="terminal"):string{return sanitizeDisplayText(value,surface)||"unknown"}
function finiteNonnegative(value:unknown,fallback:number):number{return typeof value==="number"&&Number.isFinite(value)?Math.max(0,value):fallback}
function progressBudget(data:Record<string,unknown>,prior:ProgressBudget):ProgressBudget{const raw=object(data.budget)?data.budget:null;if(!raw)return prior;const consumed=finiteNonnegative(raw.consumed_ms,prior.consumed_ms),total=finiteNonnegative(raw.total_ms,prior.total_ms),derived=Math.max(0,total-consumed),remaining=Math.min(total,finiteNonnegative(raw.remaining_ms??derived,derived));return{consumed_ms:consumed,total_ms:total,remaining_ms:remaining,percent:total?Math.min(100,Math.max(0,Math.round(consumed/total*100))):0}}
function emptyCounts():ProgressCounts{return{total:0,planned:0,running:0,succeeded:0,failed:0,blocked:0,cancelled:0,skipped:0,completed:0}}
function eventState(event:ExecutionEvent,state:ProgressSnapshot["state"]):ProgressSnapshot["state"]{const status=String(event.data.status??"");if(event.event_type==="completion")return"completed";if(event.event_type==="cancellation")return"cancelled";if(event.event_type==="failure"&&event.job_id===null)return"failed";if(event.event_type==="heartbeat"||event.event_type==="checkpoint"){if(status==="success")return"completed";if(status==="failure"||status==="failed")return"failed";if(status==="cancelled")return"cancelled";if(status==="blocked")return"blocked";if(status==="running")return"running"}if((event.event_type==="job-transition"||event.event_type==="phase-transition")&&status==="running")return"running";return state}
/** Pure canonical projection. It never reads checkpoints, clocks, environment, or the terminal. */
export function projectExecutionProgress(events:readonly ExecutionEvent[]):ProgressSnapshot{const statuses=new Map<string,string>();let phaseName:string|null=null,phaseState:string|null=null,state:ProgressSnapshot["state"]="planned",budget:ProgressBudget={consumed_ms:0,total_ms:0,remaining_ms:0,percent:0};const failures:ProgressSnapshot["failures"]=[],artifacts:ProtectedArtifactRef[]=[];let declaredTotal=0;for(const event of events){state=eventState(event,state);budget=progressBudget(event.data,budget);if(Number.isInteger(event.data.job_count))declaredTotal=Math.max(declaredTotal,Number(event.data.job_count));const phase=typeof event.data.phase==="string"?event.data.phase:null,status=typeof event.data.status==="string"?event.data.status:null;if(event.event_type==="phase-transition"&&phase){phaseName=phase;phaseState=status}if(event.event_type==="job-transition"&&event.job_id&&status)statuses.set(event.job_id,status);if(event.event_type==="checkpoint"&&Array.isArray(event.data.jobs))for(const raw of event.data.jobs){if(object(raw)&&typeof raw.id==="string"&&typeof raw.status==="string")statuses.set(raw.id,raw.status)}if(event.event_type==="failure"&&(event.job_id!==null||phase!==null))failures.push({job_id:event.job_id,phase});for(const value of Object.values(event.data)){if(artifact(value))artifacts.push(value);else if(Array.isArray(value))for(const item of value)if(artifact(item))artifacts.push(item)}}const counts=emptyCounts();counts.total=Math.max(declaredTotal,statuses.size);for(const status of statuses.values())if(status in counts)(counts as unknown as Record<string,number>)[status]++;counts.planned+=Math.max(0,counts.total-statuses.size);counts.completed=[...statuses.values()].filter(x=>DONE.has(x)).length;const last=events.at(-1)??null,lifecycle=last&&TERMINAL_EVENTS.has(last.event_type)||["completed","cancelled","failed"].includes(state)?"completed":"live",resumable=state==="blocked"||state==="cancelled"||state==="failed";return{schema_version:"1.0",run_id:last?.run_id??null,sequence:last?.sequence??0,timestamp:last?.timestamp??null,lifecycle,state,phase:{name:phaseName,state:phaseState},counts,budget,failures,artifacts:[...new Map(artifacts.map(x=>[x.ref,x])).values()],resume:{available:resumable,guidance:resumable?"Resolve the reported condition, then run plugin-creator full-eval with --resume.":null}}}
function summary(s:ProgressSnapshot,surface:DisplaySurface="terminal"):string{return`state=${s.state} lifecycle=${s.lifecycle} phase=${safe(s.phase.name??"none",surface)} phase_state=${safe(s.phase.state??"none",surface)} jobs=${s.counts.completed}/${s.counts.total} running=${s.counts.running} blocked=${s.counts.blocked} failed=${s.counts.failed} budget=${s.budget.consumed_ms}/${s.budget.total_ms}ms (${s.budget.percent}%)`}
export function renderTerminalProgress(events:readonly ExecutionEvent[],verbosity:TerminalVerbosity="normal"):ProgressProjection{const snapshot=projectExecutionProgress(events);if(verbosity==="quiet")return{snapshot,output:""};const lines=[`full-eval progress: ${summary(snapshot)}`];if(snapshot.failures.length)lines.push(...snapshot.failures.map(x=>`failure: phase=${safe(x.phase??"unknown")} job=${safe(x.job_id??"run")}`));if(snapshot.resume.guidance)lines.push("resume: "+safe(snapshot.resume.guidance));if(verbosity==="verbose")for(const event of events)lines.push(`event ${event.sequence}: ${safe(event.event_type)} job=${safe(event.job_id??"run")}`);return{snapshot,output:lines.join("\n")}}
/** Every non-empty line is JSON. Consumers never need to filter human prose. */
export function renderMachineJsonl(events:readonly ExecutionEvent[]):ProgressProjection{let snapshot=projectExecutionProgress([]);const lines:string[]=[];for(let i=0;i<events.length;i++){snapshot=projectExecutionProgress(events.slice(0,i+1));lines.push(JSON.stringify({kind:"full-eval-progress",...snapshot}))}if(!lines.length)lines.push(JSON.stringify({kind:"full-eval-progress",...snapshot}));return{snapshot,output:lines.join("\n")+"\n"}}
/** Workflow command markers are static; every dynamic value is command-neutralized. */
export function renderCiProgress(events:readonly ExecutionEvent[]):ProgressProjection{const snapshot=projectExecutionProgress(events),lines=["::group::full-eval progress",summary(snapshot,"ci"),"::endgroup::"];if(snapshot.failures.length)lines.push("::group::full-eval failures",...snapshot.failures.map(x=>`failure: phase=${safe(x.phase??"unknown","ci")} job=${safe(x.job_id??"run","ci")}`),"::endgroup::");if(snapshot.artifacts.length)lines.push("::group::full-eval artifacts",...snapshot.artifacts.map(x=>artifactUri(x)),"::endgroup::");if(snapshot.resume.guidance)lines.push("::group::full-eval resume",safe(snapshot.resume.guidance,"ci"),"::endgroup::");return{snapshot,output:lines.join("\n")}}
/** Historical replay model plus an accessible, script-free review fragment. */
export function renderHistoricalReview(events:readonly ExecutionEvent[]):ProgressProjection{const snapshots=events.map((_event,index)=>projectExecutionProgress(events.slice(0,index+1))),snapshot=snapshots.at(-1)??projectExecutionProgress([]),rows=snapshots.map(s=>`<li><time datetime="${sanitizeDisplayText(s.timestamp??"","html")}">${sanitizeDisplayText(s.timestamp??"","html")}</time> <strong>${s.lifecycle}: ${s.state}</strong> — phase ${sanitizeDisplayText(s.phase.name??"none","html")}; jobs ${s.counts.completed}/${s.counts.total}; budget ${s.budget.consumed_ms}/${s.budget.total_ms} ms</li>`).join(""),output=`<section aria-labelledby="full-eval-progress-title" data-lifecycle="${snapshot.lifecycle}"><h2 id="full-eval-progress-title">Full evaluation history (${snapshot.lifecycle})</h2><p aria-live="off">${summary(snapshot,"html")}</p><ol>${rows}</ol></section>`;return{snapshot,output}}
export const projectProgress=projectExecutionProgress;export const renderProgressJsonl=renderMachineJsonl;export const renderProgressCi=renderCiProgress;export const renderProgressReview=renderHistoricalReview;
