import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,mkdirSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadPortablePlugin } from "../dist/scripts/portable_loader.js";
import { MCP_SCHEMA_ID,PLUGIN_SCHEMA_ID } from "../dist/scripts/validate_agent_plugin_schema.js";
function fixture(run:(root:string)=>void){const root=mkdtempSync(join(tmpdir(),"portable-loader-"));try{run(root)}finally{rmSync(root,{recursive:true,force:true})}}
function manifest(extra:Record<string,unknown>={}){return{$schema:PLUGIN_SCHEMA_ID,name:"demo-plugin",...extra}}
function skill(root:string,name:string,text?:string){mkdirSync(join(root,"skills",name),{recursive:true});writeFileSync(join(root,"skills",name,"SKILL.md"),text ?? ("---\nname: "+name+"\ndescription: Handles "+name+" tasks\n---\n"))}
test("portable load ignores unknown fields and malformed extensions while strict mode fails policy",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({mystery:true,extensions:"bad"})));skill(root,"good");const portable=loadPortablePlugin(root);assert.equal(portable.status,"accepted");assert.deepEqual(portable.diagnostics.map(x=>x.code),["manifest.unknown-field","manifest.extensions-non-object"]);assert.equal(portable.manifest?.mystery,undefined);assert.equal(portable.manifest?.extensions,undefined);const strict=loadPortablePlugin(root,"strict-authoring");assert.equal(strict.status,"partial");assert.ok(strict.diagnostics.every(x=>x.severity==="error"))}));
test("fatal manifest defects prevent component discovery",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify({$schema:PLUGIN_SCHEMA_ID,name:"Bad--Name"}));skill(root,"good");const r=loadPortablePlugin(root);assert.equal(r.status,"rejected");assert.equal(r.components.length,0)}));
test("invalid skills are skipped independently and discovery is not recursive",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest()));skill(root,"good");skill(root,"bad","not frontmatter");mkdirSync(join(root,"skills","outer","nested"),{recursive:true});writeFileSync(join(root,"skills","outer","nested","SKILL.md"),"---\nname: nested\ndescription: nested\n---\n");const r=loadPortablePlugin(root);assert.equal(r.status,"partial");assert.equal(r.components.find(x=>x.componentId==="good")?.status,"accepted");assert.equal(r.components.find(x=>x.componentId==="bad")?.status,"skipped");assert.equal(r.components.some(x=>x.componentId==="nested"),false)}));
test("missing fixed locations are valid and wrong kinds isolate component types",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest()));assert.equal(loadPortablePlugin(root).status,"accepted");writeFileSync(join(root,"skills"),"wrong");writeFileSync(join(root,"mcp.json"),"[]");const r=loadPortablePlugin(root);assert.equal(r.status,"partial");assert.ok(r.components.some(x=>x.componentType==="skill"&&x.status==="skipped"));assert.ok(r.components.some(x=>x.componentType==="mcp"&&x.status==="skipped"))}));
test("portable MCP uses only mcp.json, permits empty servers, and isolates version mismatch",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest({mcpServers:{legacy:{}}})));writeFileSync(join(root,".mcp.json"),"bad legacy");skill(root,"good");writeFileSync(join(root,"mcp.json"),JSON.stringify({$schema:MCP_SCHEMA_ID,mcpServers:{}}));let r=loadPortablePlugin(root);assert.equal(r.components.find(x=>x.componentType==="mcp")?.status,"accepted");writeFileSync(join(root,"mcp.json"),JSON.stringify({$schema:"https://agent-plugins.org/schemas/1.1.0/mcp.schema.json",mcpServers:{}}));r=loadPortablePlugin(root);assert.equal(r.status,"partial");assert.equal(r.components.find(x=>x.componentId==="good")?.status,"accepted");assert.ok(r.components.some(x=>x.componentType==="mcp"&&x.diagnostics.some(d=>d.code==="mcp.schema-mismatch")))}));
test("unsupported transport and invalid server are isolated from valid siblings",()=>fixture(root=>{writeFileSync(join(root,"plugin.json"),JSON.stringify(manifest()));writeFileSync(join(root,"mcp.json"),JSON.stringify({$schema:MCP_SCHEMA_ID,mcpServers:{ok:{type:"stdio",command:"node"},legacy:{type:"sse",url:"https://example.test"},bad:{}}}));const r=loadPortablePlugin(root,"portable-load",{transports:["stdio"]});assert.equal(r.components.find(x=>x.componentId==="ok")?.status,"accepted");assert.equal(r.components.find(x=>x.componentId==="legacy")?.status,"skipped-unsupported");assert.equal(r.components.find(x=>x.componentId==="bad")?.status,"skipped-invalid")}));
