import { test } from "node:test";
import assert from "node:assert/strict";
import { runIndependentReview, type BranchHost, type BranchRequest, type PublicBranchOutput, type ReviewConfig } from "../dist/scripts/independent_review.js";

const config=():ReviewConfig=>({runId:"hostile",task:"review",approvedContext:{evidence:[{id:"ev",content:"approved"}],contracts:[{id:"contract",content:"approved"}],scenarios:[{id:"scenario",content:"approved"}]},criteria:[{id:"criterion",text:"check"}],matrix:{builders:1,domainChallengers:0,uxChallengers:0,evaluationChallengers:0,verifiers:1,maxConcurrency:1,branchBudgetMs:25,totalBudgetMs:100}});
const output=(r:BranchRequest):PublicBranchOutput=>({summary:r.role,claims:[{id:r.branchId+"-claim",subject:"subject",statement:"statement",evidenceIds:["ev"],criterionIds:["criterion"]}],proposedChanges:[{id:r.branchId+"-change",description:"change",evidenceIds:["ev"],contractIds:["contract"]}]});
const sleep=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));

test("Promise.race enforces branch budget when host ignores AbortSignal and quarantines late output",async()=>{let resolved=false;const host:BranchHost={run(r){if(r.role==="builder")return new Promise(resolve=>setTimeout(()=>{resolved=true;resolve({publicOutput:output(r)})},70));return Promise.resolve({publicOutput:output(r)})}};const result=await runIndependentReview(config(),host);const builder=result.branches.find(x=>x.role==="builder")!;assert.equal(builder.status,"timed-out");assert.equal(builder.lateOutputQuarantined,true);assert.equal(builder.rawOutput,undefined);assert.ok(builder.durationMs<65);await sleep(80);assert.equal(resolved,true);assert.equal(builder.rawOutput,undefined);assert.equal(result.convergence.agreements.length,0)});

test("run-wide deadline independently stops subsequent verifier work",async()=>{const c=config();c.matrix.branchBudgetMs=100;c.matrix.totalBudgetMs=20;let verifierCalls=0;const host:BranchHost={run(r){if(r.role==="verifier")verifierCalls++;return new Promise(()=>{})}};const before=Date.now(),result=await runIndependentReview(c,host);assert.ok(Date.now()-before<80);assert.equal(result.branches.find(x=>x.role==="builder")?.status,"timed-out");assert.equal(result.branches.find(x=>x.role==="verifier")?.status,"skipped-budget");assert.equal(verifierCalls,0)});

test("recursive closed public allowlist strips nested and top-level private or unknown fields",async()=>{let verifierRequest:BranchRequest|undefined;const host:BranchHost={async run(r){if(r.role==="verifier"){verifierRequest=r;return{publicOutput:output(r)}}const value:any=output(r);value.private="nested";value.claims[0].privateReasoning="secret";value.claims[0].evidenceIds=(Object.assign(["ev"],{secret:"array-property"}));value.proposedChanges[0].unknown={token:"leak"};value.risks=[{id:r.branchId+"-risk",statement:"risk",evidenceIds:["ev"],private:"risk-secret"}];return{publicOutput:value,privateReasoning:"top-secret"}}};await runIndependentReview(config(),host);const json=JSON.stringify(verifierRequest?.peerOutputs);assert.ok(verifierRequest);for(const secret of ["nested","secret","array-property","leak","risk-secret","top-secret"])assert.ok(!json.includes(secret),json)});

test("rejects forged or malformed risks and duplicate branch IDs",async()=>{for(const mutate of [(v:any)=>v.risks=[{id:"risk",statement:"forged",evidenceIds:["not-approved"]}],(v:any)=>v.risks=[{id:"risk",statement:"",evidenceIds:["ev"]}],(v:any)=>v.risks=[{id:v.claims[0].id,statement:"collision",evidenceIds:["ev"]}]]){const host:BranchHost={async run(r){const value:any=output(r);if(r.role==="builder")mutate(value);return{publicOutput:value}}};const result=await runIndependentReview(config(),host);assert.equal(result.branches.find(x=>x.role==="builder")?.status,"failed")}});

test("requires globally unique claim/change/risk IDs and unambiguous existing contradicts refs",async()=>{const c=config();c.matrix.domainChallengers=1;const host:BranchHost={async run(r){const value=output(r);if(r.role==="domain-challenger")value.claims[0].id="builder-01-claim";return{publicOutput:value}}};const duplicate=await runIndependentReview(c,host);assert.equal(duplicate.branches.find(x=>x.role==="builder")?.status,"failed");assert.equal(duplicate.branches.find(x=>x.role==="domain-challenger")?.status,"failed");const missingHost:BranchHost={async run(r){const value=output(r);if(r.role==="builder")value.claims[0].contradicts=["missing"];return{publicOutput:value}}};const missing=await runIndependentReview(config(),missingHost);assert.equal(missing.branches.find(x=>x.role==="builder")?.status,"failed");assert.match(missing.branches.find(x=>x.role==="builder")?.error||"",/does not resolve unambiguously/)});

test("keeps a timed-out noncooperative host in the concurrency slot until settlement",async()=>{const c=config();c.matrix={...c.matrix,builders:2,verifiers:1,maxConcurrency:1,branchBudgetMs:15,totalBudgetMs:55};let active=0,maxActive=0,builder2Calls=0,verifierCalls=0;const host:BranchHost={run(r){active++;maxActive=Math.max(maxActive,active);if(r.branchId==="builder-01")return new Promise(resolve=>setTimeout(()=>{active--;resolve({publicOutput:output(r)})},90));if(r.branchId==="builder-02")builder2Calls++;if(r.role==="verifier")verifierCalls++;active--;return Promise.resolve({publicOutput:output(r)})}};const before=Date.now(),result=await runIndependentReview(c,host),elapsed=Date.now()-before;assert.ok(elapsed<85,`orchestrator exceeded total deadline: ${elapsed}ms`);assert.equal(maxActive,1);assert.equal(builder2Calls,0);assert.equal(verifierCalls,0);assert.equal(result.branches.find(x=>x.branchId==="builder-01")?.status,"timed-out");assert.equal(result.branches.find(x=>x.branchId==="builder-02")?.status,"skipped-budget");assert.equal(result.branches.find(x=>x.role==="verifier")?.status,"skipped-budget");await sleep(45);assert.equal(active,0)});

test("preserves explicit cross-subject contradicts links in convergence",async()=>{const c=config();c.matrix={...c.matrix,domainChallengers:1,verifiers:1,maxConcurrency:2};const host:BranchHost={async run(r){const value=output(r);if(r.role==="builder"){value.claims[0].subject="availability";value.claims[0].contradicts=["domain-challenger-01-claim"]}else if(r.role==="domain-challenger")value.claims[0].subject="integrity";return{publicOutput:value}}};const result=await runIndependentReview(c,host);const contradiction=result.convergence.contradictions.find(x=>x.claims.some(c=>c.claimId==="builder-01-claim")&&x.claims.some(c=>c.claimId==="domain-challenger-01-claim"));assert.ok(contradiction);assert.deepEqual(contradiction.claims.find(c=>c.claimId==="builder-01-claim")?.contradicts,["domain-challenger-01-claim"])});

test("rejects every risk without at least one approved evidence reference",async()=>{for(const mutate of [(v:any)=>{v.risks=[{id:"risk",statement:"unsupported",evidenceIds:[]}]},(v:any)=>{v.claims[0].risk="unsupported";v.claims[0].evidenceIds=[]}]){const host:BranchHost={async run(r){const value:any=output(r);if(r.role==="builder")mutate(value);return{publicOutput:value}}};const result=await runIndependentReview(config(),host);assert.equal(result.branches.find(x=>x.role==="builder")?.status,"failed");assert.match(result.branches.find(x=>x.role==="builder")?.error||"",/risk.*approved evidence reference/)}});

