import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { evaluateEfficiencyGate, writeEfficiencyViewer } from "../dist/scripts/efficiency_gate.js";

const benchmark=(cost:any=1)=>({run_summary:{candidate:{wall_latency_ms:{p50:100,p95:200},actual_turns:{mean:2},tokens:{input:{mean:10},output:{mean:5},cached:{mean:0},reasoning:{mean:0},total:{mean:15}},cost:{mean:cost}},baseline:{wall_latency_ms:{p50:90,p95:150},actual_turns:{mean:1},tokens:{input:{mean:8},output:{mean:4},cached:{mean:0},reasoning:{mean:0},total:{mean:12}},cost:{mean:cost===null?null:0.5}},paired:{paired:{p50_wall_latency_ms:{p50:10,coverage:1,covered_pairs:3,expected_pairs:3,confidence_interval_95:{lower:5,upper:15}},p95_wall_latency_ms:{p95:50,coverage:1,covered_pairs:3,expected_pairs:3,confidence_interval_95:{lower:20,upper:80}},actual_turns:{mean:1,coverage:1,covered_pairs:3,expected_pairs:3,confidence_interval_95:{lower:0,upper:2}},tokens:{input:{mean:2,coverage:1},output:{mean:1,coverage:1},cached:{mean:0,coverage:1},reasoning:{mean:0,coverage:1},total:{mean:3,coverage:1}},cost:{mean:cost===null?null:0.5,coverage:cost===null?0:1,confidence_interval_95:cost===null?null:{lower:.2,upper:.8}}}}}});

test("unconfigured dimensions never block and genuine zero telemetry remains available",()=>{const result=evaluateEfficiencyGate(benchmark(),{});assert.equal(result.status,"pass");assert.equal(result.pareto_report.summary.configured,0);assert.equal(result.pareto_report.dimensions["tokens.cached"].current,0);assert.equal(result.pareto_report.dimensions["tokens.cached"].paired_delta,0);assert.equal(result.pareto_report.dimensions["tokens.cached"].availability,"available")});
test("configured regressions fail independently and report absolute, paired CI, and coverage",()=>{const result=evaluateEfficiencyGate(benchmark(),{max_regressions:{p50_wall_latency_ms:9,p95_wall_latency_ms:50,actual_turns:1,"tokens.total":3,cost:.5}});assert.equal(result.status,"fail");assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.verdict,"fail");assert.equal(result.pareto_report.dimensions.p95_wall_latency_ms.verdict,"pass");assert.deepEqual(result.pareto_report.dimensions.p50_wall_latency_ms.confidence_interval_95,{lower:5,upper:15});assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.coverage.paired,1);assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.current,100);assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.baseline,90)});
test("missing cost obeys block, warn, and ignore policies",()=>{for(const [policy,status,verdict] of [["block","blocked","blocked"],["warn","pass","warn"],["ignore","pass","ignored"]] as const){const result=evaluateEfficiencyGate(benchmark(null),{max_regressions:{cost:0},missing_telemetry:policy});assert.equal(result.status,status);assert.equal(result.pareto_report.dimensions.cost.verdict,verdict);assert.equal(result.pareto_report.dimensions.cost.current,null)}});
test("null, missing, hostile, and nonfinite telemetry cannot masquerade as zero",()=>{for(const value of [null,undefined,"0",NaN,Infinity,-1]){const b:any=benchmark();b.run_summary.candidate.actual_turns={mean:value};const result=evaluateEfficiencyGate(b,{max_regressions:{actual_turns:0},missing_telemetry:"block"});assert.equal(result.status,"blocked");assert.equal(result.pareto_report.dimensions.actual_turns.current,null)}});
test("invalid policy and hostile limits are rejected",()=>{assert.throws(()=>evaluateEfficiencyGate(benchmark(),{missing_telemetry:"allow" as any}),/block, warn, or ignore/);for(const value of [NaN,Infinity,-1,"1",null])assert.throws(()=>evaluateEfficiencyGate(benchmark(),{max_regressions:{cost:value as any}}),/finite nonnegative/);assert.throws(()=>evaluateEfficiencyGate(benchmark(),{max_regressions:{hostile:1} as any}),/unknown efficiency dimension/)});
test("viewer renders Pareto dimensions without executable telemetry",()=>{const dir=mkdtempSync(join(tmpdir(),"efficiency-viewer-"));try{const path=writeEfficiencyViewer(dir,evaluateEfficiencyGate(benchmark(),{max_regressions:{cost:1}})),html=readFileSync(path,"utf8");assert.match(html,/Plugin efficiency Pareto report/);assert.match(html,/Paired delta/);assert.match(html,/95% CI/);assert.doesNotMatch(html,/<script/i)}finally{rmSync(dir,{recursive:true,force:true})}});

const producerFixture=(name:string)=>JSON.parse(readFileSync(join(import.meta.dirname,"fixtures","benchmarks",name),"utf8"));
test("real Skill benchmark percentiles and paired seconds normalize to milliseconds",()=>{const result=evaluateEfficiencyGate(producerFixture("skill-benchmark.json"),{max_regressions:{p50_wall_latency_ms:1000,"tokens.total":8},missing_telemetry:"block"});assert.equal(result.status,"pass");const latency=result.pareto_report.dimensions.p50_wall_latency_ms;assert.equal(latency.current,2000);assert.equal(latency.baseline,1000);assert.equal(latency.paired_delta,1000);assert.deepEqual(latency.confidence_interval_95,{lower:800,upper:1200});assert.equal(latency.coverage.current,1);assert.equal(result.pareto_report.dimensions["tokens.total"].paired_delta,8)});
test("real Skill benchmark exposes genuine p95",()=>{const result=evaluateEfficiencyGate(producerFixture("skill-benchmark.json"),{max_regressions:{p95_wall_latency_ms:1180},missing_telemetry:"block"});const latency=result.pareto_report.dimensions.p95_wall_latency_ms;assert.equal(result.status,"pass");assert.equal(latency.current,2180);assert.equal(latency.baseline,1090);assert.equal(latency.paired_delta,1180)});
test("a mean-only duration cannot masquerade as p50",()=>{const fixture=producerFixture("skill-benchmark.json");delete fixture.run_summary.with_skill.time_seconds.p50;const result=evaluateEfficiencyGate(fixture,{max_regressions:{p50_wall_latency_ms:1000},missing_telemetry:"block"});assert.equal(result.status,"blocked");assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.current,null)});
test("a paired mean cannot masquerade as a p50 delta",()=>{const fixture=producerFixture("skill-benchmark.json");delete fixture.run_summary.delta.paired.time_seconds.p50;fixture.run_summary.with_skill.time_seconds.p50=null;const result=evaluateEfficiencyGate(fixture,{max_regressions:{p50_wall_latency_ms:1000},missing_telemetry:"block"});assert.equal(result.status,"blocked");assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.paired_delta,null)});
test("real Agent benchmark consumes distributions, scalar resource fields, aliases, and paired seconds",()=>{const result=evaluateEfficiencyGate(producerFixture("agent-benchmark.json"),{max_regressions:{p50_wall_latency_ms:1000,p95_wall_latency_ms:1400,actual_turns:1,"tokens.total":10,cost:.01},missing_telemetry:"block"});assert.equal(result.status,"pass");assert.equal(result.pareto_report.dimensions.p50_wall_latency_ms.paired_delta,1000);assert.deepEqual(result.pareto_report.dimensions.p50_wall_latency_ms.confidence_interval_95,{lower:700,upper:1300});assert.equal(result.pareto_report.dimensions.p95_wall_latency_ms.current,2900);assert.equal(result.pareto_report.dimensions.p95_wall_latency_ms.paired_delta,1400);for(const dim of ["actual_turns","tokens.total","cost"] as const)assert.equal(result.pareto_report.dimensions[dim].coverage.current,1)});
