import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { ExecutionEventWriter, protectedArtifactRef, replayExecutionEvents, sanitizeExecutionEventData } from "../dist/scripts/execution_event_stream.js";
const artifact=(name="x")=>protectedArtifactRef("/protected/"+name,"a".repeat(64));
const samples:Array<[any,string|null,Record<string,unknown>]> = [
 ["evaluation-created",null,{status:"planned",graph_hash:"hash",plugin:artifact("plugin"),workspace:artifact("workspace")}],
 ["phase-transition","job-1",{phase:"validation",status:"running"}],
 ["job-transition","job-1",{phase:"validation",status:"running",attempt:1,outputs:[artifact("output")]}],
 ["heartbeat",null,{status:"running",resume:false}],
 ["retry","job-1",{phase:"validation",attempt:2}],
 ["checkpoint",null,{revision:1,status:"running",state:artifact("state"),jobs:[{id:"job-1",phase:"validation",status:"succeeded",attempts:1}]}],
 ["approval-requested","job-2",{phase:"review",status:"blocked",reason:"human review required"}],
 ["failure","job-1",{phase:"validation",status:"failed"}],
 ["cancellation",null,{status:"cancelled"}],
 ["completion",null,{status:"success",archive:artifact("archive")}],
];
function temp(){const dir=mkdtempSync(join(tmpdir(),"execution-events-"));return{dir,path:join(dir,"events.jsonl")}}
function line(overrides:Record<string,unknown>={}):any{return{schema_version:"1.0",event_id:randomUUID(),event_type:"heartbeat",run_id:"run-1",job_id:null,sequence:1,timestamp:"2026-09-17T19:52:00.000Z",causal_event_id:null,data:{status:"running"},...overrides}}
function write(path:string,events:any[]){writeFileSync(path,events.map(x=>JSON.stringify(x)).join("\n")+"\n")}

test("every v1 event has a strict schema and replays exact ordered causality",()=>{const {dir,path}=temp();try{const writer=new ExecutionEventWriter(path,"run-1");const events=samples.map(([type,job,data])=>writer.append(type,job,data));const replay=replayExecutionEvents(path);assert.equal(replay.events.length,samples.length);assert.equal(new Set(events.map(e=>e.event_id)).size,events.length);for(let i=0;i<events.length;i++){assert.equal(events[i].sequence,i+1);assert.equal(events[i].causal_event_id,i?events[i-1].event_id:null);if(i)assert.ok(events[i].timestamp>events[i-1].timestamp)}assert.deepEqual(replay.job_counts,{succeeded:1});assert.equal(replay.interrupted_tail,false)}finally{rmSync(dir,{recursive:true,force:true})}});

test("known schemas reject missing, extra, malformed, and invalid enum data",()=>{const {dir,path}=temp();try{for(const bad of [line({data:{}}),line({data:{status:"invented"}}),line({data:{status:"running",extra:true}}),line({extra:true}),line({job_id:7}),line({event_id:"not-uuid"}),line({timestamp:"2026-09-17 19:52:00Z"}),line({schema_version:"1.1"})]){write(path,[bad]);assert.throws(()=>replayExecutionEvents(path),/invalid execution event|known event/)}const requiredField:Record<string,string>={"evaluation-created":"status","phase-transition":"phase","job-transition":"phase",heartbeat:"status",retry:"phase",checkpoint:"revision","approval-requested":"phase",failure:"status",cancellation:"status",completion:"status"};for(const [type,job,data] of samples){const malformed=line({event_type:type,job_id:job,data:{...data}});delete malformed.data[requiredField[type]];write(path,[malformed]);assert.throws(()=>replayExecutionEvents(path),/invalid execution event/,type)}}finally{rmSync(dir,{recursive:true,force:true})}});

test("duplicate IDs, non-monotonic timestamps, and anything but the exact causal chain fail",()=>{const {dir,path}=temp();try{const first=line(),second=line({sequence:2,timestamp:"2026-09-17T19:52:00.001Z",causal_event_id:(null as any)});for(const mutation of [()=>{second.causal_event_id=randomUUID()},()=>{second.causal_event_id=first.event_id;second.event_id=first.event_id},()=>{second.causal_event_id=first.event_id;second.timestamp=first.timestamp}]){Object.assign(second,line({sequence:2,timestamp:"2026-09-17T19:52:00.001Z",causal_event_id:first.event_id}));mutation();write(path,[first,second]);assert.throws(()=>replayExecutionEvents(path),/causal|duplicate|monotonic/)}}finally{rmSync(dir,{recursive:true,force:true})}});

test("interrupted tail remains detectable, ignored, and append-blocking",()=>{const {dir,path}=temp();try{new ExecutionEventWriter(path,"run-1").append("heartbeat",null,{status:"running"});writeFileSync(path,readFileSync(path,"utf8")+'{"schema_version":"1.0"');const replay=replayExecutionEvents(path);assert.equal(replay.interrupted_tail,true);assert.equal(replay.events.length,1);assert.throws(()=>new ExecutionEventWriter(path,"run-1"),/interrupted execution event tail/)}finally{rmSync(dir,{recursive:true,force:true})}});

test("supported unknown events are retained while unknown majors fail",()=>{const {dir,path}=temp();try{write(path,[line({schema_version:"1.1",event_type:"future-event",data:{arbitrary:true}})]);assert.deepEqual(replayExecutionEvents(path).unknown_events,[{sequence:1,event_type:"future-event"}]);write(path,[line({schema_version:"2.0",event_type:"future-event",data:{}})]);assert.throws(()=>replayExecutionEvents(path),/unsupported execution event schema/)}finally{rmSync(dir,{recursive:true,force:true})}});

test("normalizes prefixed and separator credential keys without leaking their values",()=>{const input:any={OPENAI_API_KEY:"openai-value","X-API-Key":"header-value",AWS_SECRET_ACCESS_KEY:"aws-secret",AZURE_CLIENT_SECRET:"azure-secret",GOOGLE_API_KEY:"google-secret",GITHUB_TOKEN:"github-exact",PRIVATE_KEY:"private-exact",prefix_OPENAI_API_KEY_suffix:"prefixed-value","vendor.x_api_key":"dotted-value",githubToken:"github-value",bearer_token:"bearer-value",prefixed_token_suffix:"token-value",prefixed_secret_suffix:"secret-value",ssh_private_key:"private-value",safe_key_name:"visible"};const data:any=sanitizeExecutionEventData(input);for(const key of Object.keys(input).filter(key=>key!=="safe_key_name"))assert.equal(data[key],"[REDACTED]",key);assert.equal(data.safe_key_name,"visible");for(const secret of Object.values(input).filter(value=>value!=="visible"))assert.equal(JSON.stringify(data).includes(String(secret)),false)});

test("redacts underscore credential assignments and separator or case variants as whole scalars",()=>{const unsafe=["OPENAI_API_KEY=openai-secret","export AWS_SECRET_ACCESS_KEY = aws-secret","AZURE_CLIENT_SECRET:azure-secret","GOOGLE_API_KEY=google-secret","GITHUB_TOKEN=github-secret","PRIVATE_KEY=private-secret","openai-api-key=hyphen-secret","aws.secret.access.key=dot-secret","AzureClientSecret=camel-secret","prefix_PRIVATE_KEY=suffixed-secret"];const data:any=sanitizeExecutionEventData({values:unsafe,safe:"API response key=value"});assert.deepEqual(data.values,unsafe.map(()=>"[REDACTED]"));assert.equal(data.safe,"API response key=value");for(const secret of unsafe)assert.equal(JSON.stringify(data).includes(secret),false)});

test("serialized event stream redacts prefixed and suffixed labels for every secret family",()=>{const {dir,path}=temp();try{const families=["OPENAI_API_KEY","AWS_SECRET_ACCESS_KEY","AZURE_CLIENT_SECRET","GOOGLE_API_KEY","GITHUB_TOKEN","API_KEY","ACCESS_KEY","SECRET_KEY","PRIVATE_KEY","CLIENT_SECRET","SECRET_ACCESS_KEY","REFRESH_TOKEN","ID_TOKEN","BEARER_TOKEN","PASSWORD","PASSWD","CREDENTIAL","CREDENTIALS","AUTHORIZATION","COOKIE","JWT","SECRET","TOKEN"];const variants=families.flatMap((family,index)=>{const words=family.toLowerCase().split("_");const camel=words[0]+words.slice(1).map(word=>word[0].toUpperCase()+word.slice(1)).join("");return [`prefix_${family}_suffix=secret-${index}-underscore`,`pre.${words.join("-")}.post:secret-${index}-separator`,`before${camel[0].toUpperCase()+camel.slice(1)}After=secret-${index}-camel`];});const writer=new ExecutionEventWriter(path,"run-1");for(const value of variants)writer.append("approval-requested",null,{phase:"release",status:"blocked",reason:`approval includes ${value} and must redact the whole reason`});const serialized=readFileSync(path,"utf8");for(const [index,event] of replayExecutionEvents(path).events.entries()){assert.equal(event.data.reason,"[REDACTED]",variants[index]);assert.equal(serialized.includes(variants[index]),false,variants[index]);assert.equal(serialized.includes(`secret-${Math.floor(index/3)}-`),false)}assert.equal(serialized.includes("[REDACTED]"),true)}finally{rmSync(dir,{recursive:true,force:true})}});

test("redacts JWT keys and values, URL userinfo, cloud, GitHub, bearer, and private-key values",()=>{const jwt="eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0In0.c2lnbmF0dXJl";const secrets=[jwt,"https://user:pass@example.test/private","Bearer abc.def.ghi","AKI\u0041ABCDEFGHIJKLMNOP","ASI\u0041ABCDEFGHIJKLMNOP","github\u005fpat_abcdefghijklmnopqrstuvwxyz123456","gh\u0070_abcdefghijklmnopqrstuvwxyz","AIz\u0061SyD-abcdefghijklmnopqrstuvwxyz123456","xox\u0062-1234567890-abcdefghij","sk\u005flive_abcdefghijklmnopqrstuvwxyz","-----BEGIN PRIVATE KEY-----\nmaterial"] as const;const data:any=sanitizeExecutionEventData({jwt_value:"key-selected",nested:secrets.map(value=>({value})),safe:"https://example.test/public"});assert.equal(data.jwt_value,"[REDACTED]");assert.equal(data.safe,"https://example.test/public");assert.deepEqual(data.nested.map((item:any)=>item.value),secrets.map(()=>"[REDACTED]"));for(const secret of secrets)assert.equal(JSON.stringify(data).includes(secret),false)});

test("recursively removes private and system conversation collections",()=>{const input:any={public_messages:[{content:"safe public text"}],wrapper:{private_messages:[{role:"user",content:"private one"},{nested:{content:"private two"}}],system_conversation:{messages:[{content:"system secret"}]}},artifact:artifact("safe")};const data:any=sanitizeExecutionEventData(input);assert.equal(data.wrapper.private_messages,"[REDACTED]");assert.equal(data.wrapper.system_conversation,"[REDACTED]");assert.equal(data.public_messages[0].content,"safe public text");assert.equal(data.artifact.kind,"protected-artifact-ref");for(const secret of ["private one","private two","system secret"])assert.equal(JSON.stringify(data).includes(secret),false)});

test("stale writer instances reload under lock and compare-and-append",()=>{const {dir,path}=temp();try{const a=new ExecutionEventWriter(path,"run-1"),b=new ExecutionEventWriter(path,"run-1");a.append("heartbeat",null,{status:"running"});b.append("heartbeat",null,{status:"running"});a.append("heartbeat",null,{status:"running"});const replay=replayExecutionEvents(path);assert.deepEqual(replay.events.map(e=>e.sequence),[1,2,3]);assert.equal(replay.events[2].causal_event_id,replay.events[1].event_id)}finally{rmSync(dir,{recursive:true,force:true})}});

test("concurrent process writers serialize without lost or corrupt events",async()=>{const {dir,path}=temp();try{const module=resolve("dist/scripts/execution_event_stream.js");const code=`import {ExecutionEventWriter} from ${JSON.stringify(module)};new ExecutionEventWriter(process.argv[1],"run-1").append("heartbeat",null,{status:"running"});`;await Promise.all(Array.from({length:12},()=>new Promise<void>((ok,fail)=>{const child=spawn(process.execPath,["--input-type=module","-e",code,path],{stdio:"pipe"});let err="";child.stderr.on("data",x=>err+=x);child.on("exit",status=>status===0?ok():fail(new Error(err||String(status))))})));const replay=replayExecutionEvents(path);assert.equal(replay.events.length,12);assert.deepEqual(replay.events.map(e=>e.sequence),Array.from({length:12},(_,i)=>i+1))}finally{rmSync(dir,{recursive:true,force:true})}});


test("event append recovers a lock abandoned by a dead owner",()=>{const {dir,path}=temp();try{writeFileSync(path+".lock",JSON.stringify({pid:999999999,created_at:new Date(0).toISOString()}));new ExecutionEventWriter(path,"run-1").append("heartbeat",null,{status:"running"});assert.equal(replayExecutionEvents(path).events.length,1);assert.equal(existsSync(path+".lock"),false)}finally{rmSync(dir,{recursive:true,force:true})}});
