// Execute every scaffolded current/baseline run in a fresh isolated workspace.
import { cpSync, existsSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { tmpdir } from "node:os";
import { artifactHash, expectedExecutionBinding, listRunDirs } from "./evaluation_provenance.js";
import { createRunner } from "./runners/index.js";
import { PairedExecutionError } from "./runners/paired.js";
import type { DeclaredCapabilities, PairedExecutionEvidence, PairedExecutionPlan, PairedRunner } from "./runners/paired.js";

export interface ExecutePairOptions { skillPath:string;workspace:string;baseline:"old_skill"|"without_skill";baselineSkillPath?:string;runner?:string;model?:string|null;signal?:AbortSignal; }
export interface ExecutePairOutcome { status:"complete"|"blocked"|"failed"|"cancelled";completed:string[];failures:Array<{run:string;code:string;message:string;exit_reason:string}>; }
function json(path:string):any{return JSON.parse(readFileSync(path,"utf8"));}
function atomic(path:string,value:unknown):void{const temp=`${path}.tmp-${process.pid}`;writeFileSync(temp,JSON.stringify(value,null,2)+"\n",{mode:0o600});renameSync(temp,path);}
function contained(root:string,path:string):boolean{const rel=relative(realpathSync(root),realpathSync(path));return rel===""||(!rel.startsWith("..")&&!isAbsolute(rel));}
function fixtureSources(metadata:any,evalDir:string,skillPath:string):Array<{source:string;target:string}>{const files:string[]=Array.isArray(metadata.files)?metadata.files.map(String):[];return files.map((file:string)=>{if(isAbsolute(file))throw new PairedExecutionError("invalid-plan",`Fixture path must be relative: ${file}`,"invalid-plan");const roots=[skillPath,evalDir,dirname(evalDir)];for(const root of roots){const path=resolve(root,file);if(existsSync(path)&&contained(root,path))return{source:path,target:file};}throw new PairedExecutionError("invalid-plan",`Fixture is missing or escapes its scenario root: ${file}`,"invalid-plan");});}
function assertNoSymlinks(path:string):void{if(lstatSync(path).isSymbolicLink())throw new PairedExecutionError("invalid-plan",`Fixture symlinks are not allowed: ${path}`,"invalid-plan");if(lstatSync(path).isDirectory())for(const name of readdirSync(path))assertNoSymlinks(join(path,name));}
function stage(source:string|null,skillName:string,fixtures:Array<{source:string;target:string}>):string{const cwd=mkdtempSync(join(tmpdir(),"skill-paired-run-"));if(source){mkdirSync(join(cwd,".agents","skills"),{recursive:true});cpSync(source,join(cwd,".agents","skills",skillName),{recursive:true,dereference:false});}for(const fixture of fixtures){assertNoSymlinks(fixture.source);const target=resolve(cwd,fixture.target);if(relative(cwd,target).startsWith(".."))throw new PairedExecutionError("invalid-plan",`Fixture target escapes workspace: ${fixture.target}`,"invalid-plan");mkdirSync(dirname(target),{recursive:true});cpSync(fixture.source,target,{recursive:true,dereference:false});}mkdirSync(join(cwd,"outputs"),{recursive:true});return cwd;}
function persistOutcome(runDir:string,evidence:PairedExecutionEvidence,plan:PairedExecutionPlan,status:"failed"|"cancelled",failureCode:string,message:string):void{mkdirSync(join(runDir,"outputs"),{recursive:true});writeFileSync(join(runDir,"transcript.json"),evidence.transcript);atomic(join(runDir,"events.json"),evidence.events);atomic(join(runDir,"timing.json"),{total_duration_seconds:evidence.durationSeconds,tokens:null,total_tokens:null,token_availability_reason:"Execution did not complete",host_version:evidence.hostVersion,exit_reason:evidence.exitReason,exit_code:evidence.exitCode,max_turns:plan.maxTurns??40,timeout_seconds:plan.timeoutSeconds,status,failure_code:failureCode,message});atomic(join(runDir,"execution-outcome.json"),{schema_version:"1.0",status,failure_code:failureCode,message,host_version:evidence.hostVersion,exit_reason:evidence.exitReason,exit_code:evidence.exitCode,command:evidence.command,artifact_sha256:{"timing.json":artifactHash(join(runDir,"timing.json")),"transcript.json":artifactHash(join(runDir,"transcript.json")),"events.json":artifactHash(join(runDir,"events.json"))}});}
function writeEvidence(runDir:string,result:Awaited<ReturnType<PairedRunner["executePaired"]>>,plan:PairedExecutionPlan,source:string|null):void{mkdirSync(join(runDir,"outputs"),{recursive:true});writeFileSync(join(runDir,"outputs","result.txt"),result.output);writeFileSync(join(runDir,"transcript.json"),result.transcript);atomic(join(runDir,"events.json"),result.events);atomic(join(runDir,"grading.json"),{expectations:result.expectations,summary:{pass_rate:result.expectations.length?result.expectations.filter(x=>x.passed).length/result.expectations.length:0,passed:result.expectations.filter(x=>x.passed).length,failed:result.expectations.filter(x=>!x.passed).length,total:result.expectations.length}});atomic(join(runDir,"timing.json"),{total_duration_seconds:result.durationSeconds,tokens:result.tokens,total_tokens:result.tokens,token_availability_reason:result.tokenAvailabilityReason,host_version:result.hostVersion,exit_reason:result.exitReason,exit_code:result.exitCode,max_turns:plan.maxTurns??40,timeout_seconds:plan.timeoutSeconds});const binding=expectedExecutionBinding(runDir);if(!binding)throw new Error(`Missing execution binding for ${runDir}`);atomic(join(runDir,"execution-evidence.json"),{schema_version:"1.0",...binding,executor:{adapter:"goose",host_version:result.hostVersion,exit_reason:result.exitReason,command:result.command,executed_skill_sha256:source?artifactHash(source):null},artifact_sha256:{outputs:artifactHash(join(runDir,"outputs")),"grading.json":artifactHash(join(runDir,"grading.json")),"timing.json":artifactHash(join(runDir,"timing.json")),"transcript.json":artifactHash(join(runDir,"transcript.json"))}});}
function capabilities(value:any):DeclaredCapabilities{if(!value||typeof value!=="object"||Array.isArray(value))throw new PairedExecutionError("capability-mismatch","Scenario capabilities must be an object","capability-mismatch");return{filesystem:value.filesystem,agent_runner:value.agent_runner,browser:value.browser,network:value.network,tools:value.tools};}
export async function executePairedRuns(options:ExecutePairOptions):Promise<ExecutePairOutcome>{const runner=createRunner(options.runner) as ReturnType<typeof createRunner>&PairedRunner;if(typeof runner.executePaired!=="function")return{status:"blocked",completed:[],failures:[{run:"*",code:"unsupported-runner",message:"Runner does not support paired execution",exit_reason:"unsupported-runner"}]};const completed:string[]=[],failures:ExecutePairOutcome["failures"]=[];const skillName=basename(resolve(options.skillPath));for(const runDir of listRunDirs(resolve(options.workspace))){const evalDir=dirname(dirname(runDir)),metadata=json(join(evalDir,"eval_metadata.json")),configuration=basename(dirname(runDir));const source=configuration==="with_skill"?resolve(options.skillPath):options.baseline==="old_skill"?(options.baselineSkillPath?resolve(options.baselineSkillPath):null):null;if(configuration==="old_skill"&&(!source||!existsSync(source))){failures.push({run:runDir,code:"invalid-plan",message:"old_skill execution requires an existing baselineSkillPath",exit_reason:"invalid-plan"});continue;}let cwd="",plan:PairedExecutionPlan|undefined;try{const declared=capabilities(metadata.capabilities),tools=declared.tools;const fixtures=fixtureSources(metadata,evalDir,resolve(options.skillPath));cwd=stage(source,skillName,fixtures);const budget=metadata.budget??{};plan={prompt:String(metadata.prompt??""),assertions:Array.isArray(metadata.assertions)?metadata.assertions.map(String):[],cwd,model:options.model??(metadata.model?String(metadata.model):null),tools,capabilities:declared,maxTurns:Number(budget.max_turns??40),timeoutSeconds:Number(budget.timeout_seconds??300),configuration,skillName,signal:options.signal};writeEvidence(runDir,await runner.executePaired(plan),plan,source);completed.push(runDir);}catch(error){const typed=error instanceof PairedExecutionError?error:new PairedExecutionError("host-exit",(error as Error).message,"adapter-error");failures.push({run:runDir,code:typed.code,message:typed.message,exit_reason:typed.exitReason});if(plan&&typed.evidence)persistOutcome(runDir,typed.evidence,plan,typed.code==="cancelled"?"cancelled":"failed",typed.code,typed.message);if(typed.code==="cancelled")break;}finally{if(cwd)rmSync(cwd,{recursive:true,force:true});}}const cancelled=failures.some(x=>x.code==="cancelled"),blocked=failures.some(x=>["command-not-found","unsupported-runner","model-unavailable","tool-unavailable","capability-mismatch"].includes(x.code));return{status:cancelled?"cancelled":failures.length?(blocked?"blocked":"failed"):"complete",completed,failures};}
